<?php
declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/app/Support/Cors.php';require_once $root.'/app/Support/Realtime.php';require_once $root.'/app/Support/AccessPolicy.php';require_once $root.'/app/Services/NivoEngine.php';require_once $root.'/app/Services/AutomationEngine.php';require_once $root.'/app/Services/ChannelProviderGateway.php';
header('Content-Type: application/json; charset=utf-8');
header('X-Robots-Tag: noindex, nofollow, nosnippet', true);

$apiCorsOrigin = ZynkoCors::requestOrigin();
ZynkoCors::handleAuthenticatedApiPreflight();
if ($apiCorsOrigin !== '') {
    ZynkoCors::send(
        $apiCorsOrigin,
        ['GET', 'POST', 'OPTIONS'],
        ['Authorization', 'Content-Type', 'Accept', 'Idempotency-Key', 'X-Requested-With']
    );
}

function out(int $status,bool $ok,string $message,array $data=[]): never { http_response_code($status); echo json_encode(['ok'=>$ok,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function envCfg(string $p): array { $v=@parse_ini_file($p,false,INI_SCANNER_RAW); return is_array($v)?$v:[]; }
function db(): PDO { static $pdo; global $root; if($pdo)return $pdo;$e=envCfg($root.'/.env');$dsn='mysql:host='.($e['DB_HOST']??'127.0.0.1').';port='.($e['DB_PORT']??'3306').';dbname='.($e['DB_DATABASE']??'zynko').';charset=utf8mb4';$pdo=new PDO($dsn,$e['DB_USERNAME']??'root',$e['DB_PASSWORD']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec("SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci");return $pdo; }
function uuid4(): string {$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
function bearer(): string { $h=$_SERVER['HTTP_AUTHORIZATION']??''; if(!preg_match('/^Bearer\s+(.+)$/i',$h,$m))out(401,false,'Falta Authorization: Bearer <API_KEY>.'); return trim($m[1]); }
function auth(): array { $key=bearer();$prefix=explode('.',$key,2)[0]??'';if(!str_starts_with($prefix,'zk_'))out(401,false,'Clave API inválida.');$q=db()->prepare('SELECT * FROM api_keys WHERE key_prefix=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>NOW())');$q->execute([$prefix]);$r=$q->fetch();if(!$r||!hash_equals($r['key_hash'],hash('sha256',$key)))out(401,false,'Clave API inválida o revocada.');try{ZynkoAccessPolicy::enforce(db(),$r);}catch(OverflowException $e){out(429,false,$e->getMessage());}catch(RuntimeException $e){out(403,false,$e->getMessage());}db()->prepare('UPDATE api_keys SET last_used_at=NOW() WHERE id=?')->execute([$r['id']]);return $r; }
function hasScope(array $k,string $scope): void {$s=json_decode($k['scopes_json']??'[]',true)?:[];if(!in_array($scope,$s,true))out(403,false,'La clave no tiene el permiso '.$scope.'.');}
function hasAnyScope(array $k,array $scopes): void {$s=json_decode($k['scopes_json']??'[]',true)?:[];foreach($scopes as $scope)if(in_array($scope,$s,true))return;out(403,false,'La clave no tiene permiso para recibir mensajes.');}
function body(): array {$raw=file_get_contents('php://input')?:'';$j=json_decode($raw,true);if(!is_array($j))out(400,false,'JSON inválido.');return $j;}
function planAllows(int $tid,string $feature): bool {try{$q=db()->prepare('SELECT sp.module_access_json,sp.features_json,sp.active,ts.status FROM tenant_subscriptions ts JOIN subscription_plans sp ON sp.id=ts.plan_id WHERE ts.tenant_id=? LIMIT 1');$q->execute([$tid]);$row=$q->fetch();if(!$row)return false;if((int)($row['active']??0)!==1||!in_array((string)($row['status']??''),['active','grace','trial'],true))return false;$m=json_decode($row['module_access_json']??'{}',true)?:[];if(array_key_exists($feature,$m))return (bool)$m[$feature];$f=json_decode($row['features_json']??'[]',true)?:[];foreach($f as $k=>$v){if(is_string($k)&&$k===$feature)return (bool)$v;if(is_string($v)&&$v===$feature)return true;}return false;}catch(Throwable $e){return false;}}
function monthlyChatLimit(int $tid): ?int {try{$q=db()->prepare('SELECT sp.max_monthly_chats FROM tenant_subscriptions ts JOIN subscription_plans sp ON sp.id=ts.plan_id WHERE ts.tenant_id=? AND ts.status IN ("active","grace","trial") LIMIT 1');$q->execute([$tid]);$v=$q->fetchColumn();if($v===false||$v===null)return null;$n=(int)$v;return $n>0?$n:null;}catch(Throwable $e){return null;}}
function enforceMonthlyChatLimit(int $tid): void {$limit=monthlyChatLimit($tid);if($limit===null)return;try{$q=db()->prepare("SELECT COUNT(*) FROM conversations WHERE tenant_id=? AND created_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01') AND created_at<DATE_ADD(LAST_DAY(CURDATE()),INTERVAL 1 DAY)");$q->execute([$tid]);$used=(int)$q->fetchColumn();if($used>=$limit)out(429,false,'La empresa alcanzó el límite de '.number_format($limit).' chats nuevos de este mes.',['limit'=>$limit,'used'=>$used,'period'=>'month']);}catch(Throwable $e){}}
function logReq(int $tid,int $keyId,string $endpoint,string $idem,int $status,array $payload): void {try{db()->prepare('INSERT INTO api_request_logs(tenant_id,api_key_id,endpoint,idempotency_key,http_status,payload_hash,created_at) VALUES(?,?,?,?,?,?,NOW())')->execute([$tid,$keyId,$endpoint,$idem?:null,$status,hash('sha256',json_encode($payload))]);}catch(Throwable $e){}}
try{
 $key=auth();$tid=(int)$key['tenant_id'];$method=$_SERVER['REQUEST_METHOD']??'GET';$path=trim($_GET['r']??($_SERVER['PATH_INFO']??''),'/');
 if($method==='GET'&&($path===''||$path==='v1/health'))out(200,true,'ZYNKO API disponible.',['version'=>'v1','tenant_id'=>$tid]);
 if(!planAllows($tid,'api'))out(403,false,'El plan o estado de suscripción de esta empresa no permite usar la API de ZYNKO.');
 if($method==='GET'&&$path==='v1/channels'){
  hasAnyScope($key,['channels:read','messages:send','messages:receive']);if(!planAllows($tid,'api'))out(403,false,'El plan de esta empresa no incluye acceso API.');$q=db()->prepare('SELECT id,uuid,type,name,display_address,status,created_at FROM channels WHERE tenant_id=? ORDER BY name,id');$q->execute([$tid]);out(200,true,'Canales disponibles.',['channels'=>$q->fetchAll()]);
 }
 if($method==='POST'&&$path==='v1/messages/send'){
  hasScope($key,'messages:send');if(!planAllows($tid,'api'))out(403,false,'El plan de esta empresa no incluye acceso API.');$j=body();$idem=trim($_SERVER['HTTP_IDEMPOTENCY_KEY']??'');if($idem!==''){$q=db()->prepare('SELECT response_json,http_status FROM api_idempotency WHERE tenant_id=? AND idempotency_key=?');$q->execute([$tid,$idem]);if($old=$q->fetch()){http_response_code((int)$old['http_status']);echo $old['response_json'];exit;}}
  $channel=(int)($j['channel_id']??0);$to=trim((string)($j['to']??''));$name=trim((string)($j['contact_name']??$to));$text=trim((string)($j['message']??''));if($channel<1||$to===''||$text==='')out(422,false,'Requiere channel_id, to y message.');$q=db()->prepare('SELECT * FROM channels WHERE id=? AND tenant_id=?');$q->execute([$channel,$tid]);$ch=$q->fetch();if(!$ch)out(404,false,'Canal no encontrado.');if($ch['status']!=='connected')out(409,false,'El canal existe pero aún no está conectado/autorizado con el proveedor.');
  $q=db()->prepare('SELECT contact_id FROM contact_identities WHERE tenant_id=? AND channel_id=? AND external_id=? LIMIT 1');$q->execute([$tid,$channel,$to]);$contact=(int)($q->fetchColumn()?:0);if(!$contact&&$ch['type']==='whatsapp'){$q=db()->prepare('SELECT id FROM contacts WHERE tenant_id=? AND phone=? LIMIT 1');$q->execute([$tid,$to]);$contact=(int)($q->fetchColumn()?:0);}if(!$contact){db()->prepare('INSERT INTO contacts(tenant_id,uuid,name,phone,email) VALUES(?,?,?,?,?)')->execute([$tid,uuid4(),$name,$ch['type']==='whatsapp'?$to:null,$ch['type']==='email'?$to:null]);$contact=(int)db()->lastInsertId();}db()->prepare('INSERT INTO contact_identities(tenant_id,contact_id,channel_id,external_id,profile_json) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE contact_id=VALUES(contact_id),profile_json=VALUES(profile_json)')->execute([$tid,$contact,$channel,$to,json_encode(['name'=>$name],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
  $q=db()->prepare("SELECT id FROM conversations WHERE tenant_id=? AND channel_id=? AND contact_id=? AND status IN ('open','pending') ORDER BY id DESC LIMIT 1");$q->execute([$tid,$channel,$contact]);$cid=(int)($q->fetchColumn()?:0);$newConversation=false;if(!$cid){enforceMonthlyChatLimit($tid);db()->prepare("INSERT INTO conversations(tenant_id,uuid,channel_id,contact_id,status,last_message_at) VALUES(?,?,?,?,'open',NOW())")->execute([$tid,uuid4(),$channel,$contact]);$cid=(int)db()->lastInsertId();$newConversation=true;zynkoRealtimePublish(db(),$tid,'conversation.created',['conversation_id'=>$cid,'channel'=>$ch['type'],'contact_name'=>$name],'conversation',(string)$cid);}
  $uuid=uuid4();db()->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,'out','system','text',?,'queued',NOW())")->execute([$tid,$cid,$uuid,$text]);$messageId=(int)db()->lastInsertId();db()->prepare('UPDATE conversations SET last_message_at=NOW() WHERE id=?')->execute([$cid]);zynkoRealtimePublishMessage(db(),$tid,$messageId,['channel'=>$ch['type'],'sender'=>'system']);$dispatch=[true,'Canal interno'];if(!in_array((string)$ch['type'],['webchat','email'],true))$dispatch=(new ChannelProviderGateway(db(),$root))->dispatch($ch,$to,$text,[],$messageId);$resp=['ok'=>$dispatch[0],'message'=>$dispatch[0]?'Mensaje aceptado y despachado por el canal.':'El proveedor rechazó el despacho.','data'=>['message_uuid'=>$uuid,'conversation_id'=>$cid,'status'=>$dispatch[0]?'sent':'failed','provider_status'=>$dispatch[0]?'sent':'failed','provider_message'=>$dispatch[1]]];$json=json_encode($resp,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($idem!=='')db()->prepare('INSERT INTO api_idempotency(tenant_id,idempotency_key,response_json,http_status,created_at) VALUES(?,?,?,?,NOW())')->execute([$tid,$idem,$json,202]);logReq($tid,(int)$key['id'],'v1/messages/send',$idem,202,$j);http_response_code(202);echo $json;exit;
 }
 if($method==='POST'&&$path==='v1/messages/receive'){
  hasAnyScope($key,['messages:receive','messages:send']);if(!planAllows($tid,'api'))out(403,false,'El plan de esta empresa no incluye acceso API.');$j=body();$idem=trim($_SERVER['HTTP_IDEMPOTENCY_KEY']??'');if($idem!==''){$q=db()->prepare('SELECT response_json,http_status FROM api_idempotency WHERE tenant_id=? AND idempotency_key=?');$q->execute([$tid,$idem]);if($old=$q->fetch()){http_response_code((int)$old['http_status']);echo $old['response_json'];exit;}}$channel=(int)($j['channel_id']??0);$from=trim((string)($j['from']??''));$name=trim((string)($j['contact_name']??$from));$text=trim((string)($j['message']??''));if($channel<1||$from===''||$text==='')out(422,false,'Requiere channel_id, from y message.');$q=db()->prepare('SELECT * FROM channels WHERE id=? AND tenant_id=?');$q->execute([$channel,$tid]);$ch=$q->fetch();if(!$ch)out(404,false,'Canal no encontrado.');if($ch['status']!=='connected')out(409,false,'El canal todavía no está conectado/autorizado.');
  $q=db()->prepare('SELECT contact_id FROM contact_identities WHERE tenant_id=? AND channel_id=? AND external_id=? LIMIT 1');$q->execute([$tid,$channel,$from]);$contact=(int)($q->fetchColumn()?:0);if(!$contact&&$ch['type']==='whatsapp'){$q=db()->prepare('SELECT id FROM contacts WHERE tenant_id=? AND phone=? LIMIT 1');$q->execute([$tid,$from]);$contact=(int)($q->fetchColumn()?:0);}if(!$contact){db()->prepare('INSERT INTO contacts(tenant_id,uuid,name,phone,email) VALUES(?,?,?,?,?)')->execute([$tid,uuid4(),$name,$ch['type']==='whatsapp'?$from:null,$ch['type']==='email'?$from:null]);$contact=(int)db()->lastInsertId();}db()->prepare('INSERT INTO contact_identities(tenant_id,contact_id,channel_id,external_id,profile_json) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE contact_id=VALUES(contact_id),profile_json=VALUES(profile_json)')->execute([$tid,$contact,$channel,$from,json_encode(['name'=>$name],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
  $q=db()->prepare("SELECT id FROM conversations WHERE tenant_id=? AND channel_id=? AND contact_id=? AND status IN ('open','pending') AND archived_at IS NULL AND deleted_at IS NULL ORDER BY id DESC LIMIT 1");$q->execute([$tid,$channel,$contact]);$cid=(int)($q->fetchColumn()?:0);if(!$cid){enforceMonthlyChatLimit($tid);db()->prepare("INSERT INTO conversations(tenant_id,uuid,channel_id,contact_id,status,last_message_at) VALUES(?,?,?,?,'open',NOW())")->execute([$tid,uuid4(),$channel,$contact]);$cid=(int)db()->lastInsertId();zynkoRealtimePublish(db(),$tid,'conversation.created',['conversation_id'=>$cid,'channel'=>$ch['type'],'contact_name'=>$name],'conversation',(string)$cid);}
  db()->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,'in','contact','text',?,'received',NOW())")->execute([$tid,$cid,uuid4(),$text]);$inboundMessageId=(int)db()->lastInsertId();db()->prepare("UPDATE conversations SET unread_count=unread_count+1,last_message_at=NOW(),status=IF(assigned_user_id IS NULL,'open',status),archived_at=NULL WHERE id=? AND tenant_id=?")->execute([$cid,$tid]);zynkoRealtimePublishMessage(db(),$tid,$inboundMessageId,['channel'=>$ch['type'],'sender'=>'contact']);zynkoRealtimePublish(db(),$tid,'conversation.updated',['conversation_id'=>$cid,'channel'=>$ch['type'],'reason'=>'inbound_message','message_id'=>$inboundMessageId],'conversation',(string)$cid);
  $ownership=db()->prepare('SELECT status,assigned_user_id FROM conversations WHERE id=? AND tenant_id=? LIMIT 1');$ownership->execute([$cid,$tid]);$ownerState=$ownership->fetch()?:[];$assignedUserId=(int)($ownerState['assigned_user_id']??0);
  $company=(string)(db()->query('SELECT name FROM tenants WHERE id='.(int)$tid)->fetchColumn()?:'la empresa');
  if($assignedUserId>0){$engine=['reply'=>null,'handoff'=>true,'source'=>'handoff:assigned','sources'=>[],'reason'=>'human_assigned'];}
  else{$automation=AutomationEngine::evaluate(db(),$tid,$cid,(string)$ch['type'],$text);$engine=($automation&&(!empty($automation['stop'])||!empty($automation['reply'])))?$automation:NivoEngine::evaluate(db(),$tid,$cid,$text,(string)$ch['type'],$name,$company);}
  $reply=$engine['reply']??null;$replyDelivery=null;if(!empty($engine['handoff'])&&$assignedUserId===0)db()->prepare("UPDATE conversations SET status='pending' WHERE id=? AND tenant_id=?")->execute([$cid,$tid]);
  if($reply&&$assignedUserId===0){db()->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,'out','bot','text',?,'queued',NOW())")->execute([$tid,$cid,uuid4(),$reply]);$replyMessageId=(int)db()->lastInsertId();$replyDelivery=(new ChannelProviderGateway(db(),$root))->dispatch($ch,$from,$reply,[],$replyMessageId);db()->prepare("UPDATE messages SET status=? WHERE id=? AND tenant_id=?")->execute([$replyDelivery[0]?'sent':'failed',$replyMessageId,$tid]);db()->prepare('UPDATE conversations SET last_message_at=NOW() WHERE id=? AND tenant_id=?')->execute([$cid,$tid]);zynkoRealtimePublishMessage(db(),$tid,$replyMessageId,['channel'=>$ch['type'],'sender'=>'bot']);zynkoRealtimePublish(db(),$tid,'conversation.updated',['conversation_id'=>$cid,'channel'=>$ch['type'],'reason'=>'bot_reply','message_id'=>$replyMessageId],'conversation',(string)$cid);}
  $resp=['ok'=>true,'message'=>'Mensaje recibido por ZYNKO.','data'=>['conversation_id'=>$cid,'channel'=>$ch['type'],'nivo'=>['reply'=>$reply,'handoff'=>(bool)($engine['handoff']??false),'source'=>$engine['source']??null,'sources'=>$engine['sources']??[],'reason'=>$engine['reason']??null],'delivery_note'=>$reply?($replyDelivery&&$replyDelivery[0]?'La respuesta de NIVO fue despachada por el canal conectado.':'La respuesta quedó registrada, pero el proveedor reportó un fallo de entrega.'):($assignedUserId>0?'La conversación está bajo atención humana; NIVO no respondió automáticamente.':null)]];$json=json_encode($resp,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($idem!=='')db()->prepare('INSERT INTO api_idempotency(tenant_id,idempotency_key,response_json,http_status,created_at) VALUES(?,?,?,?,NOW())')->execute([$tid,$idem,$json,200]);logReq($tid,(int)$key['id'],'v1/messages/receive',$idem,200,$j);http_response_code(200);echo $json;exit;
 }
 if($method==='POST'&&$path==='v1/nivo/context'){
  hasScope($key,'nivo:context');
  try{$svc=new OpenAIProviderService(db(),dirname(__DIR__));$aiPolicy=$svc->tenantSettings($tid);$origins=$aiPolicy['allowed_origins']??[];$origin=trim((string)($_SERVER['HTTP_ORIGIN']??''));if($origin!==''&&$origins&&!in_array(rtrim(strtolower($origin),'/'),array_map(static fn($v)=>rtrim(strtolower((string)$v),'/'),$origins),true))out(403,false,'Este origen no está autorizado para utilizar NIVO IA.');}catch(Throwable $ignore){}
  $j=body();$query=trim((string)($j['query']??''));if($query==='')out(422,false,'Requiere query.');$words=array_values(array_filter(preg_split('/\W+/u',mb_strtolower($query)),fn($x)=>mb_strlen($x)>=4));$q=db()->prepare("SELECT id,name,content FROM knowledge_sources WHERE tenant_id=? AND status='ready' AND approval_status='approved' ORDER BY updated_at DESC LIMIT 100");$q->execute([$tid]);$hits=[];foreach($q->fetchAll() as $r){$hay=mb_strtolower(($r['name']??'').' '.($r['content']??''));$score=0;foreach($words as $w)if(str_contains($hay,$w))$score++;if($score)$hits[]=['id'=>$r['id'],'name'=>$r['name'],'content'=>mb_substr((string)$r['content'],0,2500),'score'=>$score];}usort($hits,fn($a,$b)=>$b['score']<=>$a['score']);out(200,true,'Contexto autorizado recuperado.',['query'=>$query,'sources'=>array_slice($hits,0,5),'note'=>'Este endpoint recupera conocimiento. La generación con IA se activa al configurar un proveedor/modelo en NIVO.']);
 }
 out(404,false,'Endpoint no encontrado.');
}catch(Throwable $e){out(500,false,'Error interno de ZYNKO API.',['reference'=>substr(hash('sha256',$e->getMessage().microtime()),0,12)]);}
