<?php
declare(strict_types=1);
$root=dirname(__DIR__);
header('Content-Type: application/json; charset=utf-8');
function out(int $status,bool $ok,string $message,array $data=[]): never { http_response_code($status); echo json_encode(['ok'=>$ok,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function envCfg(string $p): array { $v=@parse_ini_file($p,false,INI_SCANNER_RAW); return is_array($v)?$v:[]; }
function db(): PDO { static $pdo; global $root; if($pdo)return $pdo;$e=envCfg($root.'/.env');$dsn='mysql:host='.($e['DB_HOST']??'127.0.0.1').';port='.($e['DB_PORT']??'3306').';dbname='.($e['DB_DATABASE']??'zynko').';charset=utf8mb4';return $pdo=new PDO($dsn,$e['DB_USERNAME']??'root',$e['DB_PASSWORD']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
function uuid4(): string {$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
function bearer(): string { $h=$_SERVER['HTTP_AUTHORIZATION']??''; if(!preg_match('/^Bearer\s+(.+)$/i',$h,$m))out(401,false,'Falta Authorization: Bearer <API_KEY>.'); return trim($m[1]); }
function auth(): array { $key=bearer();$prefix=explode('.',$key,2)[0]??'';if(!str_starts_with($prefix,'zk_'))out(401,false,'Clave API inválida.');$q=db()->prepare('SELECT * FROM api_keys WHERE key_prefix=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>NOW())');$q->execute([$prefix]);$r=$q->fetch();if(!$r||!hash_equals($r['key_hash'],hash('sha256',$key)))out(401,false,'Clave API inválida o revocada.');db()->prepare('UPDATE api_keys SET last_used_at=NOW() WHERE id=?')->execute([$r['id']]);return $r; }
function hasScope(array $k,string $scope): void {$s=json_decode($k['scopes_json']??'[]',true)?:[];if(!in_array($scope,$s,true))out(403,false,'La clave no tiene el permiso '.$scope.'.');}
function body(): array {$raw=file_get_contents('php://input')?:'';$j=json_decode($raw,true);if(!is_array($j))out(400,false,'JSON inválido.');return $j;}
function planAllows(int $tid,string $feature): bool {try{$q=db()->prepare('SELECT sp.features_json FROM tenant_subscriptions ts JOIN subscription_plans sp ON sp.id=ts.plan_id WHERE ts.tenant_id=? AND ts.status IN ("active","grace")');$q->execute([$tid]);$f=json_decode($q->fetchColumn()?:'[]',true)?:[];if(!$f)return true;foreach($f as $k=>$v){if(is_string($k)&&$k===$feature)return (bool)$v;if(is_string($v)&&$v===$feature)return true;}return false;}catch(Throwable $e){return true;}}
function logReq(int $tid,int $keyId,string $endpoint,string $idem,int $status,array $payload): void {try{db()->prepare('INSERT INTO api_request_logs(tenant_id,api_key_id,endpoint,idempotency_key,http_status,payload_hash,created_at) VALUES(?,?,?,?,?,?,NOW())')->execute([$tid,$keyId,$endpoint,$idem?:null,$status,hash('sha256',json_encode($payload))]);}catch(Throwable $e){}}
try{
 $key=auth();$tid=(int)$key['tenant_id'];$method=$_SERVER['REQUEST_METHOD']??'GET';$path=trim($_GET['r']??($_SERVER['PATH_INFO']??''),'/');
 if($method==='GET'&&($path===''||$path==='v1/health'))out(200,true,'ZYNKO API disponible.',['version'=>'v1','tenant_id'=>$tid]);
 if($method==='POST'&&$path==='v1/messages/send'){
  hasScope($key,'messages:send');if(!planAllows($tid,'api'))out(403,false,'El plan de esta empresa no incluye acceso API.');$j=body();$idem=trim($_SERVER['HTTP_IDEMPOTENCY_KEY']??'');if($idem!==''){$q=db()->prepare('SELECT response_json,http_status FROM api_idempotency WHERE tenant_id=? AND idempotency_key=?');$q->execute([$tid,$idem]);if($old=$q->fetch()){http_response_code((int)$old['http_status']);echo $old['response_json'];exit;}}
  $channel=(int)($j['channel_id']??0);$to=trim((string)($j['to']??''));$name=trim((string)($j['contact_name']??$to));$text=trim((string)($j['message']??''));if($channel<1||$to===''||$text==='')out(422,false,'Requiere channel_id, to y message.');$q=db()->prepare('SELECT id,type,status FROM channels WHERE id=? AND tenant_id=?');$q->execute([$channel,$tid]);$ch=$q->fetch();if(!$ch)out(404,false,'Canal no encontrado.');if($ch['status']!=='connected')out(409,false,'El canal existe pero aún no está conectado/autorizado con el proveedor.');
  $field=$ch['type']==='whatsapp'?'phone':'email';$q=db()->prepare("SELECT id FROM contacts WHERE tenant_id=? AND $field=? LIMIT 1");$q->execute([$tid,$to]);$contact=(int)($q->fetchColumn()?:0);if(!$contact){db()->prepare('INSERT INTO contacts(tenant_id,uuid,name,phone,email) VALUES(?,?,?,?,?)')->execute([$tid,uuid4(),$name,$ch['type']==='whatsapp'?$to:null,$ch['type']==='messenger'?$to:null]);$contact=(int)db()->lastInsertId();}
  $q=db()->prepare("SELECT id FROM conversations WHERE tenant_id=? AND channel_id=? AND contact_id=? AND status IN ('open','pending') ORDER BY id DESC LIMIT 1");$q->execute([$tid,$channel,$contact]);$cid=(int)($q->fetchColumn()?:0);if(!$cid){db()->prepare("INSERT INTO conversations(tenant_id,uuid,channel_id,contact_id,status,last_message_at) VALUES(?,?,?,?,'open',NOW())")->execute([$tid,uuid4(),$channel,$contact]);$cid=(int)db()->lastInsertId();}
  $uuid=uuid4();db()->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,'out','system','text',?,'queued',NOW())")->execute([$tid,$cid,$uuid,$text]);db()->prepare('UPDATE conversations SET last_message_at=NOW() WHERE id=?')->execute([$cid]);$resp=['ok'=>true,'message'=>'Mensaje aceptado por ZYNKO y puesto en cola.','data'=>['message_uuid'=>$uuid,'conversation_id'=>$cid,'status'=>'queued','provider_status'=>'pending_dispatch']];$json=json_encode($resp,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($idem!=='')db()->prepare('INSERT INTO api_idempotency(tenant_id,idempotency_key,response_json,http_status,created_at) VALUES(?,?,?,?,NOW())')->execute([$tid,$idem,$json,202]);logReq($tid,(int)$key['id'],'v1/messages/send',$idem,202,$j);http_response_code(202);echo $json;exit;
 }
 if($method==='POST'&&$path==='v1/nivo/context'){
  hasScope($key,'nivo:context');$j=body();$query=trim((string)($j['query']??''));if($query==='')out(422,false,'Requiere query.');$words=array_values(array_filter(preg_split('/\W+/u',mb_strtolower($query)),fn($x)=>mb_strlen($x)>=4));$q=db()->prepare("SELECT id,name,content FROM knowledge_sources WHERE tenant_id=? AND status='ready' ORDER BY updated_at DESC LIMIT 100");$q->execute([$tid]);$hits=[];foreach($q->fetchAll() as $r){$hay=mb_strtolower(($r['name']??'').' '.($r['content']??''));$score=0;foreach($words as $w)if(str_contains($hay,$w))$score++;if($score)$hits[]=['id'=>$r['id'],'name'=>$r['name'],'content'=>mb_substr((string)$r['content'],0,2500),'score'=>$score];}usort($hits,fn($a,$b)=>$b['score']<=>$a['score']);out(200,true,'Contexto autorizado recuperado.',['query'=>$query,'sources'=>array_slice($hits,0,5),'note'=>'Este endpoint recupera conocimiento. La generación con IA se activa al configurar un proveedor/modelo en NIVO.']);
 }
 out(404,false,'Endpoint no encontrado.');
}catch(Throwable $e){out(500,false,'Error interno de ZYNKO API.',['reference'=>substr(hash('sha256',$e->getMessage().microtime()),0,12)]);}
