<?php
session_start();
$root=dirname(__DIR__); $envFile=$root.'/.env'; $lock=$root.'/storage/installed.lock';
if (is_file($lock)) { header('Location: ./'); exit; }
if (!is_dir($root.'/storage')) @mkdir($root.'/storage',0775,true);
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function uuidv4(){ $d=random_bytes(16); $d[6]=chr((ord($d[6])&0x0f)|0x40); $d[8]=chr((ord($d[8])&0x3f)|0x80); return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4)); }
function writeEnv($path,$data){$out=''; foreach($data as $k=>$v){$v=str_replace(["\r","\n"],'',(string)$v); $out.=$k.'="'.addcslashes($v,"\\\"")."\"\n";} return file_put_contents($path,$out,LOCK_EX)!==false;}
$step=max(1,min(4,(int)($_GET['step']??1))); $error='';
$defaults=['host'=>'127.0.0.1','port'=>'3306','database'=>'zynko','username'=>'root','password'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=$_POST['action']??'';
  if($action==='database'){
    foreach($defaults as $k=>$v) $_SESSION['install_db'][$k]=trim((string)($_POST[$k]??$v));
    try{$d=$_SESSION['install_db'];$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$safe=preg_replace('/[^a-zA-Z0-9_]/','',$d['database']);if(!$safe)throw new Exception('Nombre de base de datos inválido.');$pdo->exec("CREATE DATABASE IF NOT EXISTS `$safe` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$_SESSION['install_db']['database']=$safe;header('Location: ?step=2');exit;}catch(Throwable $e){$error='No se pudo conectar: '.$e->getMessage();}
  }
  if($action==='install'){
    try{$d=$_SESSION['install_db']??null;if(!$d)throw new Exception('Primero configura la base de datos.');$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};dbname={$d['database']};charset=utf8mb4",$d['username'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$sql=file_get_contents($root.'/database/schema.sql');$sql=preg_replace('/CREATE DATABASE IF NOT EXISTS[^;]+;/i','',$sql);$sql=preg_replace('/USE\s+[^;]+;/i','',$sql);$pdo->exec($sql);$email=trim($_POST['email']??'');$name=trim($_POST['name']??'Administrador');$company=trim($_POST['company']??'Mi empresa');$pass=$_POST['password']??'';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pass)<8)throw new Exception('Usa un correo válido y una contraseña de al menos 8 caracteres.');$pdo->beginTransaction();$st=$pdo->prepare('INSERT INTO tenants(uuid,name,slug,status,locale,bot_name) VALUES(?,?,?,?,?,?)');$slug=strtolower(trim(preg_replace('/[^a-zA-Z0-9]+/','-',$company),'-')).'-'.substr(bin2hex(random_bytes(3)),0,6);$st->execute([uuidv4(),$company,$slug,'active',$_POST['locale']==='en'?'en':'es','NIVO']);$tid=(int)$pdo->lastInsertId();$st=$pdo->prepare('INSERT INTO users(uuid,name,email,password_hash,locale,status) VALUES(?,?,?,?,?,?)');$st->execute([uuidv4(),$name,$email,password_hash($pass,PASSWORD_DEFAULT),$_POST['locale']==='en'?'en':'es','active']);$uid=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO tenant_users(tenant_id,user_id,role_code,is_owner) VALUES(?,?, 'owner',1)")->execute([$tid,$uid]);$pdo->prepare("INSERT INTO bot_profiles(tenant_id,name,enabled,mode) VALUES(?,'NIVO',0,'hybrid')")->execute([$tid]);$pdo->prepare("INSERT INTO branding_settings(tenant_id,app_title,primary_color,secondary_color) VALUES(?,'ZYNKO','#13a88a','#0b1625')")->execute([$tid]);$pdo->commit();$key=bin2hex(random_bytes(32));writeEnv($envFile,['APP_ENV'=>'production','APP_URL'=>($_POST['app_url']??''),'APP_KEY'=>$key,'DB_HOST'=>$d['host'],'DB_PORT'=>$d['port'],'DB_DATABASE'=>$d['database'],'DB_USERNAME'=>$d['username'],'DB_PASSWORD'=>$d['password'],'META_APP_ID'=>'','META_APP_SECRET'=>'','META_VERIFY_TOKEN'=>'','META_GRAPH_VERSION'=>'','WS_HOST'=>'127.0.0.1','WS_PORT'=>'8080']);file_put_contents($lock,date(DATE_ATOM));$_SESSION['install_done']=true;header('Location: ?step=4');exit;}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$error='Instalación detenida: '.$e->getMessage();$step=3;}
  }
}
$db=array_merge($defaults,$_SESSION['install_db']??[]);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instalar ZYNKO</title><style>:root{--p:#13a88a;--n:#0b1625;--bg:#f5f7fb;--line:#e4eaf0;--muted:#6f7f91}*{box-sizing:border-box}body{margin:0;font:14px/1.5 Inter,system-ui,sans-serif;background:var(--bg);color:#152235}.wrap{width:min(900px,calc(100% - 28px));margin:5vh auto}.brand{display:flex;align-items:center;gap:12px;margin-bottom:22px}.mark{width:42px;height:42px;border-radius:13px;background:var(--p);color:#fff;display:grid;place-items:center;font-weight:900}.card{background:#fff;border:1px solid var(--line);border-radius:20px;padding:28px;box-shadow:0 20px 55px rgba(20,40,60,.08)}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:24px}.steps div{padding:11px;border:1px solid var(--line);border-radius:11px;color:var(--muted)}.steps .on{border-color:var(--p);color:#08705c;background:#f0fbf8}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:grid;gap:7px}.field label{font-weight:700}.field input,.field select{width:100%;min-height:44px;border:1px solid var(--line);border-radius:11px;padding:10px 12px;font:inherit}.full{grid-column:1/-1}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.btn{border:0;border-radius:11px;padding:11px 16px;font-weight:700;cursor:pointer}.primary{background:var(--p);color:#fff}.error{padding:12px;border:1px solid #f0c5c5;background:#fff6f6;border-radius:10px;margin-bottom:16px}.note{padding:14px;background:#f8fafc;border:1px solid var(--line);border-radius:12px;color:var(--muted)}h1{margin:0 0 7px}p{color:var(--muted)}@media(max-width:680px){.grid,.steps{grid-template-columns:1fr}.card{padding:20px}.steps div{display:none}.steps .on{display:block}.full{grid-column:auto}}</style></head><body><div class="wrap"><div class="brand"><div class="mark">Z</div><div><b>ZYNKO</b><div style="color:#6f7f91">Asistente de instalación</div></div></div><section class="card"><div class="steps"><?php foreach(['Bienvenida','Base de datos','Administrador','Finalizar'] as $i=>$s):?><div class="<?=$step===$i+1?'on':''?>"><?=($i+1).'. '.h($s)?></div><?php endforeach?></div><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if($step===1):?><h1>Instalemos ZYNKO</h1><p>El asistente preparará la base de datos, creará todas las tablas y configurará la primera empresa y su administrador. No necesitas importar SQL manualmente.</p><div class="note">Antes de continuar necesitas un servidor con PHP 8.1+, PDO MySQL y permisos para crear/escribir el archivo <b>.env</b> y la carpeta <b>storage</b>.</div><div class="actions"><a class="btn primary" href="?step=2" style="text-decoration:none">Comenzar instalación →</a></div>
<?php elseif($step===2):?><h1>Conexión a MySQL</h1><p>Escribe los datos de tu servidor. ZYNKO probará la conexión y creará la base si todavía no existe.</p><form method="post"><input type="hidden" name="action" value="database"><div class="grid"><div class="field"><label>Servidor / Host</label><input name="host" value="<?=h($db['host'])?>" required></div><div class="field"><label>Puerto</label><input name="port" value="<?=h($db['port'])?>" required></div><div class="field"><label>Base de datos</label><input name="database" value="<?=h($db['database'])?>" required></div><div class="field"><label>Usuario MySQL</label><input name="username" value="<?=h($db['username'])?>" required></div><div class="field full"><label>Contraseña MySQL</label><input type="password" name="password" value="<?=h($db['password'])?>"></div></div><div class="actions"><button class="btn primary">Probar y continuar →</button></div></form>
<?php elseif($step===3):?><h1>Cuenta principal</h1><p>Esta será la primera empresa y el propietario de ZYNKO. NIVO quedará creado y listo para configurarse después.</p><form method="post"><input type="hidden" name="action" value="install"><div class="grid"><div class="field"><label>Empresa</label><input name="company" required placeholder="Nombre de la empresa"></div><div class="field"><label>Nombre del administrador</label><input name="name" required></div><div class="field"><label>Correo</label><input type="email" name="email" required></div><div class="field"><label>Contraseña</label><input type="password" name="password" minlength="8" required></div><div class="field"><label>Idioma inicial</label><select name="locale"><option value="es">Español</option><option value="en">English</option></select></div><div class="field"><label>URL de ZYNKO</label><input name="app_url" placeholder="https://zynko.tudominio.com"></div></div><div class="actions"><button class="btn primary">Crear tablas e instalar ZYNKO</button></div></form>
<?php else:?><h1>✓ ZYNKO está instalado</h1><p>La base de datos, tablas, empresa principal, administrador, branding inicial y perfil de NIVO fueron creados automáticamente.</p><div class="note">Por seguridad, el instalador queda bloqueado mediante <b>storage/installed.lock</b>. Continúa al inicio de sesión y configura Meta, canales, branding e IA desde el panel.</div><div class="actions"><a class="btn primary" href="./" style="text-decoration:none">Ir a ZYNKO →</a></div><?php endif?></section></div></body></html>
