<?php
declare(strict_types=1);
$root=dirname(__DIR__);
require_once $root.'/app/Support/Realtime.php';
require_once $root.'/app/Services/NivoEngine.php';
require_once $root.'/app/Services/AutomationEngine.php';
require_once $root.'/app/Services/ChannelProviderGateway.php';
function envv(string $p):array{$v=@parse_ini_file($p,false,INI_SCANNER_RAW);return is_array($v)?$v:[];}
function dbh():PDO{static $p;if($p)return $p;global $root;$e=envv($root.'/.env');$p=new PDO('mysql:host='.($e['DB_HOST']??'127.0.0.1').';port='.($e['DB_PORT']??'3306').';dbname='.($e['DB_DATABASE']??'zynko').';charset=utf8mb4',$e['DB_USERNAME']??'root',$e['DB_PASSWORD']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);return $p;}
function decryptw(string $cipher):string{global $root;if($cipher===''||!str_starts_with($cipher,'enc:v1:'))return $cipher;$e=envv($root.'/.env');$hex=$e['APP_KEY']??'';if(!preg_match('/^[a-f0-9]{64}$/i',$hex))return '';$raw=base64_decode(substr($cipher,7),true);if($raw===false||strlen($raw)<29)return '';$plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',hex2bin($hex),OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16));return is_string($plain)?$plain:'';}
function uuid4w():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
function outw(int $code,array $data):never{http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
$uuid=preg_replace('/[^a-f0-9-]/i','',(string)($_GET['channel']??''));if($uuid==='')outw(404,['ok'=>false]);$q=dbh()->prepare('SELECT * FROM channels WHERE uuid=? LIMIT 1');$q->execute([$uuid]);$channel=$q->fetch();if(!$channel)outw(404,['ok'=>false]);$settings=json_decode((string)($channel['settings_json']??''),true)?:[];
if($_SERVER['REQUEST_METHOD']==='GET'){$verify=(string)($_GET['hub_verify_token']??'');if($verify!==''&&hash_equals((string)($settings['verify_token']??''),$verify)){header('Content-Type:text/plain');echo (string)($_GET['hub_challenge']??'');exit;}outw(403,['ok'=>false,'message'=>'Verify token inválido']);}
$raw=file_get_contents('php://input')?:'';$payload=json_decode($raw,true);if(!is_array($payload))outw(400,['ok'=>false,'message'=>'JSON inválido']);
$type=(string)$channel['type'];$events=[];
if($type==='telegram'){$m=$payload['message']??$payload['edited_message']??null;if(is_array($m))$events[]=['kind'=>'message','from'=>(string)($m['chat']['id']??''),'name'=>(string)($m['from']['first_name']??''),'text'=>(string)($m['text']??''),'external'=>(string)($m['message_id']??'')];}
elseif($type==='whatsapp'&&($settings['provider_mode']??'')==='qr_bridge'){$token=(string)($_SERVER['HTTP_X_ZYNKO_QR_TOKEN']??'');$expected=decryptw((string)($channel['token_ciphertext']??''));if($expected!==''&&!hash_equals($expected,$token))outw(403,['ok'=>false]);if(($payload['event']??'')==='message')$events[]=['kind'=>'message','from'=>preg_replace('/@.*/','',(string)($payload['from']??'')),'name'=>(string)($payload['push_name']??''),'text'=>(string)($payload['text']??''),'external'=>(string)($payload['message_id']??'')];}
else{
 foreach(($payload['entry']??[]) as $entry){foreach(($entry['messaging']??[]) as $m){if(!empty($m['message']['text']))$events[]=['kind'=>'message','from'=>(string)($m['sender']['id']??''),'name'=>'','text'=>(string)$m['message']['text'],'external'=>(string)($m['message']['mid']??'')];}
 foreach(($entry['changes']??[]) as $c){$v=$c['value']??[];if(($c['field']??'')==='messages'){foreach(($v['messages']??[]) as $m){$events[]=['kind'=>'message','from'=>(string)($m['from']??''),'name'=>(string)($v['contacts'][0]['profile']['name']??''),'text'=>(string)($m['text']['body']??''),'external'=>(string)($m['id']??'')];}}elseif(in_array((string)($c['field']??''),['comments','feed'],true)){ $from=(string)($v['from']['id']??$v['sender_id']??'');$text=(string)($v['message']??$v['text']??'');if($from!==''&&$text!=='')$events[]=['kind'=>'comment','from'=>$from,'name'=>(string)($v['from']['username']??$v['from']['name']??''),'text'=>$text,'external'=>(string)($v['id']??'')];}}
 }}
$pdo=dbh();$gateway=new ChannelProviderGateway($pdo,$root);foreach($events as $ev){$from=trim($ev['from']);$text=trim($ev['text']);if($from===''||$text==='')continue;$tid=(int)$channel['tenant_id'];
 if($ev['kind']==='comment'&&$type==='instagram'){$r=$pdo->prepare("SELECT * FROM social_automation_rules WHERE tenant_id=? AND channel_type='instagram' AND rule_type='comment_to_dm' AND active=1 ORDER BY id");$r->execute([$tid]);foreach($r->fetchAll() as $rule){$keys=preg_split('/[,\n]+/u',mb_strtolower((string)$rule['keywords']))?:[];$match=trim((string)$rule['keywords'])==='';foreach($keys as $k){$k=trim($k);if($k!==''&&mb_strpos(mb_strtolower($text),$k)!==false)$match=true;}if($match){$gateway->dispatch($channel,$from,(string)$rule['response_text']);break;}}continue;}
 $cq=$pdo->prepare('SELECT contact_id FROM contact_identities WHERE tenant_id=? AND channel_id=? AND external_id=? LIMIT 1');$cq->execute([$tid,(int)$channel['id'],$from]);$contact=(int)($cq->fetchColumn()?:0);if(!$contact){$pdo->prepare('INSERT INTO contacts(tenant_id,uuid,name,phone) VALUES(?,?,?,?)')->execute([$tid,uuid4w(),$ev['name']?:$from,$type==='whatsapp'?$from:null]);$contact=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO contact_identities(tenant_id,contact_id,channel_id,external_id,profile_json) VALUES(?,?,?,?,JSON_OBJECT())')->execute([$tid,$contact,(int)$channel['id'],$from]);}
 $cq=$pdo->prepare("SELECT id FROM conversations WHERE tenant_id=? AND channel_id=? AND contact_id=? AND status IN('open','pending') ORDER BY id DESC LIMIT 1");$cq->execute([$tid,(int)$channel['id'],$contact]);$cid=(int)($cq->fetchColumn()?:0);if(!$cid){$pdo->prepare("INSERT INTO conversations(tenant_id,uuid,channel_id,contact_id,status,last_message_at) VALUES(?,?,?,?,'open',NOW())")->execute([$tid,uuid4w(),(int)$channel['id'],$contact]);$cid=(int)$pdo->lastInsertId();}
 try{$pdo->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,external_message_id,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,?, 'in','contact','text',?,'received',NOW())")->execute([$tid,$cid,uuid4w(),$ev['external']?:null,$text]);}catch(PDOException $dup){continue;}$mid=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE conversations SET last_message_at=NOW(),unread_count=unread_count+1 WHERE id=?')->execute([$cid]);zynkoRealtimePublishMessage($pdo,$tid,$mid,['channel'=>$type,'sender'=>'contact']);
 $company=(string)($pdo->query('SELECT name FROM tenants WHERE id='.$tid)->fetchColumn()?:'la empresa');$auto=AutomationEngine::evaluate($pdo,$tid,$cid,$type,$text);$engine=($auto&&(!empty($auto['stop'])||!empty($auto['reply'])))?$auto:NivoEngine::evaluate($pdo,$tid,$cid,$text,$type,$ev['name']?:$from,$company);$reply=trim((string)($engine['reply']??''));if($reply!==''){$pdo->prepare("INSERT INTO messages(tenant_id,conversation_id,uuid,direction,sender_type,type,body,status,sent_at) VALUES(?,?,?,'out','bot','text',?,'queued',NOW())")->execute([$tid,$cid,uuid4w(),$reply]);$outId=(int)$pdo->lastInsertId();$gateway->dispatch($channel,$from,$reply,[],$outId);zynkoRealtimePublishMessage($pdo,$tid,$outId,['channel'=>$type,'sender'=>'bot']);}
}
$pdo->prepare('UPDATE channels SET last_event_at=NOW() WHERE id=?')->execute([(int)$channel['id']]);outw(200,['ok'=>true,'processed'=>count($events)]);
