<?php
declare(strict_types=1);
$root=dirname(__DIR__);$env=@parse_ini_file($root.'/.env',false,INI_SCANNER_RAW)?:[];$pdo=new PDO('mysql:host='.($env['DB_HOST']??'127.0.0.1').';port='.($env['DB_PORT']??'3306').';dbname='.($env['DB_DATABASE']??'zynko').';charset=utf8mb4',$env['DB_USERNAME']??'root',$env['DB_PASSWORD']??'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
function callOut(int $c,array $d):never{http_response_code($c);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
$uuid=preg_replace('/[^a-f0-9-]/i','',(string)($_GET['channel']??''));$q=$pdo->prepare("SELECT * FROM channels WHERE uuid=? AND type='whatsapp' LIMIT 1");$q->execute([$uuid]);$channel=$q->fetch();if(!$channel)callOut(404,['ok'=>false,'message'=>'Canal no encontrado']);$settings=json_decode((string)($channel['settings_json']??''),true)?:[];
if($_SERVER['REQUEST_METHOD']==='GET'){if(hash_equals((string)($settings['verify_token']??''),(string)($_GET['hub_verify_token']??''))){header('Content-Type:text/plain');echo (string)($_GET['hub_challenge']??'');exit;}callOut(403,['ok'=>false]);}
$j=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$event=(string)($j['event']??$j['type']??'call.event');$external=(string)($j['call_id']??$j['id']??'');$from=(string)($j['from']??$j['caller']??'');$status=(string)($j['status']??'ringing');if(!in_array($status,['ringing','answered','completed','failed','rejected'],true))$status='ringing';
$tid=(int)$channel['tenant_id'];$q=$pdo->prepare('SELECT * FROM whatsapp_ai_call_profiles WHERE tenant_id=? AND (channel_id=? OR channel_id IS NULL) AND enabled=1 ORDER BY channel_id DESC,id DESC LIMIT 1');$q->execute([$tid,(int)$channel['id']]);$profile=$q->fetch();if(!$profile)callOut(409,['ok'=>false,'message'=>'No hay perfil de NIVO IA activo para llamadas.']);
$pdo->prepare("INSERT INTO whatsapp_ai_calls(tenant_id,profile_id,channel_id,external_call_id,caller,status,event_json,started_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE status=VALUES(status),event_json=VALUES(event_json),updated_at=NOW(),answered_at=IF(VALUES(status)='answered' AND answered_at IS NULL,NOW(),answered_at),ended_at=IF(VALUES(status) IN('completed','failed','rejected'),NOW(),ended_at)")->execute([$tid,(int)$profile['id'],(int)$channel['id'],$external?:null,$from?:null,$status,json_encode($j,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
callOut(200,['ok'=>true,'event'=>$event,'call_id'=>$external,'nivo'=>['profile_id'=>(int)$profile['id'],'voice'=>$profile['voice_name']??null,'system_prompt'=>$profile['system_prompt']??'','handoff_enabled'=>(bool)$profile['handoff_enabled']],'note'=>'El proveedor de llamadas debe usar esta política para la sesión de voz y reportar sus eventos a este webhook.']);
