CREATE DATABASE IF NOT EXISTS zynko CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE zynko;

CREATE TABLE tenants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, status ENUM('trial','active','past_due','suspended','closed') NOT NULL DEFAULT 'trial', plan_id BIGINT UNSIGNED NULL, logo_path VARCHAR(255), logo_dark_path VARCHAR(255), favicon_path VARCHAR(255), primary_color VARCHAR(20) DEFAULT '#0F766E', secondary_color VARCHAR(20) DEFAULT '#0F172A', timezone VARCHAR(64) NOT NULL DEFAULT 'America/Tegucigalpa', locale ENUM('es','en') NOT NULL DEFAULT 'es', bot_name VARCHAR(100) NOT NULL DEFAULT 'NIVO', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, locale ENUM('es','en') NOT NULL DEFAULT 'es', status ENUM('invited','active','disabled') NOT NULL DEFAULT 'active', mfa_enabled TINYINT(1) NOT NULL DEFAULT 0, last_login_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE teams (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, INDEX(tenant_id));
CREATE TABLE tenant_users (tenant_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, role_code VARCHAR(40) NOT NULL DEFAULT 'agent', team_id BIGINT UNSIGNED NULL, is_owner TINYINT(1) NOT NULL DEFAULT 0, PRIMARY KEY(tenant_id,user_id), INDEX(team_id));
CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NULL, code VARCHAR(40) NOT NULL, name VARCHAR(80) NOT NULL, permissions_json JSON NOT NULL, UNIQUE KEY uq_role(tenant_id,code));
CREATE TABLE plans (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, monthly_price DECIMAL(12,2) NOT NULL DEFAULT 0, currency CHAR(3) NOT NULL DEFAULT 'HNL', max_users INT NULL, max_channels INT NULL, features_json JSON NULL, active TINYINT(1) NOT NULL DEFAULT 1);
CREATE TABLE subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, plan_id BIGINT UNSIGNED NOT NULL, status ENUM('trial','active','past_due','suspended','cancelled') NOT NULL DEFAULT 'trial', starts_at DATETIME NOT NULL, renews_at DATETIME NULL, grace_until DATETIME NULL, monthly_amount DECIMAL(12,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'HNL', notes VARCHAR(500), INDEX(tenant_id,status));
CREATE TABLE tenant_channel_entitlements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, channel_type ENUM('whatsapp','messenger','instagram') NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 0, monthly_amount DECIMAL(12,2) NOT NULL DEFAULT 0, UNIQUE KEY uq_entitlement(tenant_id,channel_type));
CREATE TABLE channels (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, type ENUM('whatsapp','messenger','instagram') NOT NULL, name VARCHAR(120) NOT NULL, external_account_id VARCHAR(190), external_phone_id VARCHAR(190), display_address VARCHAR(190), token_ciphertext TEXT, token_expires_at DATETIME NULL, status ENUM('pending','connected','warning','disconnected') NOT NULL DEFAULT 'pending', settings_json JSON NULL, last_event_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(tenant_id,type,status));
CREATE TABLE contacts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(160), phone VARCHAR(40), email VARCHAR(190), avatar_url VARCHAR(500), custom_fields JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(tenant_id,phone), INDEX(tenant_id,email));
CREATE TABLE contact_identities (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, channel_id BIGINT UNSIGNED NOT NULL, external_id VARCHAR(190) NOT NULL, profile_json JSON NULL, UNIQUE KEY uq_identity(channel_id,external_id));
CREATE TABLE contact_external_refs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, external_system VARCHAR(80) NOT NULL, external_id VARCHAR(190) NOT NULL, UNIQUE KEY uq_ext(tenant_id,external_system,external_id));
CREATE TABLE conversations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, channel_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, assigned_user_id BIGINT UNSIGNED NULL, team_id BIGINT UNSIGNED NULL, status ENUM('open','pending','resolved','closed') NOT NULL DEFAULT 'open', priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal', unread_count INT NOT NULL DEFAULT 0, last_message_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(tenant_id,status,last_message_at));
CREATE TABLE messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, conversation_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, external_message_id VARCHAR(190) NULL, direction ENUM('in','out') NOT NULL, sender_type ENUM('contact','user','bot','system') NOT NULL, sender_user_id BIGINT UNSIGNED NULL, type VARCHAR(40) NOT NULL DEFAULT 'text', body TEXT NULL, media_json JSON NULL, status VARCHAR(40) NULL, sent_at DATETIME NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_external(tenant_id,external_message_id), INDEX(conversation_id,sent_at));
CREATE TABLE media_library (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, original_name VARCHAR(255) NOT NULL, stored_path VARCHAR(500) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, purpose ENUM('branding','chat','template','attachment') NOT NULL DEFAULT 'attachment', uploaded_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(tenant_id,purpose));
CREATE TABLE conversation_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, conversation_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, body TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tags (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(80) NOT NULL, color VARCHAR(20), UNIQUE KEY uq_tag(tenant_id,name));
CREATE TABLE conversation_tags (conversation_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(conversation_id,tag_id));
CREATE TABLE quick_replies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, shortcut VARCHAR(80) NOT NULL, title VARCHAR(120) NOT NULL, body TEXT NOT NULL, team_id BIGINT UNSIGNED NULL, active TINYINT(1) DEFAULT 1, UNIQUE KEY uq_qr(tenant_id,shortcut));
CREATE TABLE bot_profiles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL DEFAULT 'NIVO', enabled TINYINT(1) NOT NULL DEFAULT 0, mode ENUM('rules','ai','hybrid') NOT NULL DEFAULT 'hybrid', provider VARCHAR(60) NULL, model VARCHAR(100) NULL, system_prompt TEXT NULL, fallback_message TEXT NULL, handoff_rules_json JSON NULL, business_hours_json JSON NULL, knowledge_enabled TINYINT(1) NOT NULL DEFAULT 0, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_bot_tenant(tenant_id));
CREATE TABLE bot_flows (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(140) NOT NULL, version INT NOT NULL DEFAULT 1, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', definition_json JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE knowledge_sources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, source_type ENUM('text','url','file','faq','integration') NOT NULL, source_ref VARCHAR(500), content LONGTEXT NULL, status ENUM('pending','ready','error') NOT NULL DEFAULT 'pending', updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(tenant_id,status));
CREATE TABLE api_keys (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, key_prefix VARCHAR(20) NOT NULL, key_hash VARCHAR(255) NOT NULL, scopes_json JSON NOT NULL, expires_at DATETIME NULL, revoked_at DATETIME NULL, last_used_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(tenant_id));
CREATE TABLE outgoing_webhooks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, uuid CHAR(36) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, url VARCHAR(500) NOT NULL, secret_ciphertext TEXT NOT NULL, events_json JSON NOT NULL, active TINYINT(1) DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE webhook_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NULL, provider VARCHAR(40) NOT NULL, event_key VARCHAR(190) NOT NULL, payload_json JSON NOT NULL, signature_valid TINYINT(1) NOT NULL DEFAULT 0, status ENUM('received','processing','processed','failed') NOT NULL DEFAULT 'received', attempts INT NOT NULL DEFAULT 0, received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at DATETIME NULL, UNIQUE KEY uq_event(provider,event_key), INDEX(status,received_at));
CREATE TABLE branding_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL UNIQUE, app_title VARCHAR(120), logo_path VARCHAR(255), logo_dark_path VARCHAR(255), favicon_path VARCHAR(255), login_image_path VARCHAR(255), primary_color VARCHAR(20), secondary_color VARCHAR(20), surface_radius SMALLINT NOT NULL DEFAULT 14, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80), entity_id VARCHAR(190), ip_address VARCHAR(64), user_agent VARCHAR(500), metadata_json JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(tenant_id,created_at));
CREATE TABLE user_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash VARCHAR(255) NOT NULL UNIQUE, remember_me TINYINT(1) NOT NULL DEFAULT 0, ip_address VARCHAR(64), user_agent VARCHAR(500), expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO plans(code,name,monthly_price,currency,max_users,max_channels,features_json) VALUES
('starter','Starter',0,'HNL',3,1,JSON_OBJECT('inbox',true,'bot','rules')),
('business','Business',0,'HNL',15,3,JSON_OBJECT('inbox',true,'bot','hybrid','api',true));
