<?php
$title='Automatizaciones';
require __DIR__.'/partials/top.php';
$tid=(int)$_SESSION['user']['tenant_id'];
$flows=[];$campaigns=[];$socialRules=[];$callProfiles=[];
try{$q=appDb()->prepare('SELECT * FROM automation_flows WHERE tenant_id=? ORDER BY updated_at DESC,id DESC');$q->execute([$tid]);$flows=$q->fetchAll();}catch(Throwable $e){}
try{$q=appDb()->prepare('SELECT * FROM outbound_campaigns WHERE tenant_id=? ORDER BY updated_at DESC,id DESC');$q->execute([$tid]);$campaigns=$q->fetchAll();}catch(Throwable $e){}
try{$q=appDb()->prepare('SELECT * FROM social_automation_rules WHERE tenant_id=? ORDER BY updated_at DESC,id DESC');$q->execute([$tid]);$socialRules=$q->fetchAll();}catch(Throwable $e){}
try{$q=appDb()->prepare('SELECT p.*,c.name channel_name,c.display_address FROM whatsapp_ai_call_profiles p LEFT JOIN channels c ON c.id=p.channel_id AND c.tenant_id=p.tenant_id WHERE p.tenant_id=? ORDER BY p.updated_at DESC,p.id DESC');$q->execute([$tid]);$callProfiles=$q->fetchAll();}catch(Throwable $e){}
$whatsappChannels=[];try{$q=appDb()->prepare("SELECT id,name,display_address,status FROM channels WHERE tenant_id=? AND type='whatsapp' ORDER BY id DESC");$q->execute([$tid]);$whatsappChannels=$q->fetchAll();}catch(Throwable $e){}
?>
<section class="welcome automation-welcome"><div><small>AUTOMATIZACIÓN OMNICANAL</small><h1>Automatizaciones y campañas</h1><p>Diseña flujos, prepara campañas y administra automatizaciones sociales desde un mismo centro.</p></div><button class="primary" data-open="automationFlowModal"><i class="fa-solid fa-plus"></i> Nueva automatización</button></section>

<section class="automation-capability-grid">
 <article><i class="fa-solid fa-diagram-project"></i><div><b>Constructor visual</b><small>Disparador → condición → acción → transferencia.</small></div></article>
 <article><i class="fa-brands fa-instagram"></i><div><b>Instagram Comment-to-DM</b><small>Reglas preparadas para operar con la autorización oficial de Meta.</small></div></article>
 <article><i class="fa-brands fa-whatsapp"></i><div><b>Campañas de WhatsApp</b><small>Segmentación, programación y cola controlada de destinatarios.</small></div></article>
 <article><i class="fa-solid fa-phone-volume"></i><div><b>Llamadas WhatsApp + IA</b><small>Perfil y política de NIVO listos para proveedor compatible.</small></div></article>
</section>

<section class="panel spaced" id="builder"><div class="panel-head premium-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-diagram-project"></i></span><div><b>Constructor visual de automatizaciones</b><small>Los flujos se guardan como definición estructurada y quedan aislados por empresa.</small></div><button class="primary" data-open="automationFlowModal"><i class="fa-solid fa-plus"></i> Crear flujo</button></div>
<div class="automation-list">
<?php if(!$flows):?><div class="automation-empty"><i class="fa-solid fa-diagram-project"></i><b>Aún no hay automatizaciones</b><small>Crea tu primer flujo para mensajes entrantes, palabras clave o eventos de conversación.</small></div><?php endif?>
<?php foreach($flows as $f):$d=json_decode((string)$f['definition_json'],true)?:[];?><article class="automation-row"><div class="automation-row-icon"><i class="fa-solid fa-bolt"></i></div><div class="automation-row-main"><div><b><?=htmlspecialchars($f['name'])?></b><span class="ui-badge <?=$f['status']==='active'?'success':'muted'?>"><?=htmlspecialchars(ucfirst($f['status']))?></span></div><small><?=htmlspecialchars($f['trigger_type'])?> · <?=htmlspecialchars($f['channel_type'])?></small><div class="automation-flow-preview"><span><i class="fa-solid fa-play"></i><?=htmlspecialchars($d['trigger_label']??'Mensaje recibido')?></span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-filter"></i><?=htmlspecialchars($d['condition_label']??'Sin condición')?></span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-bolt"></i><?=htmlspecialchars($d['action_label']??'Responder con NIVO')?></span></div></div><div class="automation-row-actions"><button class="soft automation-toggle" data-id="<?=$f['id']?>" data-status="<?=$f['status']==='active'?'paused':'active'?>"><i class="fa-solid <?=$f['status']==='active'?'fa-pause':'fa-play'?>"></i><?=$f['status']==='active'?'Pausar':'Activar'?></button><button class="soft danger automation-delete" data-id="<?=$f['id']?>"><i class="fa-solid fa-trash"></i></button></div></article><?php endforeach?>
</div></section>

<section class="panel spaced" id="social"><div class="panel-head premium-card-head"><span class="premium-card-head-icon"><i class="fa-brands fa-instagram"></i></span><div><b>Automatización social</b><small>Comment-to-DM para Instagram y respuestas automáticas por palabras clave.</small></div><button class="primary" data-open="socialRuleModal"><i class="fa-solid fa-plus"></i> Nueva regla</button></div>
<div class="automation-list"><?php if(!$socialRules):?><div class="automation-empty"><i class="fa-solid fa-hashtag"></i><b>Sin reglas sociales</b><small>Cuando conectes Instagram oficialmente, estas reglas podrán reaccionar a comentarios entrantes.</small></div><?php endif?><?php foreach($socialRules as $r):?><article class="automation-row"><div class="automation-row-icon"><i class="fa-brands fa-instagram"></i></div><div class="automation-row-main"><div><b><?=htmlspecialchars($r['name'])?></b><span class="ui-badge <?=$r['active']?'success':'muted'?>"><?=$r['active']?'Activa':'Pausada'?></span></div><small><?=htmlspecialchars($r['channel_type'])?> · <?=htmlspecialchars($r['rule_type'])?></small><p><?=htmlspecialchars($r['keywords']?:'Todos los comentarios')?></p></div><div class="automation-row-actions"><button class="soft social-rule-toggle" data-id="<?=$r['id']?>" data-active="<?=$r['active']?'0':'1'?>"><i class="fa-solid fa-power-off"></i></button><button class="soft danger social-rule-delete" data-id="<?=$r['id']?>"><i class="fa-solid fa-trash"></i></button></div></article><?php endforeach?></div>
<div class="provider-dependency-note"><i class="fa-solid fa-circle-info"></i><span>La regla queda completamente configurada en ZYNKO. El envío real de DM depende de que Instagram Messaging y los permisos de comentarios estén autorizados en la app oficial de Meta.</span></div></section>

<section class="panel spaced" id="campaigns"><div class="panel-head premium-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-bullhorn"></i></span><div><b>Campañas masivas de WhatsApp</b><small>Crea campañas con audiencia controlada. ZYNKO nunca marca como enviada una campaña sin despacho real del proveedor.</small></div><button class="primary" data-open="campaignModal"><i class="fa-solid fa-plus"></i> Nueva campaña</button></div>
<div class="automation-list"><?php if(!$campaigns):?><div class="automation-empty"><i class="fa-solid fa-bullhorn"></i><b>Aún no hay campañas</b><small>Prepara una campaña y mantenla en borrador hasta tener un canal WhatsApp autorizado.</small></div><?php endif?><?php foreach($campaigns as $c):?><article class="automation-row"><div class="automation-row-icon"><i class="fa-brands fa-whatsapp"></i></div><div class="automation-row-main"><div><b><?=htmlspecialchars($c['name'])?></b><span class="ui-badge <?=$c['status']==='completed'?'success':($c['status']==='scheduled'?'info':'muted')?>"><?=htmlspecialchars(ucfirst($c['status']))?></span></div><small><?=htmlspecialchars($c['audience_type'])?><?=$c['scheduled_at']?' · '.htmlspecialchars($c['scheduled_at']):''?></small><div class="campaign-stats"><span><b><?=(int)$c['total_recipients']?></b> destinatarios</span><span><b><?=(int)$c['sent_count']?></b> enviados</span><span><b><?=(int)$c['delivered_count']?></b> entregados</span><span><b><?=(int)$c['failed_count']?></b> fallidos</span></div></div><div class="automation-row-actions"><button class="soft campaign-prepare" data-id="<?=$c['id']?>"><i class="fa-solid fa-list-check"></i> Preparar audiencia</button><button class="primary compact campaign-dispatch" data-id="<?=$c['id']?>"><i class="fa-solid fa-paper-plane"></i> Despachar lote</button><button class="soft danger campaign-delete" data-id="<?=$c['id']?>"><i class="fa-solid fa-trash"></i></button></div></article><?php endforeach?></div></section>

<section class="panel spaced" id="calls"><div class="panel-head premium-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-phone-volume"></i></span><div><b>Llamadas de WhatsApp con NIVO IA</b><small>Configura el comportamiento de IA y transferencia. La llamada real requiere que Meta habilite Calling API para la cuenta y un proveedor de voz compatible.</small></div><button class="primary" data-open="callProfileModal"><i class="fa-solid fa-plus"></i> Nuevo perfil</button></div>
<div class="automation-list"><?php if(!$callProfiles):?><div class="automation-empty"><i class="fa-solid fa-phone-volume"></i><b>Sin perfiles de llamada</b><small>Crea un perfil de NIVO para dejar lista la lógica cuando tu cuenta de WhatsApp tenga llamadas habilitadas.</small></div><?php endif?><?php foreach($callProfiles as $cp):?><article class="automation-row"><div class="automation-row-icon"><i class="fa-solid fa-headset"></i></div><div class="automation-row-main"><div><b><?=htmlspecialchars($cp['name'])?></b><span class="ui-badge <?=$cp['enabled']?'success':'muted'?>"><?=$cp['enabled']?'Activo':'Inactivo'?></span></div><small><?=htmlspecialchars($cp['channel_name']?:'Sin canal')?><?=!empty($cp['display_address'])?' · '.htmlspecialchars($cp['display_address']):''?></small><p><?=htmlspecialchars($cp['voice_name']?:'Voz por definir')?> · Transferencia humana <?=$cp['handoff_enabled']?'habilitada':'deshabilitada'?></p></div><div class="automation-row-actions"><button class="soft call-profile-toggle" data-id="<?=$cp['id']?>" data-active="<?=$cp['enabled']?'0':'1'?>"><i class="fa-solid fa-power-off"></i></button><button class="soft danger call-profile-delete" data-id="<?=$cp['id']?>"><i class="fa-solid fa-trash"></i></button></div></article><?php endforeach?></div></section>

<div class="modal-shell" id="automationFlowModal"><div class="modal-card automation-modal"><div class="modal-head"><div><b>Nueva automatización</b><small>Construye el flujo con bloques claros y editables.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="automationFlowForm"><input type="hidden" name="action" value="automation_flow_save"><div class="settings-grid"><div class="field full"><label>Nombre del flujo</label><input name="name" maxlength="160" required placeholder="Ej. Prospecto interesado en precios"></div><div class="field"><label>Disparador</label><select name="trigger_type" class="select2"><option value="message_received">Mensaje recibido</option><option value="keyword">Palabra clave</option><option value="conversation_created">Conversación creada</option><option value="conversation_pending">Conversación pendiente</option></select></div><div class="field"><label>Canal</label><select name="channel_type" class="select2"><option value="all">Todos</option><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="messenger">Messenger</option><option value="webchat">NIVO Web Chat</option><option value="telegram">Telegram</option></select></div><div class="field full"><label>Condición / palabras clave</label><input name="condition_value" maxlength="1000" placeholder="precio, plan, cotización"></div><div class="field"><label>Acción</label><select name="action_type" class="select2"><option value="nivo_reply">Responder con NIVO</option><option value="send_message">Enviar mensaje fijo</option><option value="assign_agent">Asignar a agente</option><option value="handoff">Transferir a humano</option><option value="add_tag">Agregar etiqueta</option></select></div><div class="field"><label>Estado inicial</label><select name="status" class="select2"><option value="draft">Borrador</option><option value="active">Activo</option></select></div><div class="field full"><label>Contenido de la acción</label><textarea name="action_value" rows="5" maxlength="5000" placeholder="Mensaje o instrucciones para NIVO"></textarea></div></div><div class="automation-builder-preview"><span><i class="fa-solid fa-play"></i> Disparador</span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-filter"></i> Condición</span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-bolt"></i> Acción</span></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar flujo</button></div></form></div></div>

<div class="modal-shell" id="socialRuleModal"><div class="modal-card"><div class="modal-head"><div><b>Nueva regla social</b><small>Configura Instagram Comment-to-DM sin mezclarlo con las reglas generales de NIVO.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="socialRuleForm"><input type="hidden" name="action" value="social_rule_save"><input type="hidden" name="channel_type" value="instagram"><input type="hidden" name="rule_type" value="comment_to_dm"><div class="settings-grid"><div class="field full"><label>Nombre</label><input name="name" required maxlength="160" placeholder="Ej. Comentarios de precios"></div><div class="field full"><label>Palabras clave del comentario</label><input name="keywords" maxlength="1000" placeholder="precio, información, quiero"></div><div class="field full"><label>Mensaje privado</label><textarea name="response_text" required rows="5" maxlength="5000" placeholder="Hola, gracias por comentar. Te comparto la información..."></textarea></div><div class="field full"><label class="switch-line"><input type="checkbox" name="active" checked><span class="switch-control"></span><span class="switch-label-text">Regla activa</span></label></div></div><div class="modal-actions"><button type="button" class="soft modal-close">Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar regla</button></div></form></div></div>

<div class="modal-shell" id="campaignModal"><div class="modal-card"><div class="modal-head"><div><b>Nueva campaña de WhatsApp</b><small>Crea la campaña y prepara audiencia. El despacho requiere un canal oficial conectado.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="campaignForm"><input type="hidden" name="action" value="campaign_save"><div class="settings-grid"><div class="field full"><label>Nombre de campaña</label><input name="name" maxlength="160" required></div><div class="field"><label>Audiencia</label><select name="audience_type" class="select2"><option value="all_contacts">Todos los contactos con WhatsApp</option><option value="unassigned">Contactos sin conversación asignada</option><option value="recent_30d">Contactos activos últimos 30 días</option></select></div><div class="field"><label>Programar <small>opcional</small></label><input type="datetime-local" name="scheduled_at"></div><div class="field full"><label>Nombre de plantilla oficial <small>opcional</small></label><input name="template_name" maxlength="160" placeholder="Ej. promo_octubre"></div><div class="field full"><label>Mensaje</label><textarea name="message_body" rows="6" maxlength="5000" required></textarea></div></div><div class="provider-dependency-note"><i class="fa-solid fa-shield-halved"></i><span>Para iniciar conversaciones fuera de la ventana permitida por WhatsApp se debe usar una plantilla aprobada por Meta. ZYNKO conserva este dato y no simula entregas.</span></div><div class="modal-actions"><button type="button" class="soft modal-close">Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar campaña</button></div></form></div></div>

<div class="modal-shell" id="callProfileModal"><div class="modal-card"><div class="modal-head"><div><b>Perfil de llamadas con NIVO</b><small>Política de IA para llamadas de WhatsApp compatibles.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="callProfileForm"><input type="hidden" name="action" value="ai_call_profile_save"><div class="settings-grid"><div class="field full"><label>Nombre</label><input name="name" required maxlength="160"></div><div class="field full"><label>Canal WhatsApp</label><select name="channel_id" class="select2"><option value="0">Seleccionar al habilitar</option><?php foreach($whatsappChannels as $wc):?><option value="<?=$wc['id']?>"><?=htmlspecialchars($wc['name'].($wc['display_address']?' · '.$wc['display_address']:''))?></option><?php endforeach?></select></div><div class="field"><label>Voz / perfil</label><input name="voice_name" maxlength="120" placeholder="Ej. NIVO ES"></div><div class="field"><label class="switch-line"><input type="checkbox" name="handoff_enabled" checked><span class="switch-control"></span><span class="switch-label-text">Permitir transferencia humana</span></label></div><div class="field full"><label>Instrucciones para NIVO</label><textarea name="system_prompt" rows="6" maxlength="8000" placeholder="Saluda, identifica la intención y transfiere si..."></textarea></div><div class="field full"><label class="switch-line"><input type="checkbox" name="enabled"><span class="switch-control"></span><span class="switch-label-text">Perfil activo</span></label></div></div><div class="modal-actions"><button type="button" class="soft modal-close">Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar perfil</button></div></form></div></div>

<script>
document.addEventListener('DOMContentLoaded',()=>{
 const send=async fd=>{const r=await fetch(location.href,{method:'POST',headers:{'X-ZYNKO-AJAX':'1'},body:fd});return r.json()};
 const bind=(sel)=>document.querySelector(sel)?.addEventListener('submit',async e=>{e.preventDefault();const j=await send(new FormData(e.currentTarget));showNotify(j.ok?'success':'error',j.ok?'Listo':'Error',j.message);if(j.ok)setTimeout(()=>location.reload(),350)});
 ['#automationFlowForm','#socialRuleForm','#campaignForm','#callProfileForm'].forEach(bind);
 const act=async(action,id,extra={})=>{const fd=new FormData();fd.append('action',action);fd.append('id',id);Object.entries(extra).forEach(([k,v])=>fd.append(k,v));const j=await send(fd);showNotify(j.ok?'success':'error',j.ok?'Listo':'Error',j.message);if(j.ok)setTimeout(()=>location.reload(),300)};
 document.querySelectorAll('.automation-toggle').forEach(b=>b.onclick=()=>act('automation_flow_status',b.dataset.id,{status:b.dataset.status}));
 document.querySelectorAll('.automation-delete').forEach(b=>b.onclick=async()=>{const r=await Swal.fire({title:'Eliminar automatización',text:'Esta acción no se puede deshacer.',icon:'warning',showCancelButton:true,confirmButtonText:'Eliminar',cancelButtonText:'Cancelar',allowOutsideClick:false});if(r.isConfirmed)act('automation_flow_delete',b.dataset.id)});
 document.querySelectorAll('.social-rule-toggle').forEach(b=>b.onclick=()=>act('social_rule_status',b.dataset.id,{active:b.dataset.active}));
 document.querySelectorAll('.social-rule-delete').forEach(b=>b.onclick=()=>act('social_rule_delete',b.dataset.id));
 document.querySelectorAll('.campaign-prepare').forEach(b=>b.onclick=()=>act('campaign_prepare',b.dataset.id));
 document.querySelectorAll('.campaign-dispatch').forEach(b=>b.onclick=async()=>{const r=await Swal.fire({title:'Despachar campaña',text:'Se enviará un lote real por el canal WhatsApp conectado. ¿Continuar?',icon:'question',showCancelButton:true,confirmButtonText:'Sí, despachar',cancelButtonText:'Cancelar',allowOutsideClick:false});if(r.isConfirmed)act('campaign_dispatch',b.dataset.id)});
 document.querySelectorAll('.campaign-delete').forEach(b=>b.onclick=()=>act('campaign_delete',b.dataset.id));
 document.querySelectorAll('.call-profile-toggle').forEach(b=>b.onclick=()=>act('ai_call_profile_status',b.dataset.id,{enabled:b.dataset.active}));
 document.querySelectorAll('.call-profile-delete').forEach(b=>b.onclick=()=>act('ai_call_profile_delete',b.dataset.id));
});
</script>
<?php require __DIR__.'/partials/bottom.php'; ?>
