<?php
$title='Canales'; require __DIR__.'/partials/top.php';
$channelRows=[]; try{$st=appDb()->prepare("SELECT id,type,name,display_address,status,last_event_at FROM channels WHERE tenant_id=? ORDER BY FIELD(type,'whatsapp','messenger','instagram'),id");$st->execute([$_SESSION['user']['tenant_id']]);foreach($st->fetchAll() as $r)$channelRows[$r['type']]=$r;}catch(Throwable $e){}
$catalog=[]; try{$q=appDb()->query("SELECT code,name,icon_class,icon_style,description,connector_ready,visible,linkable FROM channel_connector_catalog WHERE visible=1 ORDER BY sort_order,name");foreach($q->fetchAll() as $c)$catalog[$c['code']]=[$c['name'],$c['icon_class'],$c['icon_style'],$c['description'],(bool)$c['connector_ready']&&(bool)$c['linkable'],(bool)$c['connector_ready'],(bool)$c['linkable']];}catch(Throwable $e){}
if(!$catalog)$catalog=[
 'whatsapp'=>['WhatsApp Business','fa-brands fa-whatsapp','whatsapp','Mensajes, multimedia, documentos y atención en tiempo real.',true,true,true],
 'messenger'=>['Messenger','fa-brands fa-facebook-messenger','messenger','Conversaciones de páginas de Facebook conectadas a la empresa.',true,true,true],
 'instagram'=>['Instagram Messaging','fa-brands fa-instagram','instagram','Mensajes de Instagram mediante la autorización oficial de Meta.',true,true,true],
];
$statusLabels=['pending'=>'Pendiente de autorización','connected'=>'Conectado','warning'=>'Requiere atención','disconnected'=>'Desconectado'];
?>
<section class="welcome channel-welcome"><div><small>OMNICANAL</small><h1>Canales</h1><p>Conecta y administra los canales de atención de tu empresa desde un solo lugar.</p></div><div class="channel-welcome-actions"><?php if(isPlatformOwner()):?><button class="secondary-action" id="openChannelAdmin"><i class="fa-solid fa-sliders"></i> Administrar catálogo</button><?php endif?><button class="primary" id="openChannelCatalog"><i class="fa-solid fa-plus"></i> Vincular canal</button></div></section>
<section class="channel-overview"><div><b><?=count($channelRows)?></b><span>Configurados</span></div><div><b><?=count(array_filter($channelRows,fn($r)=>$r['status']==='connected'))?></b><span>Conectados</span></div><div class="grow"><i class="fa-solid fa-circle-info"></i><span>Solo se marca un canal como conectado después de validar su autorización real.</span></div></section>
<section class="channel-cards channel-grid">
<?php foreach($catalog as $type=>$c): $row=$channelRows[$type]??null; $status=$row['status']??null; ?>
<article class="panel channel-card channel-tile <?=!$row?'is-available':''?>">
 <div class="channel-tile-top"><span class="channel-icon <?=$c[2]?>"><i class="<?=$c[1]?>"></i></span><span class="channel-state <?=$status==='connected'?'connected':($status==='warning'?'warning':'')?>"><i class="fa-solid fa-circle"></i> <?=$row?htmlspecialchars($statusLabels[$status]??ucfirst($status)):'Disponible'?></span></div>
 <div class="channel-tile-copy"><h3><?=htmlspecialchars($c[0])?></h3><p><?=htmlspecialchars($c[3])?></p><?php if($row && !empty($row['display_address'])):?><small class="channel-account"><i class="fa-solid fa-link"></i> <?=htmlspecialchars($row['display_address'])?></small><?php endif?></div>
 <div class="channel-tile-actions"><?php if($row):?><button class="soft channel-config" data-channel="<?=$type?>"><i class="fa-solid fa-gear"></i> Configurar</button><?php elseif($c[4]):?><button class="soft channel-add" data-channel="<?=$type?>"><i class="fa-solid fa-plus"></i> Vincular</button><?php else:?><button class="soft channel-unavailable" data-channel-name="<?=htmlspecialchars($c[0],ENT_QUOTES,'UTF-8')?>" data-connector-ready="<?=$c[5]?'1':'0'?>" data-linkable="<?=$c[6]?'1':'0'?>"><i class="fa-solid fa-circle-info"></i> Ver estado</button><?php endif?></div>
</article><?php endforeach?>
</section>
<section class="panel meta-requirement"><div class="panel-head"><div><b><i class="fa-brands fa-meta"></i> Autorización requerida por Meta</b><small>Cada empresa conecta sus propias cuentas. ZYNKO no comparte credenciales entre empresas.</small></div></div><p class="field-help">WhatsApp Business, Messenger e Instagram requieren autorización oficial de Meta y los permisos correspondientes. Hasta completar y validar ese proceso, ZYNKO mantiene el canal como <b>Pendiente</b> y no simula una conexión.</p></section>
<section class="panel spaced" id="connection"><div class="panel-head"><div><b>Conexión guiada</b><small>Un flujo claro para incorporar nuevos canales sin comprometer la seguridad.</small></div></div><div class="steps"><span><b>1</b> Selecciona canal</span><span><b>2</b> Guarda identificadores</span><span><b>3</b> Autoriza proveedor</span><span><b>4</b> Validamos permisos</span><span><b>5</b> Webhook</span><span><b>6</b> Recibe mensajes</span></div></section>

<div class="modal-shell" id="channelCatalogModal" aria-hidden="true"><div class="modal-card channel-catalog-modal"><div class="modal-head"><div><b>Vincular un canal</b><small>Selecciona el canal que deseas incorporar a tu bandeja omnicanal.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><div class="channel-catalog-grid">
<?php foreach($catalog as $type=>$c): $row=$channelRows[$type]??null; ?><button type="button" class="channel-catalog-item <?=$c[4]?'':'coming-soon'?>" <?=$c[4]?'data-channel="'.$type.'"':''?>><span class="channel-icon <?=$c[2]?>"><i class="<?=$c[1]?>"></i></span><span><b><?=htmlspecialchars($c[0])?></b><small><?=$row?'Ya configurado':($c[4]?'Disponible para vincular':($c[5]?'No habilitado':'Conector en preparación'))?></small></span><i class="fa-solid <?=$c[4]?'fa-chevron-right':'fa-clock'?>"></i></button><?php endforeach?>
</div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cerrar</button></div></div></div>

<?php if(isPlatformOwner()):?>
<div class="modal-shell" id="channelAdminModal" aria-hidden="true"><div class="modal-card channel-catalog-modal"><div class="modal-head"><div><b>Administrar catálogo de canales</b><small>Controla qué conectores se muestran. La vinculación solo puede activarse cuando el conector real está implementado.</small></div><button class="modal-close" aria-label="Cerrar"><i class="fa-solid fa-xmark"></i></button></div><div class="channel-admin-note"><i class="fa-solid fa-circle-info"></i><span><b>Visible</b> controla si el canal aparece en el catálogo. <b>Permitir vincular</b> solo se habilita cuando el conector real está disponible.</span></div><div class="channel-admin-list">
<?php try{$aq=appDb()->query("SELECT code,name,icon_class,icon_style,connector_ready,visible,linkable FROM channel_connector_catalog ORDER BY sort_order,name");foreach($aq->fetchAll() as $a):?>
<form class="channel-admin-row channelCatalogForm"><input type="hidden" name="action" value="channel_catalog_save"><input type="hidden" name="code" value="<?=htmlspecialchars($a['code'])?>"><span class="channel-icon <?=htmlspecialchars($a['icon_style'])?>"><i class="<?=htmlspecialchars($a['icon_class'])?>"></i></span><div class="channel-admin-copy"><b><?=htmlspecialchars($a['name'])?></b><small><?=$a['connector_ready']?'Conector funcional disponible':'Conector todavía en desarrollo'?></small></div><div class="channel-admin-control"><strong>Mostrar canal</strong><label class="switch-line"><input type="checkbox" name="visible" <?=$a['visible']?'checked':''?>><span></span><em><?=$a['visible']?'Visible':'Oculto'?></em></label></div><div class="channel-admin-control"><strong>Permitir vincular</strong><label class="switch-line <?=$a['connector_ready']?'':'is-disabled'?>"><input type="checkbox" name="linkable" <?=$a['linkable']?'checked':''?> <?=$a['connector_ready']?'':'disabled'?>><span></span><em><?=$a['connector_ready']?($a['linkable']?'Habilitado':'Deshabilitado'):'No disponible'?></em></label></div><button class="primary compact-save"><i class="fa-solid fa-floppy-disk"></i> Guardar</button></form>
<?php endforeach;}catch(Throwable $e){}?></div><div class="modal-actions"><button type="button" class="secondary-action modal-close"><i class="fa-solid fa-xmark"></i> Cerrar</button></div></div></div>
<?php endif?>

<div class="modal-shell" id="channelModal" aria-hidden="true"><div class="modal-card"><div class="modal-head"><div><b id="channelModalTitle">Configurar canal</b><small>Los datos quedan aislados por empresa.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="channelForm"><input type="hidden" name="action" value="channel_save"><input type="hidden" name="type" id="channelType"><div class="settings-grid"><div class="field"><label>Nombre del canal</label><input name="name" required placeholder="Ej. Atención principal"></div><div class="field"><label>Identificador externo / cuenta</label><input name="external_account_id" placeholder="ID de cuenta Meta"></div><div class="field"><label>Phone Number ID / Página</label><input name="external_phone_id" placeholder="Según el canal"></div><div class="field"><label>Nombre o número visible</label><input name="display_address" placeholder="+504… / Página / @usuario"></div><div class="field"><label>App ID de Meta</label><input name="meta_app_id" placeholder="App ID"></div><div class="field"><label>Business Account ID</label><input name="business_id" placeholder="WABA / Business ID"></div><div class="field full"><label>Token de acceso</label><input name="token" type="password" autocomplete="new-password" placeholder="Se guardará cifrado"></div></div><div class="meta-note"><i class="fa-solid fa-shield-halved"></i><div><b>Vinculación oficial</b><small>ZYNKO utiliza las credenciales y autorización oficial del proveedor. Nunca marca un canal como conectado sin validarlo.</small></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar configuración</button></div></form></div></div>
<?php require __DIR__.'/partials/bottom.php'; ?>