<?php
$title='NIVO · Asistente inteligente'; require __DIR__.'/partials/top.php';
$tid=(int)$_SESSION['user']['tenant_id'];$botcfg=[];$sources=[];$rules=[];$stats=['sources'=>0,'rules'=>0];
try{
 $db=appDb();
 $db->exec("CREATE TABLE IF NOT EXISTS nivo_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(160) NOT NULL,keywords VARCHAR(500) NOT NULL,response TEXT NOT NULL,priority INT NOT NULL DEFAULT 100,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_nivo_rules_tenant(tenant_id,active,priority)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $st=$db->prepare('SELECT * FROM bot_profiles WHERE tenant_id=?');$st->execute([$tid]);$botcfg=$st->fetch()?:[];
 $st=$db->prepare("SELECT id,name,source_type,status,updated_at FROM knowledge_sources WHERE tenant_id=? ORDER BY updated_at DESC LIMIT 50");$st->execute([$tid]);$sources=$st->fetchAll();
 $st=$db->prepare("SELECT id,name,keywords,response,priority,active FROM nivo_rules WHERE tenant_id=? ORDER BY active DESC,priority ASC,id DESC");$st->execute([$tid]);$rules=$st->fetchAll();
 $stats=['sources'=>count($sources),'rules'=>count(array_filter($rules,fn($r)=>(int)$r['active']===1))];
}catch(Throwable $e){}
$aliases=[];if(isPlatformOwner()){try{$q=$db->prepare('SELECT id,display_name FROM nivo_agent_aliases WHERE tenant_id=? AND active=1 ORDER BY display_name');$q->execute([$tid]);$aliases=$q->fetchAll();}catch(Throwable $e){}}
$handoff=json_decode($botcfg['handoff_rules_json']??'{}',true)?:[];
$minConfidence=$handoff['min_confidence']??'medium';$autoHandoff=!array_key_exists('auto_handoff',$handoff)||!empty($handoff['auto_handoff']);$learnMode=$handoff['learn_mode']??'review';
?>
<section class="welcome nivo-welcome"><div><small>ASISTENTE INTELIGENTE</small><h1>NIVO</h1><p>Automatiza respuestas con reglas y conocimiento aprobado, sin inventar información.</p></div><span class="status-badge"><i class="fa-solid fa-circle"></i> <?=($botcfg['enabled']??0)?'Activo':'Inactivo'?></span></section>
<section class="kpis premium-kpis nivo-kpis">
 <article><span class="kpi-icon"><i class="fa-solid fa-power-off"></i></span><div><span>Estado</span><b><?=($botcfg['enabled']??0)?'Activo':'Inactivo'?></b><small>Por empresa</small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-route"></i></span><div><span>Motor actual</span><b>Local</b><small>Reglas + conocimiento</small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-book-open"></i></span><div><span>Conocimiento</span><b><?=$stats['sources']?></b><small>Fuentes autorizadas</small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-bolt"></i></span><div><span>Reglas activas</span><b><?=$stats['rules']?></b><small>Respuestas determinísticas</small></div></article>
</section>
<section class="nivo-tabs" aria-label="Secciones de NIVO"><a href="#behavior"><i class="fa-solid fa-sliders"></i> Comportamiento</a><a href="#rules"><i class="fa-solid fa-diagram-project"></i> Reglas</a><a href="#knowledge"><i class="fa-solid fa-book-open"></i> Conocimiento</a><a href="#playground"><i class="fa-solid fa-flask"></i> Probar NIVO</a></section>
<form id="botForm"><input type="hidden" name="action" value="bot_save"><section class="panel nivo-section" id="behavior"><div class="panel-head"><div><b>Comportamiento de NIVO</b><small>Configuración segura para el motor local. Más adelante podrás conectar un proveedor de IA sin rehacer NIVO.</small></div></div><div class="settings-grid">
 <div class="field"><label>Asistente habilitado</label><label class="switch-line"><input name="enabled" type="checkbox" <?=($botcfg['enabled']??0)?'checked':''?>><span></span> Activar NIVO</label><small class="field-help">Al desactivarlo, NIVO no sugerirá ni automatizará respuestas.</small></div>
 <div class="field"><label>Nombre visible</label><input name="name" maxlength="100" value="<?=htmlspecialchars($botcfg['name']??'NIVO')?>"><small class="field-help">Nombre que verán agentes y clientes cuando corresponda.</small></div>
 <div class="field"><label>Modo operativo</label><select name="mode" class="select2"><option value="rules" <?=($botcfg['mode']??'hybrid')==='rules'?'selected':''?>>Reglas y conocimiento local</option><option value="hybrid" <?=($botcfg['mode']??'hybrid')==='hybrid'?'selected':''?>>Híbrido preparado para IA futura</option></select><small class="field-help">Por ahora no se envían datos a proveedores externos de IA.</small></div>
 <div class="field"><label>Confianza mínima</label><select name="min_confidence" class="select2"><option value="low" <?=$minConfidence==='low'?'selected':''?>>Baja</option><option value="medium" <?=$minConfidence==='medium'?'selected':''?>>Media · recomendado</option><option value="high" <?=$minConfidence==='high'?'selected':''?>>Alta</option></select><small class="field-help">Si la coincidencia no alcanza este nivel, NIVO evita improvisar.</small></div>
 <div class="field"><label>Transferencia automática</label><label class="switch-line"><input name="auto_handoff" type="checkbox" <?=$autoHandoff?'checked':''?>><span></span> Pasar a humano si no sabe</label><small class="field-help">Evita respuestas inseguras cuando falta información autorizada.</small></div>
 <div class="field"><label>Aprendizaje desde conversaciones</label><select name="learn_mode" class="select2"><option value="off" <?=$learnMode==='off'?'selected':''?>>Desactivado</option><option value="review" <?=$learnMode==='review'?'selected':''?>>Solo con revisión humana</option></select><small class="field-help">NIVO nunca aprenderá automáticamente de una conversación sin aprobación.</small></div>
 <div class="field full"><label>Instrucciones del asistente</label><textarea name="system_prompt" maxlength="5000"><?=htmlspecialchars($botcfg['system_prompt']??'Responde únicamente con información autorizada de la empresa. Si no tienes suficiente información, transfiere a un agente humano.')?></textarea><small class="field-help">Define tono, límites y comportamiento. Estas instrucciones no reemplazan las reglas ni la base de conocimiento.</small></div>
 <div class="field full" id="handoff"><label>Mensaje de transferencia humana</label><textarea name="fallback_message" maxlength="1000"><?=htmlspecialchars($botcfg['fallback_message']??'No tengo información suficiente para responder con seguridad. Te comunicaré con un agente para continuar.')?></textarea></div>
 </div><div class="form-actions"><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar configuración</button></div></section></form>

<section class="grid2 nivo-grid">
 <article class="panel nivo-section" id="rules"><div class="panel-head"><div><b>Reglas de respuesta</b><small>Las reglas tienen prioridad sobre el conocimiento general y son ideales para horarios, políticas y respuestas exactas.</small></div><button type="button" class="soft" data-open="ruleModal"><i class="fa-solid fa-plus"></i> Nueva regla</button></div>
 <?php if(!$rules):?><div class="empty-compact"><i class="fa-solid fa-diagram-project"></i><b>Sin reglas</b><span>Crea reglas para respuestas que deben ser exactas.</span></div><?php else:?><div class="nivo-list"><?php foreach($rules as $r):?><div class="nivo-list-row"><div><b><?=htmlspecialchars($r['name'])?></b><small><?=htmlspecialchars($r['keywords'])?> · Prioridad <?=$r['priority']?></small><span><?=htmlspecialchars(mb_strimwidth($r['response'],0,140,'…'))?></span></div><span class="status-badge <?=!$r['active']?'muted':''?>"><?=$r['active']?'Activa':'Inactiva'?></span><button type="button" class="icon-btn rule-delete" data-id="<?=$r['id']?>" title="Eliminar regla"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div><?php endif?>
 </article>
 <article class="panel nivo-section" id="knowledge"><div class="panel-head"><div><b>Base de conocimiento</b><small>Contenido aprobado que NIVO puede consultar.</small></div><button type="button" class="soft" data-open="knowledgeModal"><i class="fa-solid fa-plus"></i> Agregar</button></div>
 <?php if(!$sources):?><div class="empty-compact"><i class="fa-solid fa-book-open"></i><b>Sin conocimiento todavía</b><span>Agrega FAQs, productos, procesos o políticas.</span></div><?php else:?><div class="nivo-list"><?php foreach($sources as $src):?><div class="nivo-list-row"><div><b><?=htmlspecialchars($src['name'])?></b><small><?=htmlspecialchars(strtoupper($src['source_type']))?> · <?=htmlspecialchars($src['status'])?></small></div><button type="button" class="icon-btn knowledge-delete" data-id="<?=$src['id']?>" title="Eliminar fuente"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div><?php endif?>
 <label class="upload-zone nivo-upload" tabindex="0"><i class="fa-solid fa-file-arrow-up"></i><b>Importar archivo de conocimiento</b><small>TXT, MD, CSV o JSON · máximo 2 MB</small><input id="knowledgeFile" type="file" accept=".txt,.md,.csv,.json,text/plain,text/csv,application/json" hidden></label>
 </article>
</section>
<?php if(isPlatformOwner()):?><section class="panel nivo-section" id="demo-agents"><div class="panel-head"><div><b>Agentes de demostración</b><small>Solo para tu empresa principal. Permite probar transferencias con nombres alternos cuando todavía no tienes suficientes usuarios reales.</small></div></div><form id="aliasForm" class="inline-form"><input type="hidden" name="action" value="nivo_alias_add"><div class="field"><label>Nombre visible</label><input name="display_name" required maxlength="160" placeholder="Ej. Juan Velásquez"></div><button class="primary"><i class="fa-solid fa-user-plus"></i> Agregar agente</button></form><div class="nivo-list"><?php foreach($aliases as $a):?><div class="nivo-list-row"><div><b><?=htmlspecialchars($a['display_name'])?></b><small>Agente de demostración</small></div><button type="button" class="icon-btn alias-delete" data-id="<?=$a['id']?>"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div></section><?php endif?>
<section class="panel nivo-section" id="playground"><div class="panel-head"><div><b>Probar NIVO antes de usarlo</b><small>Simula una pregunta. Verás la respuesta, confianza y fuente sin enviar nada al cliente.</small></div></div><div class="nivo-playground"><div class="field"><label>Mensaje de prueba</label><textarea id="nivoTestQuery" rows="4" placeholder="Ej. ¿Cuál es el horario de atención?"></textarea></div><div class="nivo-test-result" id="nivoTestResult"><i class="fa-solid fa-flask"></i><div><b>Esperando una prueba</b><small>La respuesta aparecerá aquí.</small></div></div></div><div class="form-actions"><button type="button" class="primary" id="nivoTestBtn"><i class="fa-solid fa-play"></i> Probar NIVO</button></div></section>

<div class="modal-shell" id="knowledgeModal"><div class="modal-card"><div class="modal-head"><div><b>Enseñar a NIVO</b><small>Solo agrega información que la empresa autoriza utilizar.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="knowledgeForm"><input type="hidden" name="action" value="knowledge_add"><div class="field"><label>Nombre de la fuente</label><input name="name" required maxlength="180" placeholder="Ej. Política de devoluciones"></div><div class="field"><label>Contenido autorizado</label><textarea name="content" required rows="9" maxlength="50000" placeholder="Escribe o pega la información..."></textarea></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-brain"></i> Guardar y enseñar</button></div></form></div></div>
<div class="modal-shell" id="ruleModal"><div class="modal-card"><div class="modal-head"><div><b>Nueva regla de NIVO</b><small>Usa palabras o frases separadas por coma. Si coinciden, NIVO responde exactamente lo configurado.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="ruleForm"><input type="hidden" name="action" value="nivo_rule_add"><div class="settings-grid"><div class="field"><label>Nombre</label><input name="name" required maxlength="160" placeholder="Ej. Horario"></div><div class="field"><label>Prioridad</label><input name="priority" type="number" min="1" max="999" value="100"></div><div class="field full"><label>Palabras o frases clave</label><input name="keywords" required maxlength="500" placeholder="horario, a qué hora abren, atención"></div><div class="field full"><label>Respuesta exacta</label><textarea name="response" required maxlength="5000" rows="6"></textarea></div><div class="field"><label class="switch-line"><input name="active" type="checkbox" checked><span></span> Regla activa</label></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar regla</button></div></form></div></div>
<?php require __DIR__.'/partials/bottom.php'; ?>
