<?php
$title='NIVO · Asistente inteligente'; require __DIR__.'/partials/top.php'; require_once dirname(__DIR__).'/Services/OpenAIProviderService.php';
$tid=(int)$_SESSION['user']['tenant_id'];$botcfg=[];$sources=[];$rules=[];$solutions=[];$modules=[];$webSources=[];$stats=['sources'=>0,'rules'=>0,'websites'=>0];
try{
 $db=appDb();
 $db->exec("CREATE TABLE IF NOT EXISTS nivo_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(160) NOT NULL,keywords VARCHAR(500) NOT NULL,response TEXT NOT NULL,priority INT NOT NULL DEFAULT 100,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_nivo_rules_tenant(tenant_id,active,priority)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

 $db->exec("CREATE TABLE IF NOT EXISTS nivo_solutions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,code VARCHAR(80) NOT NULL,description VARCHAR(700) NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_nivo_solution(tenant_id,code),INDEX(tenant_id,active))");
 $db->exec("CREATE TABLE IF NOT EXISTS nivo_solution_modules(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,solution_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,description VARCHAR(500) NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_nivo_module(solution_id,name),INDEX(tenant_id,solution_id,active))");
 if(isPlatformOwner()){$c=$db->prepare('SELECT COUNT(*) FROM nivo_solutions WHERE tenant_id=?');$c->execute([$tid]);if(!(int)$c->fetchColumn()){$db->prepare("INSERT INTO nivo_solutions(tenant_id,name,code,description) VALUES(?, 'CAMI','cami','Solución para clínicas, laboratorios, pacientes, expedientes, procesos médicos y facturación relacionada al entorno médico.'),(?, 'IZZY','izzy','Solución empresarial para facturación general, POS, inventario, cuentas por cobrar, cuentas por pagar, restaurantes y operación comercial.')")->execute([$tid,$tid]);}}
 $st=$db->prepare('SELECT * FROM nivo_solutions WHERE tenant_id=? AND active=1 ORDER BY name');$st->execute([$tid]);$solutions=$st->fetchAll();
 $st=$db->prepare('SELECT m.*,s.name solution_name FROM nivo_solution_modules m JOIN nivo_solutions s ON s.id=m.solution_id WHERE m.tenant_id=? AND m.active=1 ORDER BY s.name,m.name');$st->execute([$tid]);$modules=$st->fetchAll();
 $st=$db->prepare('SELECT * FROM bot_profiles WHERE tenant_id=?');$st->execute([$tid]);$botcfg=$st->fetch()?:[];
 $st=$db->prepare("SELECT ks.id,ks.name,ks.source_type,ks.status,ks.approval_status,ks.solution_id,ks.module_id,ks.updated_at,s.name solution_name,m.name module_name FROM knowledge_sources ks LEFT JOIN nivo_solutions s ON s.id=ks.solution_id LEFT JOIN nivo_solution_modules m ON m.id=ks.module_id WHERE ks.tenant_id=? AND NOT (ks.source_type='url' AND ks.source_ref LIKE 'website:%') ORDER BY ks.updated_at DESC LIMIT 100");$st->execute([$tid]);$sources=$st->fetchAll();
 $st=$db->prepare("SELECT id,name,keywords,response,priority,active FROM nivo_rules WHERE tenant_id=? ORDER BY active DESC,priority ASC,id DESC");$st->execute([$tid]);$rules=$st->fetchAll();
 require_once dirname(__DIR__).'/Services/NivoWebsiteKnowledgeService.php';$webSvc=new NivoWebsiteKnowledgeService($db,dirname(__DIR__,2));$webSources=$webSvc->list($tid);
 $stats=['sources'=>count(array_filter($sources,fn($r)=>($r['approval_status']??'approved')==='approved')),'rules'=>count(array_filter($rules,fn($r)=>(int)$r['active']===1)),'websites'=>count(array_filter($webSources,fn($r)=>(int)$r['active']===1))];
}catch(Throwable $e){}
$webchatActive=false;try{$wq=$db->prepare('SELECT COUNT(*) FROM webchat_widgets WHERE tenant_id=? AND enabled=1');$wq->execute([$tid]);$webchatActive=(int)$wq->fetchColumn()>0;}catch(Throwable $e){}
$aliases=[];if(isPlatformOwner()){try{$q=$db->prepare('SELECT id,display_name FROM nivo_agent_aliases WHERE tenant_id=? AND active=1 ORDER BY display_name');$q->execute([$tid]);$aliases=$q->fetchAll();}catch(Throwable $e){}}
$handoff=json_decode($botcfg['handoff_rules_json']??'{}',true)?:[];$policy=json_decode($botcfg['channel_policy_json']??'{}',true)?:[];
$minConfidence=$handoff['min_confidence']??'medium';$nivoChannels=$policy['channels']??['webchat','whatsapp','messenger','instagram','telegram','email','api'];$autoHandoff=!array_key_exists('auto_handoff',$handoff)||!empty($handoff['auto_handoff']);$learnMode=$handoff['learn_mode']??'review';$tone=$handoff['tone']??'professional';$maxResponse=(int)($handoff['max_response_length']??700);$handoffKeywords=$handoff['handoff_keywords']??'agente, asesor, persona, humano, representante';$hours=json_decode($botcfg['business_hours_json']??'{}',true)?:[];$hoursEnabled=!empty($hours['enabled']);$businessStart=$hours['start']??'08:00';$businessEnd=$hours['end']??'17:00';$businessDays=$hours['days']??[1,2,3,4,5];$outsideMessage=$hours['outside_message']??'Gracias por escribirnos. En este momento estamos fuera de nuestro horario de atención; dejaré tu conversación lista para que un agente continúe contigo.';$specialDates=$hours['special_dates']??[];if(!is_array($specialDates))$specialDates=[];
$openAiGlobal=[];$openAiUsage=[];$tenantAi=[];$tenantAiAllowed=!empty($zynkoPlanContext['unrestricted'])||!empty($zynkoPlanContext['external_ai_included']);$tenantAiPlanChannels=$zynkoPlanContext['external_ai_channels']??[];
try{$openAiSvc=new OpenAIProviderService($db,dirname(__DIR__,2));$openAiGlobal=$openAiSvc->settings();$openAiUsage=$openAiSvc->usageSummary(isPlatformOwner()?null:$tid);$tenantAi=$openAiSvc->tenantSettings($tid);}catch(Throwable $e){}
$tenantAiChannels=$tenantAi['channels']??['webchat'];$openAiConnected=!empty($openAiGlobal['api_key_configured']);$openAiEnabled=!empty($openAiGlobal['enabled']);$tenantAiSwitchAllowed=$tenantAiAllowed&&$openAiConnected&&$openAiEnabled;$tenantExternalEnabled=!empty($tenantAi['enabled'])&&$tenantAiAllowed&&$openAiConnected&&$openAiEnabled&&(($botcfg['mode']??'hybrid')==='hybrid');
$monthTokens=(int)($openAiUsage['input_tokens']??0)+(int)($openAiUsage['output_tokens']??0);$localCost=(float)($openAiUsage['estimated_cost_usd']??0);$remoteCost=(float)($openAiGlobal['remote_month_cost_usd']??0);$globalBudget=(float)($openAiGlobal['monthly_budget_usd']??0);$remaining=$globalBudget>0?max(0,$globalBudget-($remoteCost>0?$remoteCost:$localCost)):null;
?>
<section class="welcome nivo-welcome nivo-page-welcome"><div><small>ASISTENTE INTELIGENTE</small><h1>NIVO</h1><p>Automatiza respuestas con reglas y conocimiento aprobado, sin inventar información.</p></div><div class="nivo-welcome-tools"><div class="nivo-identity-card" aria-label="Identidad de NIVO"><img src="assets/img/nivo-email.png" alt="NIVO"><span><b>NIVO</b><small>Tu asistente inteligente</small></span></div><span class="status-badge <?=($botcfg['enabled']??0)?'connected':'inactive'?>"><i class="fa-solid fa-circle"></i> <?=($botcfg['enabled']??0)?'Activo':'Inactivo'?></span></div></section>
<section class="kpis premium-kpis nivo-kpis">
 <article><span class="kpi-icon"><i class="fa-solid fa-power-off"></i></span><div><span>Estado</span><b><?=($botcfg['enabled']??0)?'Activo':'Inactivo'?></b><small>Por empresa</small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-route"></i></span><div><span>Motor actual</span><b><?= $tenantExternalEnabled?'Local → OpenAI':'Local' ?></b><small><?= $tenantExternalEnabled?'Fallback externo activo':'Reglas + conocimiento' ?></small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-book-open"></i></span><div><span>Conocimiento</span><b><?=$stats['sources']?></b><small><?=$stats['websites']?> sitio(s) web · fuentes aprobadas</small></div></article>
 <article><span class="kpi-icon"><i class="fa-solid fa-bolt"></i></span><div><span>Reglas activas</span><b><?=$stats['rules']?></b><small>Respuestas determinísticas</small></div></article>
</section>
<section class="nivo-ai-explainer">
 <div class="nivo-ai-explainer-brand"><img src="assets/img/nivo-email.png" alt="NIVO"><span><small>NIVO IA + WEB CHAT</small><b><?=($botcfg['enabled']??0)?'Tu asistente ya puede participar en las conversaciones':'Activa NIVO para automatizar con control'?></b></span></div>
 <div class="nivo-ai-flow"><span><i class="fa-solid fa-diagram-project"></i><b>1. Reglas</b><small>Responde exactamente lo definido cuando detecta palabras clave.</small></span><span><i class="fa-solid fa-book-open"></i><b>2. Conocimiento</b><small>Busca información aprobada por tu empresa antes de contestar.</small></span><span><i class="fa-solid fa-headset"></i><b>3. Transferencia</b><small>Pasa a una persona cuando el visitante lo pide o falta información segura.</small></span><span><i class="fa-solid fa-inbox"></i><b>4. Bandeja</b><small>Todo queda dentro de la conversación para que tu equipo continúe.</small></span></div>
 <div class="nivo-ai-connection <?=($webchatActive&&($botcfg['enabled']??0))?'is-on':''?>"><i class="fa-solid fa-link"></i><span><b><?=($webchatActive&&($botcfg['enabled']??0))?'NIVO IA está conectado al flujo de NIVO Web Chat':'Integración preparada con NIVO Web Chat'?></b><small><?=($webchatActive&&($botcfg['enabled']??0))?'Cuando llega un mensaje por Web Chat, NIVO evalúa reglas, conocimiento y transferencia humana automáticamente.':'Activa el asistente y el Web Chat para usar este flujo con visitantes reales.'?></small></span></div>
</section>
<section class="nivo-tabs" aria-label="Secciones de NIVO"><a href="#behavior"><i class="fa-solid fa-sliders"></i> Comportamiento</a><a href="#solutions"><i class="fa-solid fa-layer-group"></i> Soluciones</a><a href="#rules"><i class="fa-solid fa-diagram-project"></i> Reglas</a><a href="#knowledge-sites"><i class="fa-solid fa-globe"></i> Fuentes web</a><a href="#knowledge"><i class="fa-solid fa-book-open"></i> Conocimiento</a><a href="#external-ai"><i class="fa-solid fa-cloud"></i> IA externa</a><a href="#playground"><i class="fa-solid fa-flask"></i> Probar NIVO</a></section>
<form id="botForm"><input type="hidden" name="action" value="bot_save"><section class="panel nivo-section" id="behavior"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Comportamiento de NIVO</b><small>NIVO usa primero reglas y conocimiento local. Si habilitas IA externa, OpenAI entra únicamente como segunda fase cuando el motor interno no resuelve.</small></div></div><div class="settings-grid">
 <div class="field"><label>Asistente habilitado</label><label class="switch-line nivo-master-switch"><input name="enabled" type="checkbox" <?=($botcfg['enabled']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text"><?=($botcfg['enabled']??0)?'NIVO activo':'Activar NIVO'?></span></label><small class="field-help">Al activarlo, NIVO puede responder, sugerir borradores y automatizar según reglas y conocimiento aprobados.</small></div>
 <div class="field"><label>Nombre visible</label><input name="name" maxlength="100" value="<?=htmlspecialchars($botcfg['name']??'NIVO')?>"><small class="field-help">Nombre que verán agentes y clientes cuando corresponda.</small></div>
 <div class="field"><label>Modo operativo</label><select name="mode" class="select2"><option value="rules" <?=($botcfg['mode']??'hybrid')==='rules'?'selected':''?>>Reglas y conocimiento local</option><option value="hybrid" <?=($botcfg['mode']??'hybrid')==='hybrid'?'selected':''?>>Híbrido · local primero + respaldo externo</option></select><small class="field-help">Los datos solo salen a OpenAI cuando el respaldo externo está conectado, permitido por el plan y activado para el canal.</small></div>
 <div class="field"><label>Confianza mínima</label><select name="min_confidence" class="select2"><option value="low" <?=$minConfidence==='low'?'selected':''?>>Baja</option><option value="medium" <?=$minConfidence==='medium'?'selected':''?>>Media · recomendado</option><option value="high" <?=$minConfidence==='high'?'selected':''?>>Alta</option></select><small class="field-help">Si la coincidencia no alcanza este nivel, NIVO evita improvisar.</small></div>
 <div class="field"><label>Transferencia automática</label><label class="switch-line"><input name="auto_handoff" type="checkbox" <?=$autoHandoff?'checked':''?>><span></span> Pasar a humano si no sabe</label><small class="field-help">Evita respuestas inseguras cuando falta información autorizada.</small></div>
 <div class="field"><label>Aprendizaje desde conversaciones</label><select name="learn_mode" class="select2"><option value="off" <?=$learnMode==='off'?'selected':''?>>Desactivado</option><option value="review" <?=$learnMode==='review'?'selected':''?>>Solo con revisión humana</option></select><small class="field-help">NIVO nunca aprenderá automáticamente de una conversación sin aprobación.</small></div>
 <div class="field"><label>Tono de respuesta</label><select name="tone" class="select2"><option value="professional" <?=$tone==='professional'?'selected':''?>>Profesional</option><option value="friendly" <?=$tone==='friendly'?'selected':''?>>Cercano y amable</option><option value="concise" <?=$tone==='concise'?'selected':''?>>Breve y directo</option></select><small class="field-help">Se aplica al motor local sin alterar respuestas exactas de reglas.</small></div>
 <div class="field"><label>Longitud máxima</label><input name="max_response_length" type="number" min="180" max="1500" value="<?=$maxResponse?>"><small class="field-help">Máximo aproximado de caracteres al responder desde conocimiento.</small></div>
 <div class="field full"><label>Palabras para solicitar agente</label><input name="handoff_keywords" maxlength="500" value="<?=htmlspecialchars($handoffKeywords)?>"><small class="field-help">Separadas por coma. Ej.: agente, asesor, humano.</small></div>
 <div class="field full nivo-omnichannel-box">
  <div class="nivo-omnichannel-head"><div><b><i class="fa-solid fa-diagram-project"></i> NIVO IA omnicanal</b><small>20+ controles para que el mismo asistente trabaje con Web Chat y con cada canal que ingrese a ZYNKO.</small></div><span class="status-badge connected">Motor local · sin costo externo</span></div>
  <div class="nivo-channel-pills"><?php foreach(['webchat'=>'NIVO Web Chat','whatsapp'=>'WhatsApp','messenger'=>'Messenger','instagram'=>'Instagram','telegram'=>'Telegram','email'=>'Correo','api'=>'API / Webhooks'] as $code=>$label):?><label><input type="checkbox" name="nivo_channels[]" value="<?=$code?>" <?=in_array($code,$nivoChannels,true)?'checked':''?>><span><?=htmlspecialchars($label)?></span></label><?php endforeach?></div>
  <div class="nivo-policy-grid">
   <label class="switch-line"><input name="identity_enabled" type="checkbox" <?=!array_key_exists('identity_enabled',$policy)||!empty($policy['identity_enabled'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Presentarse como NIVO de la empresa</span></label>
   <label class="switch-line"><input name="personalized_greeting" type="checkbox" <?=!array_key_exists('personalized_greeting',$policy)||!empty($policy['personalized_greeting'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Saludar usando el nombre del cliente</span></label>
   <label class="switch-line"><input name="language_auto" type="checkbox" <?=!array_key_exists('language_auto',$policy)||!empty($policy['language_auto'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Detectar saludo ES / EN</span></label>
   <label class="switch-line"><input name="duplicate_guard" type="checkbox" <?=!array_key_exists('duplicate_guard',$policy)||!empty($policy['duplicate_guard'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Evitar respuestas duplicadas</span></label>
   <label class="switch-line"><input name="pause_when_assigned" type="checkbox" <?=!array_key_exists('pause_when_assigned',$policy)||!empty($policy['pause_when_assigned'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Pausar IA cuando atiende un humano</span></label>
   <label class="switch-line"><input name="channel_context" type="checkbox" <?=!array_key_exists('channel_context',$policy)||!empty($policy['channel_context'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Conservar contexto del canal actual</span></label>
   <label class="switch-line"><input name="safe_unknown" type="checkbox" <?=!array_key_exists('safe_unknown',$policy)||!empty($policy['safe_unknown'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">No inventar cuando no conoce la respuesta</span></label>
   <label class="switch-line"><input name="business_hours_only" type="checkbox" <?=!empty($policy['business_hours_only'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Automatizar solo dentro del horario</span></label>
   <label class="switch-line"><input name="sensitive_data_guard" type="checkbox" <?=!array_key_exists('sensitive_data_guard',$policy)||!empty($policy['sensitive_data_guard'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Proteger datos sensibles</span></label>
   <label class="switch-line"><input name="safe_links_only" type="checkbox" <?=!array_key_exists('safe_links_only',$policy)||!empty($policy['safe_links_only'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Bloquear enlaces inseguros</span></label>
  </div>
  <div class="nivo-policy-numbers">
   <div class="field"><label>Mensajes de contexto</label><input name="context_messages" type="number" min="0" max="20" value="<?=htmlspecialchars((string)($policy['context_messages']??6))?>"><small class="field-help">Últimos mensajes que NIVO considera como referencia operativa.</small></div>
   <div class="field"><label>Fallos antes de transferir</label><input name="unknown_before_handoff" type="number" min="1" max="5" value="<?=htmlspecialchars((string)($policy['unknown_before_handoff']??1))?>"></div>
   <div class="field"><label>Máximo respuestas automáticas</label><input name="max_auto_replies" type="number" min="1" max="100" value="<?=htmlspecialchars((string)($policy['max_auto_replies']??25))?>"></div>
   <div class="field"><label>Pausa entre respuestas</label><div class="input-suffix"><input name="cooldown_seconds" type="number" min="0" max="30" value="<?=htmlspecialchars((string)($policy['cooldown_seconds']??1))?>"><span>seg</span></div></div>
   <div class="field"><label>Máximo de caracteres por pregunta</label><input name="max_input_chars" type="number" min="200" max="10000" value="<?=htmlspecialchars((string)($policy['max_input_chars']??3000))?>"></div>
   <div class="field"><label>Palabras bloqueadas</label><input name="blocked_keywords" maxlength="1200" value="<?=htmlspecialchars((string)($policy['blocked_keywords']??''))?>" placeholder="secreto, contraseña, tarjeta completa"></div>
  </div>
  <small class="field-help"><i class="fa-solid fa-circle-info"></i> La automatización funciona en los canales seleccionados cuando el mensaje entra a una conversación de ZYNKO. Web Chat ya usa este motor directamente; los demás conectores lo reutilizan al recibir mensajes.</small>
 </div>
 <div class="field full nivo-hours">
  <div class="nivo-hours-head">
   <div class="nivo-hours-copy"><strong>Horario de atención humana</strong><small>Define cuándo NIVO puede transferir una conversación a tu equipo.</small></div>
   <label class="switch-line nivo-hours-switch"><input name="business_hours_enabled" type="checkbox" <?=$hoursEnabled?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Aplicar horario para transferencias</span></label>
  </div>
  <div class="nivo-hours-body">
   <div class="hours-row"><div class="hours-control"><label>Desde</label><input type="time" name="business_start" value="<?=htmlspecialchars($businessStart)?>"></div><span class="hours-separator">a</span><div class="hours-control"><label>Hasta</label><input type="time" name="business_end" value="<?=htmlspecialchars($businessEnd)?>"></div></div>
   <div class="day-pills"><?php foreach([1=>'Lun',2=>'Mar',3=>'Mié',4=>'Jue',5=>'Vie',6=>'Sáb',7=>'Dom'] as $n=>$day):?><label><input type="checkbox" name="business_days[]" value="<?=$n?>" <?=in_array($n,$businessDays)?'checked':''?>><span><?=$day?></span></label><?php endforeach?></div>
   <div class="nivo-hours-message"><label>Mensaje fuera de horario</label><textarea name="outside_message" maxlength="1000" rows="3"><?=htmlspecialchars($outsideMessage)?></textarea><small class="field-help">Fuera de horario NIVO informa al visitante y deja la conversación pendiente para atención humana.</small></div><div class="nivo-special-dates"><div class="nivo-special-head"><div><strong>Fechas y horarios especiales</strong><small>Feriados, cierres, jornadas especiales o fechas con horario diferente.</small></div><button type="button" class="soft" id="addSpecialDate"><i class="fa-solid fa-calendar-plus"></i> Agregar fecha</button></div><div id="specialDatesList"><?php foreach($specialDates as $sd):?><div class="special-date-row"><input type="date" name="special_date[]" value="<?=htmlspecialchars($sd['date']??'')?>" aria-label="Fecha especial"><select name="special_type[]"><option value="closed" <?=($sd['type']??'closed')==='closed'?'selected':''?>>Cerrado todo el día</option><option value="hours" <?=($sd['type']??'')==='hours'?'selected':''?>>Horario especial</option></select><input type="time" name="special_start[]" value="<?=htmlspecialchars($sd['start']??'')?>" aria-label="Inicio"><input type="time" name="special_end[]" value="<?=htmlspecialchars($sd['end']??'')?>" aria-label="Fin"><button type="button" class="icon-btn danger remove-special-date" title="Quitar fecha"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div></div>
  </div>
 </div>
 <div class="field full"><label>Instrucciones del asistente</label><textarea name="system_prompt" maxlength="5000"><?=htmlspecialchars($botcfg['system_prompt']??'Responde únicamente con información autorizada de la empresa. Si no tienes suficiente información, transfiere a un agente humano.')?></textarea><small class="field-help">Define tono, límites y comportamiento. Estas instrucciones no reemplazan las reglas ni la base de conocimiento.</small></div>
 <div class="field full" id="handoff"><label>Mensaje de transferencia humana</label><textarea name="fallback_message" maxlength="1000"><?=htmlspecialchars($botcfg['fallback_message']??'No tengo información suficiente para responder con seguridad. Te comunicaré con un agente para continuar.')?></textarea></div>
 </div><div class="form-actions"><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar configuración</button></div></section></form>

<section class="panel nivo-section" id="solutions"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Centro de conocimiento · Soluciones</b><small>Separa lo que NIVO sabe por producto. CAMI cubre el entorno médico/laboratorio; IZZY la operación empresarial general. Puedes agregar futuras soluciones sin reprogramar NIVO.</small></div><button type="button" class="soft" data-open="solutionModal"><i class="fa-solid fa-plus"></i> Nueva solución</button></div>
<div class="solution-cards"><?php foreach($solutions as $sol):?><article class="solution-card"><span class="solution-icon"><i class="fa-solid fa-cube"></i></span><div><b><?=htmlspecialchars($sol['name'])?></b><p><?=htmlspecialchars($sol['description']??'')?></p><small><?=count(array_filter($modules,fn($m)=>(int)$m['solution_id']===(int)$sol['id']))?> módulos · <?=count(array_filter($sources,fn($k)=>(int)($k['solution_id']??0)===(int)$sol['id'] && ($k['approval_status']??'approved')==='approved'))?> fuentes publicadas</small></div><button type="button" class="icon-btn add-module" data-solution="<?=$sol['id']?>" data-name="<?=htmlspecialchars($sol['name'],ENT_QUOTES)?>" title="Agregar módulo"><i class="fa-solid fa-folder-plus"></i></button></article><?php endforeach?></div></section>
<section class="panel nivo-section nivo-web-knowledge" id="knowledge-sites"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Fuentes web de conocimiento</b><small>Autoriza los sitios que NIVO puede leer. No son los mismos dominios donde instalas el widget: aquí decides de qué páginas puede aprender.</small></div><button type="button" class="soft" data-open="knowledgeSiteModal"><i class="fa-solid fa-plus"></i> Agregar sitio</button></div>
<div class="nivo-web-source-info"><span><i class="fa-solid fa-shield-halved"></i><b>Control total</b><small>Solo se consulta contenido público de los dominios que tú agregues.</small></span><span><i class="fa-solid fa-arrows-rotate"></i><b>Sincronizable</b><small>Puedes actualizar manualmente o programar refresco periódico.</small></span><span><i class="fa-solid fa-brain"></i><b>Conocimiento aprobado</b><small>Las páginas sincronizadas entran listas para responder y quedan trazables por URL.</small></span></div>
<?php if(!$webSources):?><div class="empty-compact"><i class="fa-solid fa-globe"></i><b>Aún no hay sitios de conocimiento</b><span>Agrega por ejemplo tu sitio corporativo, IZZY, CAMI o cualquier dominio público autorizado por tu empresa.</span></div><?php else:?><div class="nivo-web-source-list"><?php foreach($webSources as $ws):$wsJson=htmlspecialchars(json_encode($ws,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8');$status=$ws['sync_status']??'never';?><article class="nivo-web-source-card"><span class="nivo-web-source-icon"><i class="fa-solid fa-globe"></i></span><div class="nivo-web-source-main"><div class="nivo-web-source-title"><b><?=htmlspecialchars($ws['name'])?></b><span class="status-badge <?=$status==='ready'?'connected':($status==='error'?'inactive':'muted')?>"><?=$status==='ready'?'Sincronizado':($status==='error'?'Error':($status==='syncing'?'Sincronizando':'Sin sincronizar'))?></span></div><a href="<?=htmlspecialchars($ws['base_url'],ENT_QUOTES,'UTF-8')?>" target="_blank" rel="noopener noreferrer"><?=htmlspecialchars($ws['base_url'])?> <i class="fa-solid fa-arrow-up-right-from-square"></i></a><small><?=$ws['crawl_scope']==='domain'?'Dominio completo':'Solo esta página'?> · <?=intval($ws['pages_count'])?> página(s) aprendidas · máximo <?=intval($ws['max_pages'])?> · <?=$ws['auto_sync']?'Auto cada '.intval($ws['refresh_hours']).' h':'Actualización manual'?></small><?php if(!empty($ws['last_synced_at'])):?><small>Última sincronización: <?=htmlspecialchars($ws['last_synced_at'])?></small><?php endif?><?php if(!empty($ws['last_error'])):?><small class="nivo-web-source-error"><i class="fa-solid fa-triangle-exclamation"></i> <?=htmlspecialchars($ws['last_error'])?></small><?php endif?></div><div class="nivo-web-source-actions"><button type="button" class="icon-btn knowledge-site-sync" data-id="<?=$ws['id']?>" title="Sincronizar ahora"><i class="fa-solid fa-rotate"></i></button><button type="button" class="icon-btn knowledge-site-edit" data-site='<?=$wsJson?>' title="Editar fuente"><i class="fa-solid fa-pen"></i></button><button type="button" class="icon-btn danger knowledge-site-delete" data-id="<?=$ws['id']?>" title="Eliminar fuente"><i class="fa-solid fa-trash"></i></button></div></article><?php endforeach?></div><?php endif?>
<div class="nivo-web-source-footer"><i class="fa-solid fa-circle-info"></i><span><b>Importante:</b> NIVO no navega Internet libremente al responder. Solo usa el contenido que tú sincronizaste desde estas fuentes autorizadas, además de reglas, textos y archivos aprobados.</span></div></section>
<section class="grid2 nivo-grid">
 <article class="panel nivo-section" id="rules"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Reglas de respuesta</b><small>Las reglas tienen prioridad sobre el conocimiento general y son ideales para horarios, políticas y respuestas exactas.</small></div><button type="button" class="soft" data-open="ruleModal"><i class="fa-solid fa-plus"></i> Nueva regla</button></div>
 <?php if(!$rules):?><div class="empty-compact"><i class="fa-solid fa-diagram-project"></i><b>Sin reglas</b><span>Crea reglas para respuestas que deben ser exactas.</span></div><?php else:?><div class="nivo-list"><?php foreach($rules as $r):$ruleJson=htmlspecialchars(json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8');?><div class="nivo-list-row"><div><b><?=htmlspecialchars($r['name'])?></b><small><?=htmlspecialchars($r['keywords'])?> · Prioridad <?=$r['priority']?></small><span><?=htmlspecialchars(mb_strimwidth($r['response'],0,140,'…'))?></span></div><span class="status-badge <?=!$r['active']?'muted':''?>"><?=$r['active']?'Activa':'Inactiva'?></span><div class="nivo-row-actions"><button type="button" class="icon-btn rule-edit" data-rule='<?=$ruleJson?>' title="Editar regla"><i class="fa-solid fa-pen"></i></button><button type="button" class="icon-btn danger rule-delete" data-id="<?=$r['id']?>" title="Eliminar regla"><i class="fa-solid fa-trash"></i></button></div></div><?php endforeach?></div><?php endif?>
 </article>
 <article class="panel nivo-section" id="knowledge"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Base de conocimiento</b><small>Contenido aprobado que NIVO puede consultar.</small></div><button type="button" class="soft" data-open="knowledgeModal"><i class="fa-solid fa-plus"></i> Agregar</button></div>
 <?php if(!$sources):?><div class="empty-compact"><i class="fa-solid fa-book-open"></i><b>Sin conocimiento todavía</b><span>Agrega FAQs, productos, procesos o políticas.</span></div><?php else:?><div class="nivo-list"><?php foreach($sources as $src):?><div class="nivo-list-row"><div><b><?=htmlspecialchars($src['name'])?></b><small><?=htmlspecialchars($src['solution_name']?:'General')?><?=!empty($src['module_name'])?' · '.htmlspecialchars($src['module_name']):''?> · <?=htmlspecialchars(strtoupper($src['source_type']))?></small><span class="knowledge-state <?=($src['approval_status']??'approved')==='approved'?'approved':'pending'?>"><?=($src['approval_status']??'approved')==='approved'?'Publicado':'Pendiente de revisión'?></span></div><?php if(($src['approval_status']??'approved')!=='approved'):?><button type="button" class="icon-btn knowledge-approve" data-id="<?=$src['id']?>" title="Aprobar y publicar"><i class="fa-solid fa-check"></i></button><?php endif?><button type="button" class="icon-btn knowledge-delete" data-id="<?=$src['id']?>" title="Eliminar fuente"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div><?php endif?>
 <div class="knowledge-import-meta"><select id="knowledgeFileSolution" class="select2"><option value="0">Conocimiento general</option><?php foreach($solutions as $sol):?><option value="<?=$sol['id']?>"><?=htmlspecialchars($sol['name'])?></option><?php endforeach?></select><select id="knowledgeFileModule" class="select2"><option value="0">Sin módulo específico</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" data-solution="<?=$m['solution_id']?>"><?=htmlspecialchars($m['solution_name'].' · '.$m['name'])?></option><?php endforeach?></select></div><label class="upload-zone nivo-upload" tabindex="0"><i class="fa-solid fa-file-arrow-up"></i><b>Importar archivo de conocimiento</b><small>TXT, MD, CSV o JSON · máximo 2 MB · entra como pendiente para revisión</small><input id="knowledgeFile" type="file" accept=".txt,.md,.csv,.json,text/plain,text/csv,application/json" hidden></label>
 </article>
</section>
<?php if(isPlatformOwner()):?><section class="panel nivo-section" id="demo-agents"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Agentes de demostración</b><small>Solo para tu empresa principal. Permite probar transferencias con nombres alternos cuando todavía no tienes suficientes usuarios reales.</small></div></div><form id="aliasForm" class="inline-form"><input type="hidden" name="action" value="nivo_alias_add"><div class="field"><label>Nombre visible</label><input name="display_name" required maxlength="160" placeholder="Ej. Juan Velásquez"></div><button class="primary"><i class="fa-solid fa-user-plus"></i> Agregar agente</button></form><div class="nivo-list"><?php foreach($aliases as $a):?><div class="nivo-list-row"><div><b><?=htmlspecialchars($a['display_name'])?></b><small>Agente de demostración</small></div><button type="button" class="icon-btn alias-delete" data-id="<?=$a['id']?>"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div></section><?php endif?>
<section class="panel nivo-section" id="external-ai">
 <div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>IA externa · segunda fase</b><small>NIVO siempre intenta primero reglas y conocimiento interno. Solo si no puede responder, usa OpenAI cuando esté conectado, habilitado y permitido por tu plan.</small></div><span class="status-badge <?= $tenantExternalEnabled?'connected':'inactive' ?>"><i class="fa-solid fa-circle"></i> <?= $tenantExternalEnabled?'Fallback activo':'Fallback inactivo' ?></span></div>
 <div class="nivo-external-flow"><span><i class="fa-solid fa-brain"></i><b>1. NIVO interno</b><small>Reglas + conocimiento aprobado.</small></span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-cloud"></i><b>2. OpenAI</b><small>Solo cuando NIVO interno no resuelve.</small></span><i class="fa-solid fa-arrow-right"></i><span><i class="fa-solid fa-headset"></i><b>3. Humano</b><small>Si aún no hay respuesta segura.</small></span></div>
 <?php if(isPlatformOwner()):?>
 <div class="ai-admin-grid">
  <article class="ai-status-card"><span><i class="fa-solid fa-plug-circle-bolt"></i></span><div><small>CONEXIÓN</small><b><?= $openAiConnected?'API Key configurada':'Sin API Key' ?></b><em><?=htmlspecialchars($openAiGlobal['last_test_message']??'Guarda la clave y prueba la conexión.')?></em></div></article>
  <article class="ai-status-card"><span><i class="fa-solid fa-microchip"></i></span><div><small>MODELO</small><b><?=htmlspecialchars($openAiGlobal['model']??'gpt-6-luna')?></b><em>Proveedor: OpenAI</em></div></article>
  <article class="ai-status-card"><span><i class="fa-solid fa-coins"></i></span><div><small>TOKENS ZYNKO · MES</small><b><?=number_format($monthTokens)?></b><em><?=number_format((int)($openAiUsage['requests']??0))?> solicitudes</em></div></article>
  <article class="ai-status-card"><span><i class="fa-solid fa-dollar-sign"></i></span><div><small>COSTO ESTIMADO ZYNKO</small><b>USD <?=number_format($localCost,4)?></b><em>Calculado con tus tarifas configuradas</em></div></article>
  <article class="ai-status-card"><span><i class="fa-solid fa-building-columns"></i></span><div><small>COSTO REAL ORGANIZACIÓN</small><b><?=($openAiGlobal['remote_cost_refreshed_at']??null)?'USD '.number_format($remoteCost,4):'Sin consultar'?></b><em><?=!empty($openAiGlobal['admin_key_configured'])?'Usa “Actualizar consumo”':'Requiere Admin API Key'?></em></div></article>
  <article class="ai-status-card"><span><i class="fa-solid fa-wallet"></i></span><div><small>SALDO OPERATIVO</small><b><?= $remaining===null?'Sin presupuesto':'USD '.number_format($remaining,4) ?></b><em>Presupuesto configurado menos consumo; no es el saldo prepago de OpenAI.</em></div></article>
 </div>
 <form id="openAiProviderForm" class="ai-provider-form"><input type="hidden" name="action" value="ai_provider_save"><div class="settings-grid">
  <div class="field full nivo-provider-toggle-field"><label class="switch-line nivo-provider-toggle"><input type="checkbox" name="enabled" <?=$openAiEnabled?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text"><b>Permitir OpenAI como segunda fase de NIVO</b><small>Apagado = ZYNKO trabaja únicamente con NIVO interno.</small></span></label></div>
  <div class="field"><label>API Key de OpenAI</label><input type="password" name="api_key" autocomplete="new-password" placeholder="<?=!empty($openAiGlobal['api_key_configured'])?'Configurada · dejar vacío para conservar':'sk-... / clave del proyecto'?>"><small class="field-help">Se cifra con APP_KEY y nunca se muestra completa.</small></div>
  <div class="field"><label>Admin API Key · opcional</label><input type="password" name="admin_key" autocomplete="new-password" placeholder="<?=!empty($openAiGlobal['admin_key_configured'])?'Configurada · dejar vacío para conservar':'Solo para consultar costos de organización'?>"><small class="field-help">No se usa para responder chats.</small></div>
  <div class="field"><label>Modelo</label><input name="model" value="<?=htmlspecialchars($openAiGlobal['model']??'gpt-6-luna')?>" placeholder="gpt-6-luna"></div>
  <div class="field"><label>Máximo de tokens por respuesta</label><input type="number" name="max_output_tokens" min="100" max="4000" value="<?=htmlspecialchars((string)($openAiGlobal['max_output_tokens']??700))?>"></div>
  <div class="field"><label>Presupuesto mensual · USD</label><input type="number" name="monthly_budget_usd" min="0" step="0.01" value="<?=htmlspecialchars((string)($openAiGlobal['monthly_budget_usd']??''))?>" placeholder="0 = sin tope global"><small class="field-help">NIVO bloquea nuevas llamadas externas al alcanzar este presupuesto estimado.</small></div>
  <div class="field"><label>Entrada / 1M tokens · USD</label><input type="number" name="input_cost_per_million" min="0" step="0.000001" value="<?=htmlspecialchars((string)($openAiGlobal['input_cost_per_million']??0.05))?>"></div>
  <div class="field"><label>Entrada caché / 1M · USD</label><input type="number" name="cached_input_cost_per_million" min="0" step="0.000001" value="<?=htmlspecialchars((string)($openAiGlobal['cached_input_cost_per_million']??0.005))?>"></div>
  <div class="field"><label>Salida / 1M tokens · USD</label><input type="number" name="output_cost_per_million" min="0" step="0.000001" value="<?=htmlspecialchars((string)($openAiGlobal['output_cost_per_million']??0.25))?>"></div>
 </div><div class="form-actions ai-provider-actions"><button type="button" class="soft" id="openAiTestBtn"><i class="fa-solid fa-plug-circle-check"></i> Probar conexión</button><button type="button" class="soft" id="openAiUsageBtn" <?=empty($openAiGlobal['admin_key_configured'])?'disabled':''?>><i class="fa-solid fa-rotate"></i> Actualizar consumo</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar OpenAI</button></div></form>
 <?php endif?>
 <form id="tenantAiForm" class="tenant-ai-form"><input type="hidden" name="action" value="tenant_ai_save"><div class="tenant-ai-entitlement <?=!$tenantAiAllowed?'is-locked':''?>"><div><span class="tenant-ai-icon"><i class="fa-solid fa-wand-magic-sparkles"></i></span><div><b>OpenAI como respaldo de NIVO</b><small><?= $tenantAiAllowed?'Tu plan permite IA externa. Actívala únicamente cuando quieras usarla.':'Tu plan actual no incluye IA externa. NIVO interno continúa funcionando normalmente.' ?></small></div></div><label class="switch-line"><input type="checkbox" name="enabled" <?=!empty($tenantAi['enabled'])?'checked':''?> <?=!$tenantAiSwitchAllowed?'disabled':''?>><span class="switch-control"></span><span class="switch-label-text">Activar segunda fase</span></label></div>
 <div class="tenant-ai-usage"><span><small>Uso externo este mes</small><b><?=number_format($monthTokens)?> tokens</b></span><span><small>Límite del plan</small><b><?=!empty($zynkoPlanContext['external_ai_monthly_tokens'])?number_format((int)$zynkoPlanContext['external_ai_monthly_tokens']).' tokens':'Sin límite del plan'?></b></span><span><small>Proveedor</small><b><?= $openAiConnected&&$openAiEnabled?'OpenAI conectado':'No disponible' ?></b></span></div>
 <div class="ai-channel-grid"><label>Canales donde puede usarse OpenAI</label><div><?php foreach(['webchat'=>'NIVO Web Chat','whatsapp'=>'WhatsApp','messenger'=>'Messenger','instagram'=>'Instagram','telegram'=>'Telegram','email'=>'Correo','api'=>'API/Webhooks'] as $code=>$label):$planChannelOk=!$tenantAiPlanChannels||in_array($code,$tenantAiPlanChannels,true)||!empty($zynkoPlanContext['unrestricted']);?><label class="ai-channel-option <?=!$planChannelOk?'is-disabled':''?>"><input type="checkbox" name="channels[]" value="<?=$code?>" <?=in_array($code,$tenantAiChannels,true)?'checked':''?> <?=(!$tenantAiAllowed||!$planChannelOk)?'disabled':''?>><span><b><?=htmlspecialchars($label)?></b><small><?= $planChannelOk?'Disponible':'No incluido en plan' ?></small></span></label><?php endforeach?></div></div>
 <div class="settings-grid nivo-premium-policy">
 <div class="field full"><label>Orígenes web permitidos para NIVO IA</label><textarea name="allowed_origins" rows="3" placeholder="https://cliente.com
https://app.cliente.com"><?=htmlspecialchars(implode("\n",$tenantAi['allowed_origins']??[]))?></textarea><small class="field-help">Vacío = solo se aplican los permisos normales de la API/canal. Si agregas dominios, NIVO IA vía navegador se limita a ellos.</small></div>
 <div class="field"><label>Límite IA por minuto</label><input type="number" name="max_requests_per_minute" min="5" max="1000" value="<?=htmlspecialchars((string)($tenantAi['max_requests_per_minute']??60))?>"></div>
 <div class="field"><label>Privacidad</label><label class="switch-line"><input type="checkbox" name="redact_sensitive" <?=!array_key_exists('redact_sensitive',$tenantAi)||!empty($tenantAi['redact_sensitive'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Ocultar datos sensibles antes de IA externa</span></label></div>
 <div class="field"><label>Fuentes seguras</label><label class="switch-line"><input type="checkbox" name="require_approved_knowledge" <?=!array_key_exists('require_approved_knowledge',$tenantAi)||!empty($tenantAi['require_approved_knowledge'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Usar solo conocimiento aprobado</span></label></div>
 <div class="field"><label>Auditoría</label><label class="switch-line"><input type="checkbox" name="log_decisions" <?=!array_key_exists('log_decisions',$tenantAi)||!empty($tenantAi['log_decisions'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Registrar decisiones y consumo</span></label></div>
</div>
<div class="form-actions"><span class="field-help"><i class="fa-solid fa-shield-halved"></i> El cliente nunca ve tu API Key. NIVO local se ejecuta primero siempre.</span><button class="primary" <?=!$tenantAiSwitchAllowed?'disabled':''?>><i class="fa-solid fa-floppy-disk"></i> Guardar uso de IA</button></div></form>
</section>

<section class="panel nivo-section" id="playground"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-robot"></i></span><div><b>Probar NIVO antes de usarlo</b><small>Simula una pregunta. Verás la respuesta, confianza y fuente sin enviar nada al cliente.</small></div></div><div class="nivo-playground nivo-playground-stacked"><div class="field nivo-playground-solution"><label>Solución a probar</label><select id="nivoTestSolution"><option value="0">Automático / conocimiento general</option><?php foreach($solutions as $sol):?><option value="<?=$sol['id']?>"><?=htmlspecialchars($sol['name'])?></option><?php endforeach?></select></div><div class="field nivo-playground-message"><label>Mensaje de prueba</label><textarea id="nivoTestQuery" rows="5" placeholder="Ej. ¿Cuál es el horario de atención?"></textarea></div><div class="nivo-test-result" id="nivoTestResult"><i class="fa-solid fa-flask"></i><div><b>Esperando una prueba</b><small>La respuesta aparecerá aquí.</small></div></div></div><div class="form-actions"><button type="button" class="primary" id="nivoTestBtn"><i class="fa-solid fa-play"></i> Probar NIVO</button></div></section>

<div class="modal-shell" id="knowledgeSiteModal"><div class="modal-card nivo-website-modal"><div class="modal-head"><div><b id="knowledgeSiteModalTitle">Agregar fuente web</b><small>Indica exactamente qué sitio puede leer NIVO. El dominio puede cambiar cuando quieras.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="knowledgeSiteForm"><input type="hidden" name="action" value="knowledge_site_add"><input type="hidden" name="website_id" value="0"><div class="settings-grid"><div class="field"><label>Nombre de la fuente</label><input name="name" required maxlength="180" placeholder="Ej. Sitio ES MULTISERVICIOS"></div><div class="field"><label>URL base</label><input name="base_url" required type="url" maxlength="500" placeholder="https://esmultiservicios.com"></div><div class="field"><label>Alcance</label><select name="crawl_scope" class="select2"><option value="domain">Todo el dominio público</option><option value="page">Solo esta página</option></select></div><div class="field"><label>Máximo de páginas</label><input name="max_pages" type="number" min="1" max="30" value="10"></div><div class="field"><label>Actualizar automáticamente</label><label class="switch-line"><input name="auto_sync" type="checkbox"><span class="switch-control"></span><span class="switch-label-text">Sincronización automática</span></label></div><div class="field"><label>Frecuencia</label><div class="input-suffix"><input name="refresh_hours" type="number" min="1" max="720" value="24"><span>horas</span></div></div><div class="field full"><label>Rutas excluidas</label><textarea name="exclude_paths" rows="3" placeholder="/admin, /login, /checkout, /cart, /account">/admin, /login, /checkout, /cart, /account</textarea><small class="field-help">Separadas por coma o línea. NIVO nunca necesita leer paneles privados.</small></div><div class="field full"><label class="switch-line"><input name="active" type="checkbox" checked><span class="switch-control"></span><span class="switch-label-text">Fuente activa</span></label></div><div class="field full" id="knowledgeSiteSyncNowField"><label class="switch-line"><input name="sync_now" type="checkbox" checked><span class="switch-control"></span><span class="switch-label-text">Sincronizar inmediatamente al crear</span></label></div></div><div class="nivo-web-source-safety"><i class="fa-solid fa-shield-halved"></i><span>ZYNKO bloquea redes privadas/reservadas en producción para evitar accesos internos no autorizados. En entorno local se permiten dominios <b>.test</b>.</span></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-globe"></i> Guardar fuente</button></div></form></div></div>
<div class="modal-shell" id="knowledgeModal"><div class="modal-card"><div class="modal-head"><div><b>Enseñar a NIVO</b><small>Solo agrega información que la empresa autoriza utilizar.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="knowledgeForm"><input type="hidden" name="action" value="knowledge_add"><div class="settings-grid"><div class="field"><label>Solución</label><select name="solution_id" class="knowledge-solution select2"><option value="0">General</option><?php foreach($solutions as $sol):?><option value="<?=$sol['id']?>"><?=htmlspecialchars($sol['name'])?></option><?php endforeach?></select></div><div class="field"><label>Módulo</label><select name="module_id" class="knowledge-module select2"><option value="0">Sin módulo específico</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" data-solution="<?=$m['solution_id']?>"><?=htmlspecialchars($m['solution_name'].' · '.$m['name'])?></option><?php endforeach?></select></div></div><div class="field"><label>Nombre de la fuente</label><input name="name" required maxlength="180" placeholder="Ej. Política de devoluciones"></div><div class="field"><label>Contenido autorizado</label><textarea name="content" required rows="9" maxlength="50000" placeholder="Escribe o pega la información..."></textarea></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-brain"></i> Guardar y enseñar</button></div></form></div></div>
<div class="modal-shell" id="solutionModal"><div class="modal-card"><div class="modal-head"><div class="modal-title-with-icon"><span class="modal-title-icon"><i class="fa-solid fa-layer-group"></i></span><span class="modal-title-copy"><b>Nueva solución para NIVO</b><small>Ej. un ERP, sistema clínico, e-commerce o cualquier producto que tu empresa soporte.</small></span></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="solutionForm"><input type="hidden" name="action" value="nivo_solution_add"><div class="field"><label>Nombre</label><input name="name" required maxlength="120" placeholder="Ej. Mi ERP"></div><div class="field"><label>Qué cubre esta solución</label><textarea name="description" rows="4" maxlength="700" placeholder="Describe el alcance para mantener el conocimiento separado y claro."></textarea></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-plus"></i> Crear solución</button></div></form></div></div>
<div class="modal-shell" id="moduleModal"><div class="modal-card"><div class="modal-head"><div><b>Nuevo módulo</b><small id="moduleSolutionName">Organiza las funcionalidades dentro de la solución.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="moduleForm"><input type="hidden" name="action" value="nivo_module_add"><input type="hidden" name="solution_id" id="moduleSolutionId"><div class="field"><label>Nombre del módulo</label><input name="name" required maxlength="120" placeholder="Ej. Facturación"></div><div class="field"><label>Descripción</label><textarea name="description" rows="3" maxlength="500"></textarea></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-folder-plus"></i> Agregar módulo</button></div></form></div></div>
<div class="modal-shell" id="ruleModal"><div class="modal-card"><div class="modal-head"><div class="modal-title-with-icon"><span class="modal-title-icon"><i class="fa-solid fa-diagram-project"></i></span><span class="modal-title-copy"><b id="ruleModalTitle">Nueva regla de NIVO</b><small id="ruleModalSubtitle">Usa palabras o frases separadas por coma. Si coinciden, NIVO responde exactamente lo configurado.</small></span></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="ruleForm"><input type="hidden" name="action" value="nivo_rule_add"><input type="hidden" name="rule_id" value="0"><div class="settings-grid"><div class="field"><label>Nombre</label><input name="name" required maxlength="160" placeholder="Ej. Horario"></div><div class="field"><label>Prioridad</label><input name="priority" type="number" min="1" max="999" value="100"></div><div class="field full"><label>Palabras o frases clave</label><input name="keywords" required maxlength="500" placeholder="horario, a qué hora abren, atención"></div><div class="field full"><label>Respuesta exacta</label><textarea name="response" required maxlength="5000" rows="6"></textarea></div><div class="field full rule-active-field"><label class="switch-line rule-active-switch"><input name="active" type="checkbox" checked><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Regla activa</span></label></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary" id="ruleSubmitBtn"><i class="fa-solid fa-floppy-disk"></i> Guardar regla</button></div></form></div></div>
<?php require __DIR__.'/partials/bottom.php'; ?>

<script>document.addEventListener('DOMContentLoaded',()=>{const list=document.getElementById('specialDatesList'),add=document.getElementById('addSpecialDate');if(!list||!add)return;const row=()=>{const d=document.createElement('div');d.className='special-date-row';d.innerHTML='<input type="date" name="special_date[]" aria-label="Fecha especial"><select name="special_type[]"><option value="closed">Cerrado todo el día</option><option value="hours">Horario especial</option></select><input type="time" name="special_start[]" aria-label="Inicio"><input type="time" name="special_end[]" aria-label="Fin"><button type="button" class="icon-btn danger remove-special-date" title="Quitar fecha"><i class="fa-solid fa-trash"></i></button>';return d};add.addEventListener('click',()=>list.appendChild(row()));list.addEventListener('click',e=>{const b=e.target.closest('.remove-special-date');if(b)b.closest('.special-date-row')?.remove()})});</script>
