<?php
if(!isPlatformOwner()){header('Location: ?page=dashboard');exit;}
$title='Empresas';require __DIR__.'/partials/top.php';$pdo=appDb();$mainTid=mainTenantId();$companies=[];$plans=[];$companyUsers=[];
try{
  $plans=$pdo->query("SELECT id,name,monthly_price,currency,active,is_default_free FROM subscription_plans ORDER BY is_default_free DESC,monthly_price,name")->fetchAll();
  $q=$pdo->prepare("SELECT t.id,t.uuid,t.name,t.business_id,t.contact_phone,t.registration_source,t.status,t.created_at,ts.plan_id,ts.status subscription_status,sp.name plan_name,sp.monthly_price,sp.currency,(SELECT COUNT(*) FROM tenant_users tu WHERE tu.tenant_id=t.id) user_count,(SELECT COUNT(*) FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=t.id AND u.status='active') active_users,(SELECT COUNT(*) FROM channels c WHERE c.tenant_id=t.id) channel_count,(SELECT u.name FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=t.id ORDER BY tu.is_owner DESC,tu.user_id LIMIT 1) owner_name,(SELECT u.email FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=t.id ORDER BY tu.is_owner DESC,tu.user_id LIMIT 1) owner_email FROM tenants t LEFT JOIN tenant_subscriptions ts ON ts.tenant_id=t.id LEFT JOIN subscription_plans sp ON sp.id=ts.plan_id ORDER BY (t.id=?) DESC,t.created_at DESC,t.name");$q->execute([$mainTid]);$companies=$q->fetchAll();
  $q=$pdo->query("SELECT tu.tenant_id,u.id,u.name,u.email,u.status,u.last_login_at,u.created_at,tu.role_code,tu.is_owner,(SELECT COUNT(*) FROM user_sessions s WHERE s.user_id=u.id AND s.revoked_at IS NULL AND s.expires_at>NOW()) active_sessions FROM tenant_users tu JOIN users u ON u.id=tu.user_id ORDER BY tu.tenant_id,tu.is_owner DESC,FIELD(tu.role_code,'owner','admin','supervisor','agent'),u.name");foreach($q->fetchAll() as $u)$companyUsers[(int)$u['tenant_id']][]=$u;
}catch(Throwable $e){}
$total=count($companies);$active=count(array_filter($companies,fn($x)=>$x['status']==='active'));$suspended=count(array_filter($companies,fn($x)=>in_array($x['status'],['suspended','closed'],true)));$usersTotal=array_sum(array_map(fn($x)=>(int)$x['user_count'],$companies));
$statusLabels=['trial'=>'Prueba','active'=>'Activa','past_due'=>'Pago pendiente','suspended'=>'Suspendida','closed'=>'Cerrada'];
?>
<section class="welcome companies-welcome"><div><small>ADMINISTRACIÓN DE PLATAFORMA</small><h1>Empresas</h1><p>Gestiona clientes, usuarios, planes y accesos desde un solo lugar. Las empresas registradas desde el login aparecen aquí automáticamente.</p></div><button class="primary" data-open="companyCreateModal"><i class="fa-solid fa-building-circle-check"></i> Crear empresa</button></section>
<section class="company-kpis"><article><span><i class="fa-solid fa-building"></i></span><div><b><?=$total?></b><small>Empresas registradas</small></div></article><article><span><i class="fa-solid fa-circle-check"></i></span><div><b><?=$active?></b><small>Empresas activas</small></div></article><article><span><i class="fa-solid fa-users"></i></span><div><b><?=$usersTotal?></b><small>Usuarios totales</small></div></article><article><span><i class="fa-solid fa-circle-pause"></i></span><div><b><?=$suspended?></b><small>Suspendidas / cerradas</small></div></article></section>
<section class="panel company-control-panel"><div class="company-filter-grid"><div class="field company-search-field"><label>Buscar empresa</label><div class="company-filter-search"><i class="fa-solid fa-magnifying-glass"></i><input id="companySearch" autocomplete="off" placeholder="Nombre, RTN/ID, propietario o correo"><button type="button" class="company-search-clear" id="companySearchClear" hidden aria-label="Limpiar búsqueda"><i class="fa-solid fa-xmark"></i></button></div></div><div class="field"><label>Estado</label><select id="companyStatusFilter" class="select2"><option value="">Todos los estados</option><?php foreach($statusLabels as $k=>$v):?><option value="<?=$k?>"><?=$v?></option><?php endforeach?></select></div><div class="field"><label>Plan</label><select id="companyPlanFilter" class="select2"><option value="">Todos los planes</option><?php foreach($plans as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?></option><?php endforeach?></select></div><button type="button" class="soft company-filter-clear" id="companyFilterClear"><i class="fa-solid fa-rotate-left"></i> Limpiar</button></div></section>
<section class="panel company-directory-shell">
<div class="company-directory-toolbar">
 <div class="company-directory-tools">
  <label class="company-show-count">Mostrar <select id="companyPerPage" class="company-mini-select"><option value="6">6</option><option value="9" selected>9</option><option value="12">12</option><option value="24">24</option></select> registros</label>
  <small id="companyPaginationInfo">Mostrando 0 de 0 empresas</small>
 </div>
 <div class="company-directory-search" role="search">
  <i class="fa-solid fa-magnifying-glass"></i>
  <input id="companyQuickSearch" autocomplete="off" placeholder="Buscar empresa, RTN, propietario o correo">
  <button type="button" class="company-search-clear" id="companyQuickSearchClear" hidden aria-label="Limpiar búsqueda"><i class="fa-solid fa-xmark"></i></button>
 </div>
</div>
<section class="company-grid" id="companyGrid">
<?php foreach($companies as $c):$isMain=(int)$c['id']===$mainTid;$status=$c['status'];$users=$companyUsers[(int)$c['id']]??[];$search=mb_strtolower(implode(' ',[$c['name'],$c['business_id'],$c['owner_name'],$c['owner_email'],$c['plan_name']]));?>
<article class="company-card" data-search="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" data-status="<?=htmlspecialchars($status)?>" data-plan="<?=(int)($c['plan_id']??0)?>"
 <div class="company-card-top"><div class="company-logo-placeholder"><i class="fa-solid <?=$isMain?'fa-shield-halved':'fa-building'?>"></i></div><div class="company-main-copy"><div class="company-title-line"><b><?=htmlspecialchars($c['name'])?></b><?php if($isMain):?><span class="ui-badge info">Plataforma</span><?php endif?></div><small><?=htmlspecialchars($c['business_id']?:'Sin identificación fiscal')?> · <?=htmlspecialchars($c['contact_phone']?:'Sin teléfono')?></small></div><span class="status-badge <?=$status==='active'?'connected':($status==='trial'?'warning':'muted')?>"><i class="fa-solid fa-circle"></i><?=htmlspecialchars($statusLabels[$status]??ucfirst($status))?></span></div>
 <div class="company-card-body"><div class="company-owner"><span><i class="fa-solid fa-user-tie"></i></span><div><small>USUARIO PRINCIPAL</small><b><?=htmlspecialchars($c['owner_name']?:'Sin propietario')?></b><em><?=htmlspecialchars($c['owner_email']?:'Sin correo')?></em></div></div><div class="company-stat-row"><span><b><?=(int)$c['user_count']?></b><small>Usuarios</small></span><span><b><?=(int)$c['active_users']?></b><small>Activos</small></span><span><b><?=(int)$c['channel_count']?></b><small>Canales</small></span></div><div class="company-plan-summary"><span><i class="fa-solid fa-gem"></i></span><div><small>PLAN ASIGNADO</small><b><?=htmlspecialchars($c['plan_name']?:'Sin plan')?></b><em><?=htmlspecialchars(ucfirst((string)($c['subscription_status']?:'sin estado')))?></em></div></div></div>
 <div class="company-card-actions"><button type="button" class="soft company-users-btn" data-tenant="<?=$c['id']?>" data-name="<?=htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8')?>"><i class="fa-solid fa-users-gear"></i> Usuarios</button><button type="button" class="soft company-edit-btn" data-tenant="<?=$c['id']?>" data-name="<?=htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8')?>" data-business="<?=htmlspecialchars((string)$c['business_id'],ENT_QUOTES,'UTF-8')?>" data-phone="<?=htmlspecialchars((string)$c['contact_phone'],ENT_QUOTES,'UTF-8')?>" data-status="<?=htmlspecialchars($status)?>"><i class="fa-solid fa-pen"></i> Empresa</button><button type="button" class="primary company-plan-btn" data-tenant="<?=$c['id']?>" data-name="<?=htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8')?>" data-plan="<?=(int)($c['plan_id']??0)?>" data-substatus="<?=htmlspecialchars((string)($c['subscription_status']?:'active'))?>"><i class="fa-solid fa-gem"></i> Plan</button></div>
 <div class="company-created"><i class="fa-regular fa-calendar"></i> Creada <?=htmlspecialchars($c['created_at'])?> · <?=htmlspecialchars($c['registration_source']==='self_service'?'Registro público':($c['registration_source']==='admin'?'Creada desde panel':'Sistema'))?></div>
</article>
<?php endforeach?>
<div class="company-empty" id="companyEmpty" hidden><i class="fa-solid fa-building-circle-xmark"></i><b>No encontramos empresas</b><span>Cuando no existan resultados, el directorio sigue disponible para crear, filtrar y navegar empresas.</span></div>
</section>
<div class="company-directory-footer">
 <small id="companyDirectorySummary">0 empresas en directorio</small>
 <div class="company-pagination" id="companyPagination"></div>
</div>
</section>

<div class="modal-shell" id="companyCreateModal"><div class="modal-card company-modal"><div class="modal-head"><div><b>Nueva empresa</b><small>Crea el cliente, su usuario principal, plan y NIVO Web Chat en un solo proceso.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="companyCreateForm"><input type="hidden" name="action" value="company_create"><div class="settings-grid"><div class="field"><label>Nombre de empresa</label><input name="company_name" required autofocus></div><div class="field"><label>RTN / identificación fiscal</label><input name="business_id" maxlength="80"></div><div class="field"><label>Teléfono</label><input name="contact_phone" maxlength="50"></div><div class="field"><label>Plan inicial</label><select name="plan_id" class="select2" required><?php foreach($plans as $p):if(!$p['active'])continue;?><option value="<?=$p['id']?>" <?=$p['is_default_free']?'selected':''?>><?=htmlspecialchars($p['name'])?> · <?=number_format((float)$p['monthly_price'],2)?> <?=htmlspecialchars($p['currency'])?></option><?php endforeach?></select></div><div class="field"><label>Usuario principal</label><input name="owner_name" required></div><div class="field"><label>Correo principal</label><input name="owner_email" type="email" required></div><div class="field full"><label>Contraseña temporal</label><div class="company-password-row"><input name="owner_password" id="companyOwnerPassword" type="text" minlength="8" required autocomplete="new-password"><button type="button" class="soft" id="companyGeneratePassword"><i class="fa-solid fa-wand-magic-sparkles"></i> Generar segura</button></div><small class="field-help">Entrégala al cliente por un canal seguro. Puede cambiarla después.</small></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-building-circle-check"></i> Crear empresa</button></div></form></div></div>

<div class="modal-shell" id="companyEditModal"><div class="modal-card company-modal"><div class="modal-head"><div><b>Administrar empresa</b><small>Datos generales y estado operativo.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="companyEditForm"><input type="hidden" name="action" value="company_update"><input type="hidden" name="tenant_id"><div class="settings-grid"><div class="field full"><label>Nombre</label><input name="company_name" required></div><div class="field"><label>RTN / identificación</label><input name="business_id"></div><div class="field"><label>Teléfono</label><input name="contact_phone"></div><div class="field full"><label>Estado</label><select name="status" class="select2"><?php foreach($statusLabels as $k=>$v):?><option value="<?=$k?>"><?=$v?></option><?php endforeach?></select></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar cambios</button></div></form></div></div>

<div class="modal-shell" id="companyPlanModal"><div class="modal-card company-modal"><div class="modal-head"><div><b>Asignar plan</b><small id="companyPlanSubtitle">El plan pertenece a la empresa y todos sus usuarios heredan sus capacidades.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="companyPlanForm"><input type="hidden" name="action" value="subscription_assign"><input type="hidden" name="tenant_id"><div class="settings-grid"><div class="field full"><label>Plan</label><select name="plan_id" class="select2" required><?php foreach($plans as $p):if(!$p['active'])continue;?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?> · <?=number_format((float)$p['monthly_price'],2)?> <?=htmlspecialchars($p['currency'])?></option><?php endforeach?></select></div><div class="field full"><label>Estado de suscripción</label><select name="status" class="select2"><option value="active">Activo</option><option value="grace">Gracia</option><option value="suspended">Suspendido</option><option value="cancelled">Cancelado</option></select></div></div><div class="company-plan-note"><i class="fa-solid fa-circle-info"></i><span>Al guardar, ZYNKO aplica inmediatamente los módulos, canales, límites y beneficios del plan a toda la empresa.</span></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-gem"></i> Asignar plan</button></div></form></div></div>

<div class="modal-shell" id="companyUsersModal"><div class="modal-card company-users-modal"><div class="modal-head"><div><b id="companyUsersTitle">Usuarios de empresa</b><small>Administra accesos sin conocer ni visualizar contraseñas actuales.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><div class="company-security-note"><i class="fa-solid fa-shield-halved"></i><span>Por seguridad las contraseñas existentes están cifradas con hash y no pueden visualizarse. Puedes generar una contraseña temporal nueva cuando el cliente lo solicite.</span></div><div id="companyUsersList" class="company-user-list"></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cerrar</button></div></div></div>
<script>window.ZYNKO_COMPANY_USERS=<?=json_encode($companyUsers,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<?php require __DIR__.'/partials/bottom.php'; ?>
