<?php
$title='Documentación'; require __DIR__.'/partials/top.php';
$changes=[];try{$changes=json_decode((string)file_get_contents($root.'/docs/CHANGELOG.json'),true)?:[];}catch(Throwable $e){}
$current=$changes[0]??['version'=>'2.31.114','title'=>'Versión actual','date'=>'','changes'=>[]];
?>
<section class="welcome"><div><small>DOCUMENTACIÓN VIVA</small><h1>Documentación e historial</h1><p>Consulta el estado funcional de API, NIVO, Web Chat, canales y cambios por versión.</p></div><a class="secondary-action" href="?page=home#documentacion" target="_blank"><i class="fa-solid fa-arrow-up-right-from-square"></i> Ver documentación pública</a></section>
<section class="panel docs-version-panel">
 <div class="panel-head premium-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-code-branch"></i></span><div><b>Historial de versiones</b><small>Cada mejora funcional debe quedar documentada aquí y en el sitio público.</small></div><div class="head-actions"><select id="docsVersionSelect" class="select2"><?php foreach($changes as $i=>$c):?><option value="docs-v-<?=$i?>" <?=$i===0?'selected':''?>>v<?=htmlspecialchars($c['version'])?> · <?=htmlspecialchars($c['title'])?></option><?php endforeach?></select></div></div>
 <div class="docs-version-list"><?php foreach($changes as $i=>$c):?><article id="docs-v-<?=$i?>" class="docs-version-card" <?=$i===0?'':'hidden'?>><div><span class="ui-badge success">v<?=htmlspecialchars($c['version'])?></span><small><?=htmlspecialchars($c['date'])?></small></div><h3><?=htmlspecialchars($c['title'])?></h3><ul><?php foreach(($c['changes']??[]) as $change):?><li><i class="fa-solid fa-circle-check"></i><?=htmlspecialchars($change)?></li><?php endforeach?></ul></article><?php endforeach?></div>
</section>
<section class="docs-admin-grid">
 <article class="panel"><div class="panel-head premium-card-head compact-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-message"></i></span><div><b>NIVO Web Chat</b><small>Widget, sitios, tiempo real y experiencia.</small></div></div><p>El mensaje se persiste en base de datos, WebSocket entrega en tiempo real y la reconciliación HTTP repara eventos perdidos. Los sitios externos usan installation_key única por dominio.</p><a class="soft" href="?page=webchat">Abrir NIVO Web Chat</a></article>
 <article class="panel"><div class="panel-head premium-card-head compact-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-brain"></i></span><div><b>NIVO IA</b><small>Reglas, conocimiento y handoff.</small></div></div><p>NIVO prioriza reglas e información aprobada del tenant, mantiene contexto y transfiere a humano cuando corresponde.</p><a class="soft" href="?page=chatbot">Abrir NIVO IA</a></article>
 <article class="panel"><div class="panel-head premium-card-head compact-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-code"></i></span><div><b>API e integraciones</b><small>Claves, webhooks, scopes y endpoints.</small></div></div><p>Las claves son por tenant, soportan scopes, restricciones de origen/IP y rate limit. Los conectores externos requieren autorización real del proveedor.</p><a class="soft" href="?page=integrations">Abrir Integraciones</a></article>
 <article class="panel"><div class="panel-head premium-card-head compact-card-head"><span class="premium-card-head-icon"><i class="fa-solid fa-satellite-dish"></i></span><div><b>Canales</b><small>WhatsApp, Messenger, Instagram, Telegram, Web Chat y correo.</small></div></div><p>Los conectores solo se marcan conectados después de validación real. Correo SMTP/Graph actual cubre envío/notificaciones; la recepción omnicanal requiere un conector entrante autorizado.</p><a class="soft" href="?page=channels">Abrir Canales</a></article>
</section>
<script>document.addEventListener('DOMContentLoaded',()=>{const select=document.getElementById('docsVersionSelect');select?.addEventListener('change',()=>{document.querySelectorAll('.docs-version-card').forEach(x=>x.hidden=x.id!==select.value);});});</script>
<?php require __DIR__.'/partials/bottom.php'; ?>
