<?php
$env=envConfig($root.'/.env');
$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';
$host=$_SERVER['HTTP_HOST']??'localhost';
$seo=[];try{$rows=appDb()->query("SELECT setting_key,setting_value FROM system_settings WHERE setting_key LIKE 'seo_%'")->fetchAll();foreach($rows as $r)$seo[$r['setting_key']]=$r['setting_value'];}catch(Throwable $e){}
$configured=trim((string)($seo['seo_site_url']??''));if($configured==='')$configured=trim((string)($env['APP_URL']??''));
$baseUrl=$configured!==''?rtrim($configured,'/'):$scheme.'://'.$host;
$siteName=trim((string)($seo['seo_site_name']??($env['SEO_SITE_NAME']??'ZYNKO')))?:'ZYNKO';
$description=trim((string)($seo['seo_description']??($env['SEO_DESCRIPTION']??'Plataforma SaaS omnicanal para centralizar conversaciones, Web Chat, automatización y atención humana.')));
$locale=trim((string)($seo['seo_locale']??($env['SEO_LOCALE']??'es_HN')))?:'es_HN';
$twitter=trim((string)($seo['seo_twitter']??($env['SEO_TWITTER']??'')));
$googleVerification=trim((string)($seo['seo_google_verification']??''));
$bingVerification=trim((string)($seo['seo_bing_verification']??''));
$ogImage=$baseUrl.'/assets/img/og-zynko.png';
$canonical=$baseUrl.'/';
$schema=[
 '@context'=>'https://schema.org','@graph'=>[
  ['@type'=>'Organization','@id'=>$baseUrl.'/#organization','name'=>$siteName,'url'=>$baseUrl.'/','logo'=>$baseUrl.'/assets/img/favicon.svg'],
  ['@type'=>'SoftwareApplication','@id'=>$baseUrl.'/#software','name'=>$siteName,'applicationCategory'=>'BusinessApplication','operatingSystem'=>'Web','url'=>$baseUrl.'/','description'=>$description,'offers'=>['@type'=>'Offer','price'=>'0','priceCurrency'=>'USD','description'=>'Plan Gratis disponible'],'publisher'=>['@id'=>$baseUrl.'/#organization']],
  ['@type'=>'WebSite','@id'=>$baseUrl.'/#website','url'=>$baseUrl.'/','name'=>$siteName,'description'=>$description,'publisher'=>['@id'=>$baseUrl.'/#organization'],'inLanguage'=>'es']
 ]
];
?>
<!doctype html><html lang="es"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ZYNKO | Plataforma omnicanal para conversaciones y atención al cliente</title>
<meta name="description" content="<?=htmlspecialchars($description,ENT_QUOTES,'UTF-8')?>">
<?php if($googleVerification!==''):?><meta name="google-site-verification" content="<?=htmlspecialchars($googleVerification,ENT_QUOTES,'UTF-8')?>"><?php endif?>
<?php if($bingVerification!==''):?><meta name="msvalidate.01" content="<?=htmlspecialchars($bingVerification,ENT_QUOTES,'UTF-8')?>"><?php endif?>
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">
<link rel="canonical" href="<?=htmlspecialchars($canonical,ENT_QUOTES,'UTF-8')?>">
<meta property="og:type" content="website"><meta property="og:site_name" content="<?=htmlspecialchars($siteName,ENT_QUOTES,'UTF-8')?>"><meta property="og:locale" content="<?=htmlspecialchars($locale,ENT_QUOTES,'UTF-8')?>">
<meta property="og:title" content="ZYNKO | Atención omnicanal desde un solo lugar"><meta property="og:description" content="<?=htmlspecialchars($description,ENT_QUOTES,'UTF-8')?>"><meta property="og:url" content="<?=htmlspecialchars($canonical,ENT_QUOTES,'UTF-8')?>"><meta property="og:image" content="<?=htmlspecialchars($ogImage,ENT_QUOTES,'UTF-8')?>"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="ZYNKO | Atención omnicanal"><meta name="twitter:description" content="<?=htmlspecialchars($description,ENT_QUOTES,'UTF-8')?>"><meta name="twitter:image" content="<?=htmlspecialchars($ogImage,ENT_QUOTES,'UTF-8')?>"><?php if($twitter!==''):?><meta name="twitter:site" content="<?=htmlspecialchars($twitter,ENT_QUOTES,'UTF-8')?>"><?php endif?>
<meta name="theme-color" content="#0f766e"><link rel="icon" href="assets/img/favicon.svg"><link rel="manifest" href="site.webmanifest">
<link rel="stylesheet" href="assets/vendor/fontawesome/css/all.min.css"><link rel="stylesheet" href="assets/css/seo-home.css?v=<?=filemtime(__DIR__.'/../../public/assets/css/seo-home.css')?>">
<script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
</head><body>
<header class="site-header"><div class="wrap nav"><a class="logo" href="./" aria-label="ZYNKO inicio"><span class="brandmark">ZY</span><span><b>ZYNKO</b><small>Omnichannel SaaS</small></span></a><nav aria-label="Navegación principal"><a href="#funciones">Funciones</a><a href="#plan">Plan Gratis</a><a href="#faq">Preguntas</a></nav><div class="nav-actions"><a class="btn ghost" href="?page=login">Iniciar sesión</a><a class="btn primary" href="?page=register">Crear cuenta gratis</a></div></div></header>
<main>
<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow"><i class="fa-solid fa-circle-check"></i> OMNICANAL · MULTIEMPRESA · SAAS</span><h1>Tus conversaciones, clientes y atención en <span>un solo lugar.</span></h1><p>ZYNKO centraliza la comunicación de tu empresa y combina atención humana, NIVO Web Chat, automatización e integraciones en una experiencia clara y escalable.</p><div class="hero-actions"><a class="btn primary large" href="?page=register"><i class="fa-solid fa-rocket"></i> Comenzar gratis</a><a class="btn ghost large" href="?page=login">Ya tengo una cuenta</a></div><div class="trust"><span><i class="fa-solid fa-shield-halved"></i> Acceso seguro</span><span><i class="fa-solid fa-building"></i> Multiempresa</span><span><i class="fa-solid fa-comments"></i> Atención omnicanal</span></div></div><div class="hero-panel" aria-label="Resumen de ZYNKO"><div class="panel-top"><span><i class="fa-solid fa-wave-square"></i> Operación centralizada</span><b>En línea</b></div><div class="metric-grid"><article><i class="fa-solid fa-inbox"></i><b>Bandeja unificada</b><p>Organiza conversaciones y atención desde una sola vista.</p></article><article><i class="fa-solid fa-message"></i><b>NIVO Web Chat</b><p>Activa un canal web desde el primer día.</p></article><article><i class="fa-solid fa-users"></i><b>Equipos y roles</b><p>Controla accesos y responsabilidades por empresa.</p></article><article><i class="fa-solid fa-plug"></i><b>Integraciones</b><p>Conecta API, webhooks y canales externos.</p></article></div></div></div></section>
<section class="section" id="funciones"><div class="wrap"><div class="section-head"><span class="eyebrow">PLATAFORMA</span><h2>Diseñada para ordenar la atención, no para complicarla.</h2><p>Una base única para administrar conversaciones, clientes, usuarios, automatización e integraciones.</p></div><div class="feature-grid"><article><span><i class="fa-solid fa-comments"></i></span><h3>Conversaciones centralizadas</h3><p>Consulta y gestiona la atención de distintos canales desde una bandeja común.</p></article><article><span><i class="fa-solid fa-robot"></i></span><h3>NIVO y automatización</h3><p>Configura asistencia automatizada y transferencia a personas cuando sea necesario.</p></article><article><span><i class="fa-solid fa-user-shield"></i></span><h3>Usuarios y permisos</h3><p>Administra equipos, roles y accesos dentro de cada empresa de forma separada.</p></article><article><span><i class="fa-solid fa-chart-line"></i></span><h3>Visibilidad operativa</h3><p>Revisa actividad, estados de canales y señales importantes desde el dashboard.</p></article><article><span><i class="fa-solid fa-code-branch"></i></span><h3>API y webhooks</h3><p>Integra ZYNKO con procesos externos sin mezclar la información entre empresas.</p></article><article><span><i class="fa-solid fa-envelope"></i></span><h3>Notificaciones</h3><p>Configura correo y avisos para eventos relevantes de la operación.</p></article></div></div></section>
<section class="section soft" id="plan"><div class="wrap plan-grid"><div><span class="eyebrow">EMPIEZA SIN COSTO</span><h2>Plan Gratis para poner ZYNKO a trabajar desde hoy.</h2><p>Registra tu empresa, verifica tu correo y comienza con las capacidades visibles durante el registro.</p><ul><li><i class="fa-solid fa-check"></i> NIVO Web Chat incluido</li><li><i class="fa-solid fa-check"></i> 1 sitio web autorizado</li><li><i class="fa-solid fa-check"></i> 5 chats nuevos por día</li><li><i class="fa-solid fa-check"></i> Mensajes ilimitados dentro de cada chat</li></ul></div><aside class="plan-card"><span>PLAN GRATIS</span><b>$0</b><small>Para comenzar</small><a class="btn primary large" href="?page=register">Crear empresa</a><p>La disponibilidad y los límites vigentes siempre se muestran dentro de ZYNKO.</p></aside></div></section>
<section class="section" id="faq"><div class="wrap"><div class="section-head"><span class="eyebrow">PREGUNTAS FRECUENTES</span><h2>Lo esencial antes de comenzar.</h2></div><div class="faq-grid"><details><summary>¿Qué es ZYNKO?</summary><p>Es una plataforma SaaS omnicanal para organizar conversaciones, atención, usuarios, canales, automatización e integraciones empresariales.</p></details><details><summary>¿Puedo crear una cuenta gratis?</summary><p>Sí. El registro público permite crear una empresa, verificar el correo y comenzar con el Plan Gratis disponible.</p></details><details><summary>¿ZYNKO trabaja con varias empresas?</summary><p>Sí. La plataforma está diseñada con separación lógica de información y configuración por empresa.</p></details><details><summary>¿Puedo conectar servicios externos?</summary><p>ZYNKO contempla integraciones mediante canales, API y webhooks, sujetas a la configuración y al plan correspondiente.</p></details></div></div></section>
<section class="cta"><div class="wrap cta-box"><div><span class="eyebrow">ZYNKO</span><h2>Centraliza tu atención y empieza con una operación más ordenada.</h2></div><a class="btn primary large" href="?page=register">Crear cuenta gratis <i class="fa-solid fa-arrow-right"></i></a></div></section>
</main>
<footer><div class="wrap footer"><div class="logo"><span class="brandmark">ZY</span><span><b>ZYNKO</b><small>Omnichannel SaaS</small></span></div><p>Plataforma omnicanal para empresas.</p><div><a href="?page=login">Iniciar sesión</a><a href="?page=register">Crear cuenta</a></div></div></footer>
</body></html>