<?php $title='Integraciones'; require __DIR__.'/partials/top.php';$rows=[];$keys=[];$env=envConfig($root.'/.env');$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$publishedBase='';try{$sq=appDb()->prepare("SELECT setting_value FROM system_settings WHERE setting_key='seo_site_url' LIMIT 1");$sq->execute();$publishedBase=trim((string)($sq->fetchColumn()?:''));}catch(Throwable $e){}if($publishedBase==='')$publishedBase=trim((string)($env['APP_URL']??''));if($publishedBase==='')$publishedBase=$scheme.'://'.$host.rtrim(dirname($_SERVER['SCRIPT_NAME']??'/'),'/');$publishedBase=htmlspecialchars_decode($publishedBase,ENT_QUOTES);$publishedBase=str_replace('\\','',$publishedBase);$publishedBase=trim($publishedBase);if($publishedBase!==''&&!preg_match('~^https?://~i',$publishedBase))$publishedBase=$scheme.'://'.ltrim($publishedBase,'/');$publishedBase=rtrim($publishedBase,'/');$apiRoot=$publishedBase.'/api.php?r=';try{require_once dirname(__DIR__).'/Support/AccessPolicy.php';ZynkoAccessPolicy::ensureTables(appDb());}catch(Throwable $e){}try{$q=appDb()->prepare('SELECT id,name,url,events_json,active,created_at FROM outgoing_webhooks WHERE tenant_id=? ORDER BY id DESC');$q->execute([$_SESSION['user']['tenant_id']]);$rows=$q->fetchAll();$q=appDb()->prepare('SELECT k.id,k.name,k.key_prefix,k.last_used_at,k.created_at,k.revoked_at,k.expires_at,k.scopes_json,p.allowed_origins_json,p.allowed_ips_json,p.rate_limit_per_minute,p.require_https,p.active policy_active FROM api_keys k LEFT JOIN api_client_policies p ON p.api_key_id=k.id WHERE k.tenant_id=? ORDER BY k.id DESC');$q->execute([$_SESSION['user']['tenant_id']]);$keys=$q->fetchAll();}catch(Throwable $e){} ?>
<section class="welcome"><div><small>API & WEBHOOKS</small><h1>Integraciones</h1><p>Conecta IZZY, CAMI u otros sistemas mediante webhooks HTTPS firmados.</p></div><button class="primary" data-open="integrationModal"><i class="fa-solid fa-plug-circle-plus"></i> Nueva integración</button></section><section class="panel"><div class="card-list"><?php if(!$rows):?><div class="empty-compact"><i class="fa-solid fa-plug"></i><b>Aún no hay integraciones</b><span>Crea la primera para empezar a intercambiar eventos.</span></div><?php else:foreach($rows as $r):?><article class="integration-card"><span class="channel-icon"><i class="fa-solid fa-webhook"></i></span><div><b><?=htmlspecialchars($r['name'])?></b><small><?=htmlspecialchars($r['url'])?></small></div><span class="ui-badge <?=$r['active']?'success':'muted'?>"><i class="fa-solid fa-circle"></i><?=$r['active']?'Activa':'Inactiva'?></span></article><?php endforeach;endif?></div></section>
<section class="panel"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-plug"></i></span><div><b>Acceso API para IZZY, CAMI y otros sistemas</b><small>Solo sistemas con una clave secreta válida pueden enviar solicitudes a ZYNKO.</small></div><button class="primary" data-open="apiKeyModal"><i class="fa-solid fa-key"></i> Crear clave API</button></div><div class="api-key-list"><?php if(!$keys):?><div class="empty-compact"><i class="fa-solid fa-shield-halved"></i><b>No hay claves API</b><span>Crea una clave distinta por cada sistema externo.</span></div><?php else:foreach($keys as $k):$origins=json_decode((string)($k['allowed_origins_json']??'[]'),true)?:[];$ips=json_decode((string)($k['allowed_ips_json']??'[]'),true)?:[];$scopes=json_decode((string)($k['scopes_json']??'[]'),true)?:[];?><article class="api-key-row"><div><b><?=htmlspecialchars($k['name'])?></b><small><?=htmlspecialchars($k['key_prefix'])?>•••••••• · <?= $k['last_used_at']?'Último uso '.$k['last_used_at']:'Nunca utilizada'?></small><div class="api-policy-summary"><span><i class="fa-solid fa-globe"></i> <?=$origins?count($origins).' origen(es)':'Cualquier origen con clave válida'?></span><span><i class="fa-solid fa-network-wired"></i> <?=$ips?count($ips).' IP/CIDR':'Cualquier IP'?></span><span><i class="fa-solid fa-gauge-high"></i> <?=max(10,(int)($k['rate_limit_per_minute']??120))?>/min</span><span><i class="fa-solid fa-key"></i> <?=count($scopes)?> permisos</span></div></div><span class="ui-badge <?=$k['revoked_at']?'danger':'success'?>"><i class="fa-solid fa-circle"></i><?=$k['revoked_at']?'Revocada':'Activa'?></span><?php if(!$k['revoked_at']):?><button type="button" class="soft api-policy-edit" data-id="<?=$k['id']?>" data-name="<?=htmlspecialchars($k['name'],ENT_QUOTES)?>" data-origins="<?=htmlspecialchars(implode("
",$origins),ENT_QUOTES)?>" data-ips="<?=htmlspecialchars(implode("
",$ips),ENT_QUOTES)?>" data-rate="<?=max(10,(int)($k['rate_limit_per_minute']??120))?>" data-https="<?=!array_key_exists('require_https',$k)||!empty($k['require_https'])?'1':'0'?>" data-active="<?=!array_key_exists('policy_active',$k)||$k['policy_active']===null||!empty($k['policy_active'])?'1':'0'?>"><i class="fa-solid fa-shield-halved"></i> Permisos</button><button class="soft danger api-key-revoke" data-id="<?=$k['id']?>"><i class="fa-solid fa-ban"></i> Revocar</button><?php endif?></article><?php endforeach;endif?></div><div class="api-doc"><i class="fa-solid fa-code"></i><div><b>API REST segura</b><small>Endpoint local: <code>/api.php?r=v1/messages/send</code>. Usa <code>Authorization: Bearer TU_CLAVE</code> e <code>Idempotency-Key</code> para evitar duplicados. ZYNKO rechaza claves inválidas, revocadas o sin permisos.</small></div></div></section>
<section class="panel nivo-install-doc-panel"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-plug"></i></span><div><b><i class="fa-solid fa-robot"></i> Configurar e instalar NIVO Web Chat</b><small>NIVO Web Chat no necesita una clave API para instalarse. Cada dominio externo usa su propio código de instalación.</small></div><a class="primary" href="?page=webchat"><i class="fa-solid fa-message"></i> Abrir NIVO Web Chat</a></div><div class="nivo-install-doc-grid"><article><span>1</span><div><b>Configura NIVO IA</b><small>Define reglas, conocimiento aprobado y transferencia humana desde NIVO · IA.</small></div></article><article><span>2</span><div><b>Personaliza el widget</b><small>Ajusta saludo, posición, privacidad, respuestas rápidas y experiencia desde NIVO Web Chat.</small></div></article><article><span>3</span><div><b>Autoriza el dominio</b><small>Agrega el sitio externo. El máximo permitido depende del plan de la empresa.</small></div></article><article><span>4</span><div><b>Copia el script único</b><small>La tarjeta del sitio muestra el código exclusivo. Pégalo antes de &lt;/body&gt; y verifica “Último uso”.</small></div></article></div><div class="nivo-install-doc-note"><i class="fa-solid fa-shield-halved"></i><span>El sitio principal de ZYNKO se administra automáticamente y no consume el cupo de sitios externos. Las claves API de esta página son para integrar sistemas; no son necesarias para instalar NIVO Web Chat.</span></div><div class="nivo-install-doc-note"><i class="fa-solid fa-building-shield"></i><span><b>Multiempresa real:</b> NIVO Web Chat resuelve el tenant desde la instalación autorizada. NIVO IA consulta reglas, conocimiento, fuentes web y aprendizaje únicamente de esa empresa. Las fuentes de una empresa nunca se comparten automáticamente con otra.</span></div></section>
<section class="panel api-howto-panel"><div class="panel-head premium-card-head"><span class="premium-card-head-icon" aria-hidden="true"><i class="fa-solid fa-plug"></i></span><div><b>Cómo usar ZYNKO desde otro sistema</b><small>La URL se toma automáticamente del sitio publicado. No necesitas editar el dominio de los ejemplos manualmente.</small></div><span class="status-badge connected"><i class="fa-solid fa-link"></i> <?=htmlspecialchars(preg_replace('~/api\.php\?r=$~','',$apiRoot))?></span></div><div class="security-note"><i class="fa-solid fa-shield-halved"></i><div><b>Política de seguridad por clave</b><small>Antes de integrar, define los scopes mínimos y, si aplica, limita la credencial por origen web, IP/CIDR, HTTPS, vencimiento y rate limit. Estas reglas se validan en servidor y pueden editarse sin regenerar la clave.</small></div></div><div class="api-flow-grid"><article class="api-flow-card"><span>1</span><div><b>Crear clave API</b><small>Ve a <strong>Integraciones → Crear clave API</strong>. La llave pertenece únicamente a esta empresa.</small></div></article><article class="api-flow-card"><span>2</span><div><b>Consultar canales</b><code>GET <?=htmlspecialchars($apiRoot)?>v1/channels</code><small>Obtén el channel_id de WhatsApp, Messenger, NIVO Web Chat y demás canales habilitados.</small></div></article><article class="api-flow-card"><span>3</span><div><b>Recibir hacia NIVO</b><code>POST <?=htmlspecialchars($apiRoot)?>v1/messages/receive</code><small>Registra la conversación, ejecuta NIVO IA y devuelve respuesta o handoff.</small></div></article><article class="api-flow-card"><span>4</span><div><b>Enviar mensaje</b><code>POST <?=htmlspecialchars($apiRoot)?>v1/messages/send</code><small>Valida el canal, registra el mensaje saliente y lo deja en cola para el despachador del conector autorizado.</small></div></article></div>
<div class="api-doc-columns">
 <div class="api-doc-column">
  <article class="api-doc-card"><div class="api-doc-title"><i class="fa-solid fa-list"></i><div><b>Consultar canales</b><small>GET v1/channels</small></div><button type="button" class="api-copy-btn" data-copy-target="panelChannelsCurl"><i class="fa-regular fa-copy"></i><span>Copiar</span></button></div><pre id="panelChannelsCurl"><code>curl "<?=htmlspecialchars($apiRoot)?>v1/channels" \
  -H "Authorization: Bearer TU_CLAVE_API"</code></pre><div class="api-doc-response"><div class="api-subhead"><b>Respuesta de ejemplo</b><button type="button" class="api-copy-mini" data-copy-target="panelChannelsResponse"><i class="fa-regular fa-copy"></i> Copiar</button></div><pre id="panelChannelsResponse"><code>{
  "ok": true,
  "data": {
    "channels": [
      {
        "id": 12,
        "type": "whatsapp",
        "name": "WhatsApp Business",
        "status": "connected"
      }
    ]
  }
}</code></pre></div></article>
  <article class="api-doc-card"><div class="api-doc-title"><i class="fa-solid fa-paper-plane"></i><div><b>Enviar mensaje saliente</b><small>POST v1/messages/send</small></div><button type="button" class="api-copy-btn" data-copy-target="panelSendCurl"><i class="fa-regular fa-copy"></i><span>Copiar</span></button></div><pre id="panelSendCurl"><code>curl -X POST "<?=htmlspecialchars($apiRoot)?>v1/messages/send" \
  -H "Authorization: Bearer TU_CLAVE_API" \
  -H "Content-Type: application/json" \
  -H "Idempotency-Key: izzy-000123" \
  -d '{
    "channel_id": 12,
    "to": "+50499999999",
    "contact_name": "Juan Pérez",
    "message": "Su solicitud ya fue procesada."
  }'</code></pre><div class="api-doc-warning"><i class="fa-solid fa-circle-info"></i><span><b>Entrega real:</b> <code>messages/send</code> responde HTTP 202 y deja el mensaje en estado <code>queued</code>. WhatsApp, Messenger y otros proveedores habilitados necesitan su conector oficial autorizado y operativo para completar la entrega.</span></div></article>
 </div>
 <div class="api-doc-column">
  <article class="api-doc-card"><div class="api-doc-title"><i class="fa-solid fa-arrow-right-to-bracket"></i><div><b>Ingresar mensaje recibido</b><small>POST v1/messages/receive</small></div><button type="button" class="api-copy-btn" data-copy-target="panelReceiveCurl"><i class="fa-regular fa-copy"></i><span>Copiar</span></button></div><pre id="panelReceiveCurl"><code>curl -X POST "<?=htmlspecialchars($apiRoot)?>v1/messages/receive" \
  -H "Authorization: Bearer TU_CLAVE_API" \
  -H "Content-Type: application/json" \
  -H "Idempotency-Key: whatsapp-msg-987654" \
  -d '{
    "channel_id": 12,
    "from": "+50499999999",
    "contact_name": "Juan Pérez",
    "message": "Hola, necesito información"
  }'</code></pre><div class="api-route-flow"><span>Sistema externo</span><i class="fa-solid fa-arrow-right"></i><span>ZYNKO</span><i class="fa-solid fa-arrow-right"></i><span>Canal</span><i class="fa-solid fa-arrow-right"></i><span>NIVO IA</span><i class="fa-solid fa-arrow-right"></i><span>Respuesta / handoff</span></div><div class="api-doc-response"><div class="api-subhead"><b>Decisión de NIVO</b><button type="button" class="api-copy-mini" data-copy-target="panelReceiveResponse"><i class="fa-regular fa-copy"></i> Copiar</button></div><pre id="panelReceiveResponse"><code>{
  "ok": true,
  "data": {
    "conversation_id": 123,
    "channel": "whatsapp",
    "nivo": {
      "reply": "¡Hola Juan! Soy NIVO...",
      "handoff": false,
      "source": "rule",
      "reason": null
    }
  }
}</code></pre></div></article>
 </div>
</div></section>
<div class="modal-shell" id="apiKeyModal"><div class="modal-card"><div class="modal-head"><div><b>Nueva clave API</b><small>Usa una clave por sistema y limita exactamente desde dónde puede utilizarse.</small></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="apiKeyForm"><input type="hidden" name="action" value="api_key_create"><div class="field"><label>Nombre del sistema</label><input name="name" required maxlength="120" placeholder="Ej. IZZY Producción"></div><div class="api-policy-fields"><div class="field full"><label>Sitios / orígenes permitidos <small>Opcional</small></label><textarea name="allowed_origins" rows="3" placeholder="https://izzycloud.app&#10;https://miempresa.com"></textarea><small class="field-help">Si lo dejas vacío, la clave puede usarse server-to-server desde cualquier origen. En navegador, puedes restringirla a sitios concretos.</small></div><div class="field full"><label>IP o redes CIDR permitidas <small>Opcional</small></label><textarea name="allowed_ips" rows="2" placeholder="203.0.113.10&#10;198.51.100.0/24"></textarea></div><div class="field"><label>Límite por minuto</label><input type="number" name="rate_limit_per_minute" min="10" max="5000" value="120"></div><div class="field"><label>Vencimiento</label><select name="expires_days" class="select2"><option value="0">Sin vencimiento</option><option value="30">30 días</option><option value="90">90 días</option><option value="365">1 año</option></select></div><div class="field full"><label>Permisos</label><div class="check-grid"><label><input type="checkbox" name="scopes[]" value="channels:read" checked> Leer canales</label><label><input type="checkbox" name="scopes[]" value="messages:send" checked> Enviar mensajes</label><label><input type="checkbox" name="scopes[]" value="messages:receive" checked> Recibir mensajes</label><label><input type="checkbox" name="scopes[]" value="nivo:context" checked> Consultar NIVO</label></div></div><div class="field full"><label class="switch-line"><input type="checkbox" name="require_https" checked><span class="switch-control"></span><span class="switch-label-text">Exigir HTTPS en solicitudes desde navegador</span></label></div></div><div class="security-note"><i class="fa-solid fa-shield-halved"></i><div><b>La clave se mostrará una sola vez</b><small>ZYNKO guarda únicamente su hash. Origen, IP, scopes, vencimiento y rate limit se validan en servidor.</small></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-key"></i> Generar clave segura</button></div></form></div></div>
<div class="modal-shell" id="apiPolicyModal"><div class="modal-card"><div class="modal-head"><div><b>Permisos de la clave API</b><small id="apiPolicyName">Configura sitios, IP y límites sin regenerar la credencial.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="apiPolicyForm"><input type="hidden" name="action" value="api_key_policy_save"><input type="hidden" name="api_key_id" value="0"><div class="api-policy-fields"><div class="field full"><label>Sitios / orígenes permitidos</label><textarea name="allowed_origins" rows="3" placeholder="https://cliente.com"></textarea></div><div class="field full"><label>IP / CIDR permitidos</label><textarea name="allowed_ips" rows="2"></textarea></div><div class="field"><label>Límite por minuto</label><input type="number" name="rate_limit_per_minute" min="10" max="5000" value="120"></div><div class="field"><label class="switch-line"><input type="checkbox" name="require_https" checked><span class="switch-control"></span><span class="switch-label-text">Exigir HTTPS</span></label></div><div class="field full"><label class="switch-line"><input type="checkbox" name="active" checked><span class="switch-control"></span><span class="switch-label-text">Política activa</span></label></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cerrar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar permisos</button></div></form></div></div>
<div class="modal-shell" id="integrationModal"><div class="modal-card"><div class="modal-head"><div class="modal-title-with-icon"><span class="modal-title-icon"><i class="fa-solid fa-plug-circle-plus"></i></span><span class="modal-title-copy"><b>Nueva integración</b><small>El secreto se genera automáticamente y se muestra una sola vez.</small></span></div><button class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="integrationForm"><input type="hidden" name="action" value="integration_save"><div class="field"><label>Nombre</label><input name="name" required placeholder="Ej. IZZY Producción"></div><div class="field"><label>Webhook HTTPS</label><input name="url" type="url" required placeholder="https://.../webhook"></div><div class="field integration-events"><label>Eventos</label><small class="field-help">Selecciona qué eventos enviará ZYNKO a este webhook.</small><div class="check-grid"><label><input type="checkbox" name="events[]" value="conversation.created" checked> Conversación creada</label><label><input type="checkbox" name="events[]" value="message.received" checked> Mensaje recibido</label><label><input type="checkbox" name="events[]" value="conversation.resolved"> Conversación resuelta</label></div></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar integración</button></div></form></div></div><script>
document.addEventListener('DOMContentLoaded',()=>{
  const modal=document.getElementById('apiPolicyModal'),form=document.getElementById('apiPolicyForm');
  document.querySelectorAll('.api-policy-edit').forEach(btn=>btn.addEventListener('click',()=>{
    if(!modal||!form)return;
    form.api_key_id.value=btn.dataset.id||'0';form.allowed_origins.value=btn.dataset.origins||'';form.allowed_ips.value=btn.dataset.ips||'';form.rate_limit_per_minute.value=btn.dataset.rate||'120';form.require_https.checked=btn.dataset.https==='1';form.active.checked=btn.dataset.active==='1';
    const name=document.getElementById('apiPolicyName');if(name)name.textContent='Clave: '+(btn.dataset.name||'API');modal.classList.add('open');
  }));
});
</script>
<?php require __DIR__.'/partials/bottom.php'; ?>