<?php
$title='NIVO Web Chat'; require __DIR__.'/partials/top.php'; $tid=(int)$_SESSION['user']['tenant_id'];
$q=appDb()->prepare('SELECT * FROM webchat_widgets WHERE tenant_id=? ORDER BY id LIMIT 1');$q->execute([$tid]);$w=$q->fetch();$tq=appDb()->prepare('SELECT name FROM tenants WHERE id=? LIMIT 1');$tq->execute([$tid]);$tenantName=(string)($tq->fetchColumn()?:($_SESSION['user']['company']??'Tu empresa'));$assistantSubtitle=trim((string)($w['assistant_subtitle']??''));if($assistantSubtitle==='')$assistantSubtitle='Asistente virtual de '.$tenantName;$experience=json_decode((string)($w['experience_json']??'{}'),true)?:[];$nivoAiEnabled=false;try{$bq=appDb()->prepare('SELECT enabled FROM bot_profiles WHERE tenant_id=? LIMIT 1');$bq->execute([$tid]);$nivoAiEnabled=(int)($bq->fetchColumn()?:0)===1;}catch(Throwable $e){}$launcherPreview=trim((string)($w['launcher_label']??''));if($launcherPreview===''||mb_strtolower($launcherPreview)==='¿necesitas ayuda?')$launcherPreview='NIVO Web Chat · ¿Necesitas ayuda?';
$inst=[];$webStats=['sites'=>0,'active'=>0,'detected'=>0,'visitors'=>0];if($w){$q=appDb()->prepare('SELECT wi.*,u.name created_by_name FROM webchat_installations wi LEFT JOIN users u ON u.id=wi.created_by WHERE wi.tenant_id=? AND wi.widget_id=? ORDER BY wi.created_at DESC');$q->execute([$tid,$w['id']]);$inst=$q->fetchAll();$webStats['sites']=count($inst);foreach($inst as $site){if(!empty($site['enabled']))$webStats['active']++;if(!empty($site['last_seen_at']))$webStats['detected']++;}try{$sq=appDb()->prepare('SELECT COUNT(*) FROM webchat_visitors WHERE tenant_id=? AND widget_id=?');$sq->execute([$tid,$w['id']]);$webStats['visitors']=(int)$sq->fetchColumn();}catch(Throwable $e){}}
$base=((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??'/'),'/');
$snippet=$w?'<script src="'.$base.'/nivo-widget.js" data-zynko-key="'.$w['public_key'].'" async></script>':'';$snippet=str_replace('\\/','/',$snippet);$siteLimit=zynkoPlanLimit($zynkoPlanContext,'max_webchat_sites');$dailyLimit=zynkoPlanLimit($zynkoPlanContext,'max_daily_chats');$dailyUsage=zynkoPlanDailyChatUsage(appDb(),$tid);$siteLimitReached=$siteLimit!==null&&$webStats['active']>=$siteLimit;
?>
<div class="nivo-webchat-page"><section class="welcome nivo-page-welcome"><div><small>CANAL PROPIO · TIEMPO REAL</small><h1>NIVO Web Chat</h1><p>Crea un chat inteligente de tu empresa, instálalo en tus sitios y atiéndelo desde la misma Bandeja de ZYNKO.</p></div><div class="nivo-welcome-tools"><div class="nivo-identity-card" aria-label="Identidad de NIVO"><img src="assets/img/nivo-email.png" alt="NIVO"><span><b>NIVO</b><small>Tu asistente inteligente</small></span></div><span class="status-badge connected"><i class="fa-solid fa-bolt"></i> WebSocket + NIVO</span></div></section><?php if(!$zynkoPlanContext['unrestricted']):?><div class="webchat-plan-note"><div><span><i class="fa-solid fa-gift"></i></span><span><b><?=htmlspecialchars($zynkoPlanContext['plan_name'])?> · NIVO Web Chat incluido</b><small><?=$siteLimit?$siteLimit.' sitio'.($siteLimit===1?'':'s'):'Sitios ilimitados'?> · <?=$dailyLimit?$dailyLimit.' chats nuevos por día':'Chats nuevos ilimitados'?>. Las conversaciones existentes pueden continuar sin límite de mensajes.</small></span></div><span class="plan-limit-pill"><?=$dailyLimit?min($dailyUsage,$dailyLimit).'/'.$dailyLimit:'∞'?> chats hoy</span></div><?php endif?>
<div class="webchat-layout"><section class="panel"><div class="panel-head"><div><b>Diseño y comportamiento</b><small>Los cambios se aplican al mismo widget en todos los sitios autorizados.</small></div></div><form id="webchatWidgetForm"><input type="hidden" name="action" value="webchat_widget_save"><input type="hidden" name="widget_id" value="<?=$w['id']??0?>"><div class="settings-grid">
<div class="field"><label>Nombre interno</label><input name="name" value="<?=htmlspecialchars($w['name']??'NIVO Web Chat')?>" required></div>
<div class="field"><label>Posición</label><select name="position" class="select2"><?php foreach(['bottom-right'=>'Abajo · derecha','bottom-left'=>'Abajo · izquierda','top-right'=>'Arriba · derecha','top-left'=>'Arriba · izquierda'] as $v=>$l):?><option value="<?=$v?>" <?=($w['position']??'bottom-right')===$v?'selected':''?>><?=$l?></option><?php endforeach?></select></div>
<div class="field"><label>Color principal</label><input name="accent_color" type="color" value="<?=htmlspecialchars($w['accent_color']??'#0F766E')?>"></div>
<div class="field"><label>Texto junto al botón</label><input name="launcher_label" maxlength="80" value="<?=htmlspecialchars($launcherPreview)?>" placeholder="NIVO Web Chat · ¿Necesitas ayuda?"><small class="field-help">Se muestra junto al botón flotante. Recomendado: incluir el nombre NIVO para que el visitante identifique el canal.</small></div>
<div class="field"><label>Cómo inicia el chat</label><select name="display_mode" class="select2"><option value="launcher" <?=($w['display_mode']??'launcher')==='launcher'?'selected':''?>>Icono flotante · cerrado</option><option value="open" <?=($w['display_mode']??'launcher')==='open'?'selected':''?>>Ventana abierta al cargar</option></select><small class="field-help">El visitante siempre puede minimizarlo o volverlo a abrir.</small></div>
<div class="field"><label>Estado</label><label class="switch-line"><input name="enabled" type="checkbox" <?=!$w||$w['enabled']?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Widget activo</span></label></div>
<div class="field"><label>Título de bienvenida</label><input name="welcome_title" value="<?=htmlspecialchars($w['welcome_title']??'¡Hola! Soy NIVO')?>"></div>
<div class="field"><label>Identidad del asistente</label><input name="assistant_subtitle" value="<?=htmlspecialchars($assistantSubtitle)?>"><small class="field-help">Por defecto NIVO se presenta como asistente de tu empresa. Puedes personalizar este texto.</small></div>
<div class="field"><label>Notificaciones</label><label class="switch-line"><input name="sound_enabled" type="checkbox" <?=!$w||($w['sound_enabled']??1)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Sonido al recibir respuesta</span></label></div>
<div class="field"><label>Solicitar datos</label><div class="switch-stack"><label class="switch-line"><input name="ask_name" type="checkbox" <?=!$w||$w['ask_name']?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Nombre</span></label><label class="switch-line"><input name="ask_email" type="checkbox" <?=($w['ask_email']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Correo</span></label></div><label class="switch-line compact-switch"><input name="profile_required" type="checkbox" <?=($w['profile_required']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Exigir datos seleccionados antes de enviar</span></label></div>
<div class="field full"><label>Mensaje inicial</label><textarea name="welcome_message" rows="3"><?=htmlspecialchars($w['welcome_message']??'¿En qué puedo ayudarte hoy?')?></textarea></div>
<div class="field full privacy-config"><label>Privacidad del visitante</label><label class="switch-line"><input name="privacy_enabled" type="checkbox" <?=($w['privacy_enabled']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Mostrar aviso de privacidad antes de enviar</span></label><div class="privacy-grid"><input name="privacy_text" maxlength="240" value="<?=htmlspecialchars($w['privacy_text']??'Al continuar aceptas nuestra política de privacidad.')?>" placeholder="Texto del aviso"><input name="privacy_url" type="url" value="<?=htmlspecialchars($w['privacy_url']??'')?>" placeholder="https://empresa.com/privacidad"></div></div>
<div class="field full"><label class="switch-line <?=$siteLimit===1?'plan-readonly-switch':''?>"><input name="allow_multiple_domains" type="checkbox" <?=($siteLimit===1?'':(!isset($w['allow_multiple_domains'])||$w['allow_multiple_domains']?'checked':''))?> <?=$siteLimit===1?'disabled':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Permitir instalar este chat en más de un sitio</span></label><small class="field-help"><?=$siteLimit===1?'Tu plan actual permite un solo sitio web autorizado.':'Si lo desactivas, solo podrás mantener un dominio autorizado activo.'?></small></div>
<div class="field full webchat-advanced-box"><div class="webchat-advanced-head"><div><b><i class="fa-solid fa-wand-magic-sparkles"></i> Experiencia avanzada</b><small>10 ajustes prácticos para hacer el chat más claro, rápido y cómodo sin cambiar su identidad visual.</small></div></div><div class="webchat-advanced-grid">
 <div class="field"><label>Apertura automática</label><div class="input-suffix"><input name="auto_open_delay" type="number" min="0" max="30" value="<?=htmlspecialchars((string)($experience['auto_open_delay']??0))?>"><span>seg</span></div><small class="field-help">0 = no abrir automáticamente.</small></div>
 <div class="field"><label>Retardo visual de respuesta</label><div class="input-suffix"><input name="typing_delay_ms" type="number" min="0" max="2500" step="50" value="<?=htmlspecialchars((string)($experience['typing_delay_ms']??450))?>"><span>ms</span></div><small class="field-help">Hace más natural la transición de respuesta.</small></div>
 <div class="field"><label>Límite por mensaje</label><div class="input-suffix"><input name="max_message_length" type="number" min="120" max="3000" value="<?=htmlspecialchars((string)($experience['max_message_length']??1000))?>"><span>car.</span></div></div>
 <div class="field"><label>Mensajes por minuto</label><input name="rate_limit_per_minute" type="number" min="2" max="30" value="<?=htmlspecialchars((string)($experience['rate_limit_per_minute']??12))?>"><small class="field-help">Protección simple contra abuso.</small></div>
 <div class="field full"><label>Respuestas rápidas</label><textarea name="quick_replies" rows="2" maxlength="650" placeholder="Precios, Hablar con una persona, NIVO Web Chat"><?=htmlspecialchars(implode("
",(array)($experience['quick_replies']??['Conocer ZYNKO','NIVO Web Chat','Hablar con una persona'])))?></textarea><small class="field-help">Una opción por línea; máximo 8.</small></div>
 <div class="webchat-toggle-grid">
  <label class="switch-line"><input name="typing_indicator" type="checkbox" <?=!array_key_exists('typing_indicator',$experience)||!empty($experience['typing_indicator'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Mostrar “NIVO está escribiendo”</span></label>
  <label class="switch-line"><input name="show_timestamps" type="checkbox" <?=!empty($experience['show_timestamps'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Mostrar hora de mensajes</span></label>
  <label class="switch-line"><input name="quick_replies_enabled" type="checkbox" <?=!empty($experience['quick_replies_enabled'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Activar respuestas rápidas</span></label>
  <label class="switch-line"><input name="remember_open_state" type="checkbox" <?=!array_key_exists('remember_open_state',$experience)||!empty($experience['remember_open_state'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Recordar si el chat quedó abierto</span></label>
  <label class="switch-line"><input name="prevent_double_submit" type="checkbox" <?=!array_key_exists('prevent_double_submit',$experience)||!empty($experience['prevent_double_submit'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Evitar doble envío</span></label>
  <label class="switch-line"><input name="show_branding" type="checkbox" <?=!array_key_exists('show_branding',$experience)||!empty($experience['show_branding'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Mostrar marca NIVO/ZYNKO</span></label>
  <label class="switch-line"><input name="close_on_escape" type="checkbox" <?=!array_key_exists('close_on_escape',$experience)||!empty($experience['close_on_escape'])?'checked':''?>><span class="switch-control"></span><span class="switch-label-text">Cerrar con tecla ESC</span></label>
 </div>
</div></div>
</div><div class="form-actions"><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar NIVO Web Chat</button></div></form></section>
<div class="nivo-webchat-rail" role="complementary" aria-label="Vista previa y asistente NIVO"><section class="panel webchat-preview"><div class="panel-head"><div><b>Vista previa real del visitante</b><small>La marca, el texto flotante y el encabezado se muestran igual en los sitios autorizados.</small></div></div><div class="preview-stage"><div class="preview-chat"><div class="preview-head"><span class="nivo-orb nivo-brand-orb"><img src="assets/img/nivo-email.png" alt="NIVO"></span><div><b><?=htmlspecialchars($w['welcome_title']??'¡Hola! Soy NIVO')?></b><small><?=htmlspecialchars($assistantSubtitle)?> · En línea</small><?php if($nivoAiEnabled):?><span class="preview-ai-state"><i class="fa-solid fa-wand-magic-sparkles"></i> NIVO IA activo</span><?php endif?></div></div><div class="preview-body"><span><?=htmlspecialchars($w['welcome_message']??'¿En qué puedo ayudarte hoy?')?></span></div><div class="preview-input">Escribe un mensaje… <i class="fa-solid fa-paper-plane"></i></div></div><div class="preview-launcher-wrap"><span class="preview-launcher-label"><?=htmlspecialchars($launcherPreview)?></span><button class="preview-launcher preview-launcher-brand" style="background:<?=htmlspecialchars($w['accent_color']??'#0F766E')?>"><img src="assets/img/nivo-email.png" alt="NIVO"></button></div></div></section><section class="nivo-companion-card"><div class="nivo-companion-copy"><b>NIVO Web Chat + NIVO IA</b><small><?= $nivoAiEnabled?'El asistente está activo: puede responder reglas y conocimiento aprobado y transferir a humano cuando corresponde.':'El Web Chat está listo. Activa NIVO IA para responder automáticamente con reglas y conocimiento aprobado.' ?></small></div><div class="nivo-companion-visual"><img src="assets/img/nivo-email.png" alt="NIVO, asistente inteligente"></div></section></div></div>
<section class="webchat-kpis" aria-label="Uso de NIVO Web Chat"><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-globe"></i></span><div><b><?=$webStats['sites']?></b><small>Sitios registrados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-circle-check"></i></span><div><b><?=$webStats['active']?></b><small>Sitios autorizados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-comments"></i></span><div><b><?=$dailyUsage?></b><small>Chats nuevos hoy<?=$dailyLimit?' · límite '.$dailyLimit:''?></small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-signal"></i></span><div><b><?=$webStats['detected']?></b><small>Widgets detectados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-users"></i></span><div><b><?=$webStats['visitors']?></b><small>Visitantes registrados</small></div></article></section>
<section class="panel spaced" id="installations"><div class="panel-head"><div><b>Instalación en sitios web</b><small>Autoriza el dominio y copia una sola línea. Puedes desautorizar cualquier sitio desde aquí.</small></div></div>
<?php if(!$w):?><div class="empty-compact"><i class="fa-solid fa-code"></i><b>Guarda primero tu widget</b><span>Al guardarlo se generará una clave pública de instalación.</span></div><?php else:?><div class="embed-box"><div><b>Código de inserción</b><small>Pégalo una sola vez al final del HTML del sitio autorizado. ZYNKO se encarga del resto.</small></div><code id="embedCode"><?=htmlspecialchars($snippet)?></code><button type="button" class="secondary-action" id="copyEmbed"><i class="fa-regular fa-copy"></i> Copiar código</button></div>
<form id="installationForm" class="installation-form"><input type="hidden" name="action" value="webchat_installation_add"><input type="hidden" name="widget_id" value="<?=$w['id']?>"><div class="field"><label>Dominio autorizado</label><input name="domain" required placeholder="www.cliente.com" <?=$siteLimitReached?'disabled':''?>></div><div class="field"><label>Etiqueta opcional</label><input name="label" placeholder="Sitio principal" <?=$siteLimitReached?'disabled':''?>></div><button class="primary" <?=$siteLimitReached?'disabled':''?>><i class="fa-solid <?=$siteLimitReached?'fa-lock':'fa-plus'?>"></i> <?=$siteLimitReached?'Límite de sitios alcanzado':'Autorizar sitio'?></button></form><?php if($siteLimitReached):?><small class="field-help"><i class="fa-solid fa-circle-info"></i> Tu plan permite <?=$siteLimit?> sitio web autorizado. Desautoriza el actual o cambia de plan.</small><?php endif?>
<div class="installation-list"><?php if(!$inst):?><div class="empty-compact"><i class="fa-solid fa-globe"></i><span>Todavía no hay sitios autorizados.</span></div><?php endif;foreach($inst as $i):?><div class="installation-row"><span class="channel-icon webchat"><i class="fa-solid fa-globe"></i></span><div class="installation-copy"><b><?=htmlspecialchars($i['label']?:$i['domain'])?></b><small><span><?=htmlspecialchars($i['domain'])?></span><span>Agregado por <?=htmlspecialchars($i['created_by_name']?:'Sistema')?></span><span><?=$i['last_seen_at']?'Último uso '.htmlspecialchars($i['last_seen_at']):'Aún no detectado'?></span></small></div><span class="status-badge <?=$i['enabled']?'connected':'muted'?>"><?=$i['enabled']?'Autorizado':'Desactivado'?></span><button class="icon-btn install-edit" data-id="<?=$i['id']?>" data-domain="<?=htmlspecialchars($i['domain'],ENT_QUOTES,'UTF-8')?>" data-label="<?=htmlspecialchars((string)($i['label']??''),ENT_QUOTES,'UTF-8')?>" title="Editar nombre o dominio"><i class="fa-solid fa-pen"></i></button><button class="icon-btn install-toggle" data-id="<?=$i['id']?>" title="Activar / desactivar"><i class="fa-solid fa-power-off"></i></button><button class="icon-btn danger install-delete" data-id="<?=$i['id']?>" title="Desautorizar"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div><?php endif?></section><div class="modal-shell" id="installationEditModal"><div class="modal-card webchat-install-edit-modal"><div class="modal-head"><div><b>Editar sitio autorizado</b><small>Asigna un nombre claro para reconocer dónde está instalado NIVO Web Chat.</small></div><button type="button" class="modal-close"><i class="fa-solid fa-xmark"></i></button></div><form id="installationEditForm"><input type="hidden" name="action" value="webchat_installation_update"><input type="hidden" name="installation_id" value=""><div class="settings-grid"><div class="field"><label>Nombre / etiqueta</label><input name="label" maxlength="120" placeholder="Ej. Sitio corporativo"></div><div class="field"><label>Dominio autorizado</label><input name="domain" maxlength="190" required placeholder="www.cliente.com"></div></div><div class="webchat-install-help"><i class="fa-solid fa-circle-info"></i><span>La etiqueta es solo para identificar el sitio dentro de ZYNKO. El dominio es el que autoriza técnicamente el widget.</span></div><div class="modal-actions"><button type="button" class="soft modal-close"><i class="fa-solid fa-xmark"></i> Cancelar</button><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar cambios</button></div></form></div></div>
</div><script>document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.nivo-webchat-page .nivo-webchat-rail')?.style.removeProperty('height');document.querySelectorAll('.webchat-kpi b').forEach(el=>{const end=parseInt(el.textContent,10);if(!Number.isFinite(end)||end<=0)return;const start=performance.now(),duration=520;const tick=now=>{const p=Math.min(1,(now-start)/duration);el.textContent=Math.round(end*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});const post=async fd=>{const r=await fetch(location.href,{method:'POST',body:fd});const j=await r.json();if(!j.ok)throw new Error(j.message);return j};const bind=(id)=>{const f=document.getElementById(id);if(f)f.addEventListener('submit',async e=>{e.preventDefault();try{await post(new FormData(f));showNotify('success','Guardado','Configuración actualizada.');setTimeout(()=>location.reload(),500)}catch(x){showNotify('error','No se pudo guardar',x.message)}})};bind('webchatWidgetForm');bind('installationForm');const zynkoEmbedSnippet=<?=json_encode($snippet,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;document.getElementById('copyEmbed')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(zynkoEmbedSnippet);showNotify('success','Copiado','Pega el código en tu sitio web.')});const editModal=document.getElementById('installationEditModal'),editForm=document.getElementById('installationEditForm');document.querySelectorAll('.install-edit').forEach(b=>b.addEventListener('click',()=>{if(!editModal||!editForm)return;editForm.installation_id.value=b.dataset.id||'';editForm.label.value=b.dataset.label||'';editForm.domain.value=b.dataset.domain||'';window.ZynkoModal?.open('#installationEditModal')}));if(editForm)editForm.addEventListener('submit',async e=>{e.preventDefault();try{await post(new FormData(editForm));showNotify('success','Sitio actualizado','El nombre y dominio autorizado quedaron actualizados.');setTimeout(()=>location.reload(),450)}catch(x){showNotify('error','No se pudo actualizar',x.message)}});document.querySelectorAll('.install-toggle').forEach(b=>b.onclick=async()=>{let f=new FormData();f.append('action','webchat_installation_toggle');f.append('installation_id',b.dataset.id);try{await post(f);location.reload()}catch(x){showNotify('error','Error',x.message)}});document.querySelectorAll('.install-delete').forEach(b=>b.onclick=async()=>{const ask=await Swal.fire({title:'Desautorizar sitio',text:'El chat dejará de funcionar inmediatamente en este dominio.',icon:'warning',showCancelButton:true,confirmButtonText:'Sí, desautorizar',cancelButtonText:'Cancelar',allowOutsideClick:false});if(!ask.isConfirmed)return;let f=new FormData();f.append('action','webchat_installation_delete');f.append('installation_id',b.dataset.id);try{await post(f);location.reload()}catch(x){showNotify('error','Error',x.message)}})});</script>
<?php require __DIR__.'/partials/bottom.php'; ?>
