<?php
$title='NIVO Web Chat'; require __DIR__.'/partials/top.php'; $tid=(int)$_SESSION['user']['tenant_id'];
$q=appDb()->prepare('SELECT * FROM webchat_widgets WHERE tenant_id=? ORDER BY id LIMIT 1');$q->execute([$tid]);$w=$q->fetch();$tq=appDb()->prepare('SELECT name FROM tenants WHERE id=? LIMIT 1');$tq->execute([$tid]);$tenantName=(string)($tq->fetchColumn()?:($_SESSION['user']['company']??'Tu empresa'));$assistantSubtitle=trim((string)($w['assistant_subtitle']??''));if($assistantSubtitle==='')$assistantSubtitle='Asistente virtual de '.$tenantName;
$inst=[];$webStats=['sites'=>0,'active'=>0,'detected'=>0,'visitors'=>0];if($w){$q=appDb()->prepare('SELECT wi.*,u.name created_by_name FROM webchat_installations wi LEFT JOIN users u ON u.id=wi.created_by WHERE wi.tenant_id=? AND wi.widget_id=? ORDER BY wi.created_at DESC');$q->execute([$tid,$w['id']]);$inst=$q->fetchAll();$webStats['sites']=count($inst);foreach($inst as $site){if(!empty($site['enabled']))$webStats['active']++;if(!empty($site['last_seen_at']))$webStats['detected']++;}try{$sq=appDb()->prepare('SELECT COUNT(*) FROM webchat_visitors WHERE tenant_id=? AND widget_id=?');$sq->execute([$tid,$w['id']]);$webStats['visitors']=(int)$sq->fetchColumn();}catch(Throwable $e){}}
$base=((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').rtrim(dirname($_SERVER['SCRIPT_NAME']??'/'),'/');
$snippet=$w?'<script src="'.$base.'/nivo-widget.js" data-zynko-key="'.$w['public_key'].'" async></script>':'';
?>
<div class="nivo-webchat-page"><section class="welcome"><div><small>CANAL PROPIO · TIEMPO REAL</small><h1>NIVO Web Chat</h1><p>Crea un chat inteligente de tu empresa, instálalo en tus sitios y atiéndelo desde la misma Bandeja de ZYNKO.</p></div><span class="status-badge connected"><i class="fa-solid fa-bolt"></i> WebSocket + NIVO</span></section>
<div class="webchat-layout"><section class="panel"><div class="panel-head"><div><b>Diseño y comportamiento</b><small>Los cambios se aplican al mismo widget en todos los sitios autorizados.</small></div></div><form id="webchatWidgetForm"><input type="hidden" name="action" value="webchat_widget_save"><input type="hidden" name="widget_id" value="<?=$w['id']??0?>"><div class="settings-grid">
<div class="field"><label>Nombre interno</label><input name="name" value="<?=htmlspecialchars($w['name']??'NIVO Web Chat')?>" required></div>
<div class="field"><label>Posición</label><select name="position" class="select2"><?php foreach(['bottom-right'=>'Abajo · derecha','bottom-left'=>'Abajo · izquierda','top-right'=>'Arriba · derecha','top-left'=>'Arriba · izquierda'] as $v=>$l):?><option value="<?=$v?>" <?=($w['position']??'bottom-right')===$v?'selected':''?>><?=$l?></option><?php endforeach?></select></div>
<div class="field"><label>Color principal</label><input name="accent_color" type="color" value="<?=htmlspecialchars($w['accent_color']??'#0F766E')?>"></div>
<div class="field"><label>Texto junto al botón</label><input name="launcher_label" maxlength="80" value="<?=htmlspecialchars($w['launcher_label']??'')?>" placeholder="Ej. ¿Necesitas ayuda?"><small class="field-help">Opcional. Hace más visible el acceso al chat.</small></div>
<div class="field"><label>Cómo inicia el chat</label><select name="display_mode" class="select2"><option value="launcher" <?=($w['display_mode']??'launcher')==='launcher'?'selected':''?>>Icono flotante · cerrado</option><option value="open" <?=($w['display_mode']??'launcher')==='open'?'selected':''?>>Ventana abierta al cargar</option></select><small class="field-help">El visitante siempre puede minimizarlo o volverlo a abrir.</small></div>
<div class="field"><label>Estado</label><label class="switch-line"><input name="enabled" type="checkbox" <?=!$w||$w['enabled']?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Widget activo</span></label></div>
<div class="field"><label>Título de bienvenida</label><input name="welcome_title" value="<?=htmlspecialchars($w['welcome_title']??'¡Hola! Soy NIVO')?>"></div>
<div class="field"><label>Identidad del asistente</label><input name="assistant_subtitle" value="<?=htmlspecialchars($assistantSubtitle)?>"><small class="field-help">Por defecto NIVO se presenta como asistente de tu empresa. Puedes personalizar este texto.</small></div>
<div class="field"><label>Notificaciones</label><label class="switch-line"><input name="sound_enabled" type="checkbox" <?=!$w||($w['sound_enabled']??1)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Sonido al recibir respuesta</span></label></div>
<div class="field"><label>Solicitar datos</label><div class="switch-stack"><label class="switch-line"><input name="ask_name" type="checkbox" <?=!$w||$w['ask_name']?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Nombre</span></label><label class="switch-line"><input name="ask_email" type="checkbox" <?=($w['ask_email']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Correo</span></label></div><label class="switch-line compact-switch"><input name="profile_required" type="checkbox" <?=($w['profile_required']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Exigir datos seleccionados antes de enviar</span></label></div>
<div class="field full"><label>Mensaje inicial</label><textarea name="welcome_message" rows="3"><?=htmlspecialchars($w['welcome_message']??'¿En qué puedo ayudarte hoy?')?></textarea></div>
<div class="field full privacy-config"><label>Privacidad del visitante</label><label class="switch-line"><input name="privacy_enabled" type="checkbox" <?=($w['privacy_enabled']??0)?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Mostrar aviso de privacidad antes de enviar</span></label><div class="privacy-grid"><input name="privacy_text" maxlength="240" value="<?=htmlspecialchars($w['privacy_text']??'Al continuar aceptas nuestra política de privacidad.')?>" placeholder="Texto del aviso"><input name="privacy_url" type="url" value="<?=htmlspecialchars($w['privacy_url']??'')?>" placeholder="https://empresa.com/privacidad"></div></div>
<div class="field full"><label class="switch-line"><input name="allow_multiple_domains" type="checkbox" <?=!$w||$w['allow_multiple_domains']?'checked':''?>><span class="switch-control" aria-hidden="true"></span><span class="switch-label-text">Permitir instalar este chat en más de un sitio</span></label><small class="field-help">Si lo desactivas, solo podrás mantener un dominio autorizado activo.</small></div>
</div><div class="form-actions"><button class="primary"><i class="fa-solid fa-floppy-disk"></i> Guardar NIVO Web Chat</button></div></form></section>
<section class="panel webchat-preview"><div class="panel-head"><div><b>Vista previa</b><small>Así verá el visitante tu chat.</small></div></div><div class="preview-stage"><div class="preview-chat"><div class="preview-head"><span class="nivo-orb"><i class="fa-solid fa-robot"></i></span><div><b><?=htmlspecialchars($w['welcome_title']??'¡Hola! Soy NIVO')?></b><small><?=htmlspecialchars($assistantSubtitle)?> · En línea</small></div></div><div class="preview-body"><span><?=htmlspecialchars($w['welcome_message']??'¿En qué puedo ayudarte hoy?')?></span></div><div class="preview-input">Escribe un mensaje… <i class="fa-solid fa-paper-plane"></i></div></div><button class="preview-launcher" style="background:<?=htmlspecialchars($w['accent_color']??'#0F766E')?>"><i class="fa-solid fa-message"></i></button></div></section></div>
<section class="webchat-kpis" aria-label="Uso de NIVO Web Chat"><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-globe"></i></span><div><b><?=$webStats['sites']?></b><small>Sitios registrados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-circle-check"></i></span><div><b><?=$webStats['active']?></b><small>Sitios autorizados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-signal"></i></span><div><b><?=$webStats['detected']?></b><small>Widgets detectados</small></div></article><article class="webchat-kpi kpi-enter"><span><i class="fa-solid fa-users"></i></span><div><b><?=$webStats['visitors']?></b><small>Visitantes registrados</small></div></article></section>
<section class="panel spaced" id="installations"><div class="panel-head"><div><b>Instalación en sitios web</b><small>Autoriza el dominio y copia una sola línea. Puedes desautorizar cualquier sitio desde aquí.</small></div></div>
<?php if(!$w):?><div class="empty-compact"><i class="fa-solid fa-code"></i><b>Guarda primero tu widget</b><span>Al guardarlo se generará una clave pública de instalación.</span></div><?php else:?><div class="embed-box"><div><b>Código de inserción</b><small>Pégalo antes de <code>&lt;/body&gt;</code> en el sitio autorizado.</small></div><code id="embedCode"><?=htmlspecialchars($snippet)?></code><button type="button" class="secondary-action" id="copyEmbed"><i class="fa-regular fa-copy"></i> Copiar código</button></div>
<form id="installationForm" class="installation-form"><input type="hidden" name="action" value="webchat_installation_add"><input type="hidden" name="widget_id" value="<?=$w['id']?>"><div class="field"><label>Dominio autorizado</label><input name="domain" required placeholder="www.cliente.com"></div><div class="field"><label>Etiqueta opcional</label><input name="label" placeholder="Sitio principal"></div><button class="primary"><i class="fa-solid fa-plus"></i> Autorizar sitio</button></form>
<div class="installation-list"><?php if(!$inst):?><div class="empty-compact"><i class="fa-solid fa-globe"></i><span>Todavía no hay sitios autorizados.</span></div><?php endif;foreach($inst as $i):?><div class="installation-row"><span class="channel-icon webchat"><i class="fa-solid fa-globe"></i></span><div><b><?=htmlspecialchars($i['label']?:$i['domain'])?></b><small><?=htmlspecialchars($i['domain'])?> · agregado por <?=htmlspecialchars($i['created_by_name']?:'Sistema')?> · <?=$i['last_seen_at']?'Último uso '.htmlspecialchars($i['last_seen_at']):'Aún no detectado'?></small></div><span class="status-badge <?=$i['enabled']?'connected':'muted'?>"><?=$i['enabled']?'Autorizado':'Desactivado'?></span><button class="icon-btn install-toggle" data-id="<?=$i['id']?>" title="Activar / desactivar"><i class="fa-solid fa-power-off"></i></button><button class="icon-btn danger install-delete" data-id="<?=$i['id']?>" title="Desautorizar"><i class="fa-solid fa-trash"></i></button></div><?php endforeach?></div><?php endif?></section>
</div><script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.webchat-kpi b').forEach(el=>{const end=parseInt(el.textContent,10);if(!Number.isFinite(end)||end<=0)return;const start=performance.now(),duration=520;const tick=now=>{const p=Math.min(1,(now-start)/duration);el.textContent=Math.round(end*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});const post=async fd=>{const r=await fetch(location.href,{method:'POST',body:fd});const j=await r.json();if(!j.ok)throw new Error(j.message);return j};const bind=(id)=>{const f=document.getElementById(id);if(f)f.addEventListener('submit',async e=>{e.preventDefault();try{await post(new FormData(f));showNotify('success','Guardado','Configuración actualizada.');setTimeout(()=>location.reload(),500)}catch(x){showNotify('error','No se pudo guardar',x.message)}})};bind('webchatWidgetForm');bind('installationForm');document.getElementById('copyEmbed')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(document.getElementById('embedCode').textContent);showNotify('success','Copiado','Pega el código en tu sitio web.')});document.querySelectorAll('.install-toggle').forEach(b=>b.onclick=async()=>{let f=new FormData();f.append('action','webchat_installation_toggle');f.append('installation_id',b.dataset.id);try{await post(f);location.reload()}catch(x){showNotify('error','Error',x.message)}});document.querySelectorAll('.install-delete').forEach(b=>b.onclick=async()=>{const ask=await Swal.fire({title:'Desautorizar sitio',text:'El chat dejará de funcionar inmediatamente en este dominio.',icon:'warning',showCancelButton:true,confirmButtonText:'Sí, desautorizar',cancelButtonText:'Cancelar',allowOutsideClick:false});if(!ask.isConfirmed)return;let f=new FormData();f.append('action','webchat_installation_delete');f.append('installation_id',b.dataset.id);try{await post(f);location.reload()}catch(x){showNotify('error','Error',x.message)}})});</script>
<?php require __DIR__.'/partials/bottom.php'; ?>
